-- =============================================================================
-- 32 · Copiloto de IA para asesores y asistente del supervisor (docs/data-model.md §19.3)
--
-- copilot_suggestions (particionada): respuestas sugeridas / borradores / siguiente mejor acción / resúmenes que
-- se muestran al asesor, con su resultado (aceptada, editada, descartada) para medir adopción y calidad.
-- Resumen de traspaso en la conversación. assistant_threads / assistant_messages: chat del supervisor con
-- herramientas sobre los reportes (sin SQL libre).
-- =============================================================================

create table public.copilot_suggestions (
  id               bigint generated by default as identity,
  organization_id  bigint not null,
  conversation_id  bigint not null,
  agent_id         bigint,                        -- asesor al que se le mostró
  message_id       bigint,                        -- mensaje del cliente que la originó
  kind             text not null check (kind in ('reply', 'draft', 'next_action', 'summary', 'rewrite', 'translate')),
  content          jsonb not null,                -- reply: {text, alternatives[]}; next_action: {action, label, payload, reason}
  status           text not null default 'shown' check (status in ('shown', 'accepted', 'edited', 'dismissed', 'expired')),
  final_text       text,                          -- lo que el asesor envió (si editó)
  edit_distance    int,                           -- cambios respecto a la sugerencia (calidad)
  latency_ms       int,
  ai_call_id       bigint,
  decided_at       timestamptz,
  created_at       timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);
create table public.copilot_suggestions_default partition of public.copilot_suggestions default;
select public.ensure_monthly_partitions('public.copilot_suggestions', 3);
create index copilot_suggestions_conv_idx on public.copilot_suggestions (conversation_id, created_at desc);
create index copilot_suggestions_org_idx on public.copilot_suggestions (organization_id, created_at);

alter table public.conversations
  add column handoff_summary     text,           -- resumen para el asesor al transferir
  add column handoff_summary_at  timestamptz,
  add column summary             text,           -- resumen vivo de la conversación (se actualiza al cerrar)
  add column summary_at          timestamptz;

-- Asistente del supervisor ------------------------------------------------------------------------------------
create table public.assistant_threads (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  agent_id         bigint not null references public.agents(id) on delete cascade,
  title            text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index assistant_threads_agent_idx on public.assistant_threads (agent_id, updated_at desc);
create trigger trg_assistant_threads_updated before update on public.assistant_threads
  for each row execute function public.set_updated_at();

create table public.assistant_messages (
  id               bigint generated by default as identity primary key,
  thread_id        bigint not null references public.assistant_threads(id) on delete cascade,
  role             text not null check (role in ('user', 'assistant', 'tool')),
  content          text,
  tool_calls       jsonb,                         -- [{name, input}] / resultados resumidos
  charts           jsonb,                         -- datos listos para graficar en el panel
  ai_call_id       bigint,
  created_at       timestamptz not null default now()
);
create index assistant_messages_thread_idx on public.assistant_messages (thread_id, id);

-- Reporting de adopción del copiloto
create table reporting.daily_copilot (
  organization_id  bigint not null,
  day              date not null,
  agent_id         bigint not null,
  kind             text not null,
  shown            int not null default 0,
  accepted         int not null default 0,
  edited           int not null default 0,
  dismissed        int not null default 0,
  latency_sum_ms   bigint not null default 0,
  refreshed_at     timestamptz not null default now(),
  primary key (organization_id, day, agent_id, kind)
);

create or replace function reporting.refresh_copilot(p_org bigint, p_from date, p_to date) returns void
language plpgsql set search_path = reporting, public, pg_temp as $$
declare
  tz  text := (select timezone from public.organizations where id = p_org);
  lo  timestamptz := (p_from::timestamp at time zone tz);
  hi  timestamptz := ((p_to + 1)::timestamp at time zone tz);
begin
  delete from reporting.daily_copilot where organization_id = p_org and day between p_from and p_to;
  insert into reporting.daily_copilot (organization_id, day, agent_id, kind, shown, accepted, edited, dismissed, latency_sum_ms)
  select p_org, (s.created_at at time zone tz)::date, coalesce(s.agent_id, 0), s.kind, count(*),
         count(*) filter (where s.status = 'accepted'), count(*) filter (where s.status = 'edited'),
         count(*) filter (where s.status = 'dismissed'), coalesce(sum(s.latency_ms), 0)
  from public.copilot_suggestions s
  where s.organization_id = p_org and s.created_at >= lo and s.created_at < hi
  group by 2, 3, 4;
end $$;
revoke all on function reporting.refresh_copilot(bigint, date, date) from public;

create or replace function reporting.refresh_range(p_org bigint, p_from date, p_to date) returns void
language plpgsql set search_path = reporting, public, pg_temp as $$
begin
  perform reporting.refresh_core(p_org, p_from, p_to);
  perform reporting.refresh_flows(p_org, p_from, p_to);
  perform reporting.refresh_links(p_org, p_from, p_to);
  perform reporting.refresh_channels(p_org, p_from, p_to);
  perform reporting.refresh_qa(p_org, p_from, p_to);
  perform reporting.refresh_api(p_org, p_from, p_to);
  perform reporting.refresh_products(p_org, p_from, p_to);
  perform reporting.refresh_ads(p_org, p_from, p_to);
  perform reporting.refresh_service(p_org, p_from, p_to);
  perform reporting.refresh_copilot(p_org, p_from, p_to);
end $$;

-- Propósitos de IA nuevos
alter table public.ai_calls drop constraint ai_calls_purpose_check;
alter table public.ai_calls add constraint ai_calls_purpose_check check (purpose in
  ('chat', 'classification', 'learning', 'flow', 'json_edit', 'test', 'qa', 'agent_test', 'onboarding', 'golden',
   'copilot', 'assistant'));
alter table public.cortexes drop constraint cortexes_purpose_check;
alter table public.cortexes add constraint cortexes_purpose_check check (purpose in
  ('chat', 'classification', 'learning', 'flow', 'json_edit', 'qa', 'agent_test', 'onboarding', 'golden', 'copilot',
   'assistant', 'any'));

do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('copilot-partitions', '45 3 * * *', $c$
      select public.ensure_monthly_partitions('public.copilot_suggestions', 3);
      select public.drop_old_partitions('public.copilot_suggestions', 12);
    $c$);
  end if;
end $$;

alter table public.copilot_suggestions enable row level security;
alter table public.assistant_threads enable row level security;
alter table public.assistant_messages enable row level security;
