-- =============================================================================
-- 28 · Productividad del asesor (docs/data-model.md §18.3)
--
-- Respuestas rápidas con adjuntos, categoría, grupos y variables; centro de notificaciones del panel;
-- campañas desde la lista de clientes (selección, asignación y bot); sub-estados de la conversación (derivados de
-- 27/26: nueva, recurrente, reasignada) y la secuencia de seguimiento disparada por tipificación (flujos: bloque
-- "Cuando se tipifica", sin tabla nueva).
-- =============================================================================

alter table public.quick_replies
  add column title          text,
  add column category       text,
  add column resource_ids   bigint[] not null default '{}',   -- adjuntos (Gestor de recursos)
  add column group_ids      bigint[] not null default '{}',   -- vacío = todos los grupos
  add column is_active      boolean not null default true,
  add column usage_count    int not null default 0,
  add column created_by     bigint references public.agents(id) on delete set null,
  add column updated_at     timestamptz not null default now();
-- {{agent_name}}, {{client_name}}, {{client_first_name}}, {{group_name}}, {{company_name}} se resuelven al enviar

-- Centro de notificaciones (campana del panel) ----------------------------------------------------------------
create table public.notifications (
  id               bigint generated by default as identity,
  organization_id  bigint not null,
  agent_id         bigint not null,
  type             text not null check (type in ('assigned', 'message', 'mention', 'followup_due', 'callback_due',
                                                  'sla_breach', 'transfer', 'call', 'system', 'qa_review', 'stage')),
  title            text not null,
  body             text,
  link             text,                          -- ruta del panel (/conversaciones?c=123)
  data             jsonb not null default '{}'::jsonb,
  read_at          timestamptz,
  created_at       timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);
create table public.notifications_default partition of public.notifications default;
select public.ensure_monthly_partitions('public.notifications', 3);
create index notifications_agent_idx on public.notifications (agent_id, created_at desc);
create index notifications_unread_idx on public.notifications (agent_id) where read_at is null;

alter table public.agents
  add column notification_prefs jsonb not null default
    '{"sound": true, "desktop": true, "types": {"assigned": true, "message": true, "followup_due": true, "sla_breach": true, "transfer": true, "call": true}}'::jsonb;

-- Seguimientos: recordatorio cuando vencen (para no avisar dos veces)
alter table public.followups
  add column kind          text not null default 'followup' check (kind in ('followup', 'callback')),
  add column reminded_at   timestamptz;
create index followups_due_idx on public.followups (due_at) where done_at is null and reminded_at is null;

-- Campañas desde la lista de clientes ------------------------------------------------------------------------
-- audience admite {"contact_ids": [...]} (selección); options: {assign_agent_id, assign_group_id,
-- bot: "on"|"off", conversation: "continue"|"new", tags: [...]}
alter table public.campaigns
  add column source   text not null default 'campaigns' check (source in ('campaigns', 'client_list', 'api', 'webhook')),
  add column options  jsonb not null default '{}'::jsonb;

do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('notifications-partitions', '35 3 * * *', $c$
      select public.ensure_monthly_partitions('public.notifications', 3);
      select public.drop_old_partitions('public.notifications', 6);
    $c$);
  end if;
end $$;

alter table public.notifications enable row level security;
do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'auth') then
    -- cada asesor lee solo sus notificaciones (Realtime/REST directo)
    execute 'create policy own_read on public.notifications for select to authenticated
             using (organization_id = private.current_org_id() and agent_id in
                    (select id from public.agents where auth_user_id = auth.uid()))';
  end if;
end $$;
