-- =============================================================================
-- 06 · Automatizaciones simples y flujos (bloques estilo Scratch, ejecuciones estilo n8n)
-- =============================================================================

create table public.automations (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  name             text not null,
  type             text not null check (type in ('welcome', 'keyword_reply', 'keyword_handoff', 'business_hours', 'inactivity_close')),
  config           jsonb not null default '{}'::jsonb,
  enabled          boolean not null default true,
  priority         int not null default 100,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index automations_org_idx on public.automations (organization_id, type) where enabled;
create trigger trg_automations_updated before update on public.automations
  for each row execute function public.set_updated_at();

create table public.flows (
  id                  bigint generated by default as identity primary key,
  organization_id     bigint not null references public.organizations(id) on delete cascade,
  name                text not null,
  description         text,
  trigger_type        text not null check (trigger_type in
                        ('inbound_message', 'keyword', 'handoff', 'close', 'schedule', 'webhook', 'manual', 'campaign_reply')),
  trigger_config      jsonb not null default '{}'::jsonb,
  status              text not null default 'draft' check (status in ('draft', 'active', 'paused', 'archived')),
  editor_mode         text not null default 'junior' check (editor_mode in ('junior', 'advanced')),
  current_version_id  bigint,                   -- FK abajo
  priority            int not null default 100,
  created_by          bigint references public.agents(id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (organization_id, name)
);
create index flows_active_idx on public.flows (organization_id, trigger_type, priority) where status = 'active';
create trigger trg_flows_updated before update on public.flows
  for each row execute function public.set_updated_at();

-- Definición versionada en JSON (inmutable): la UI de bloques la edita, la IA puede proponer versiones nuevas
create table public.flow_versions (
  id              bigint generated by default as identity primary key,
  flow_id         bigint not null references public.flows(id) on delete cascade,
  version         int not null,
  definition      jsonb not null,               -- {schema_version, variables, scripts:[{trigger, blocks:[...]}]}
  schema_version  int not null default 1,
  change_note     text,
  created_by_ai   boolean not null default false,
  ai_prompt       text,
  ai_call_id      bigint,
  created_by      bigint references public.agents(id) on delete set null,
  created_at      timestamptz not null default now(),
  unique (flow_id, version)
);
alter table public.flows add constraint flows_current_version_fk
  foreign key (current_version_id) references public.flow_versions(id) on delete set null;

-- Ejecuciones (particionado): estado, variables y esperas
create table public.flow_runs (
  id               bigint generated by default as identity,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  flow_id          bigint not null references public.flows(id) on delete cascade,
  flow_version_id  bigint not null references public.flow_versions(id),
  conversation_id  bigint,
  contact_id       bigint,
  trigger_type     text not null,
  status           text not null default 'running' check (status in ('running', 'waiting', 'succeeded', 'failed', 'cancelled')),
  context          jsonb not null default '{}'::jsonb,   -- variables del flujo y puntero de ejecución
  error            text,
  resume_at        timestamptz,                 -- para bloques "esperar"
  started_at       timestamptz not null default now(),
  finished_at      timestamptz,
  primary key (id, started_at)
) partition by range (started_at);
create table public.flow_runs_default partition of public.flow_runs default;
select public.ensure_monthly_partitions('public.flow_runs', 3);
create index flow_runs_waiting_idx on public.flow_runs (resume_at) where status = 'waiting';
create index flow_runs_flow_idx on public.flow_runs (flow_id, started_at desc);
create index flow_runs_conv_idx on public.flow_runs (conversation_id) where conversation_id is not null;

create table public.flow_run_steps (
  id              bigint generated by default as identity,
  run_id          bigint not null,
  run_started_at  timestamptz not null,
  block_id        text not null,
  block_type      text not null,
  status          text not null check (status in ('ok', 'error', 'skipped', 'waiting')),
  input           jsonb,
  output          jsonb,
  error           text,
  latency_ms      int,
  created_at      timestamptz not null default now(),
  primary key (id, created_at),
  foreign key (run_id, run_started_at) references public.flow_runs (id, started_at) on delete cascade
) partition by range (created_at);
create table public.flow_run_steps_default partition of public.flow_run_steps default;
select public.ensure_monthly_partitions('public.flow_run_steps', 3);
create index flow_run_steps_run_idx on public.flow_run_steps (run_id, created_at);
