-- =============================================================================
-- 11 · Atribución y conversiones: tráfico web, Click to WA (Meta y Google), envío de conversiones
-- Ver docs/data-model.md §10.1
-- =============================================================================

create table public.tracking_sites (
  id                bigint generated by default as identity primary key,
  organization_id   bigint not null references public.organizations(id) on delete cascade,
  name              text not null,
  public_key        text not null unique default replace(gen_random_uuid()::text, '-', ''),  -- va en el script/GTM
  allowed_domains   text[] not null default '{}',     -- vacío = cualquiera (no recomendado)
  channel_id        bigint references public.channels(id) on delete set null,
  wa_prefill        text not null default 'Hola, quiero más información',  -- el código se agrega al final
  is_active         boolean not null default true,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (organization_id, name)
);
create trigger trg_tracking_sites_updated before update on public.tracking_sites
  for each row execute function public.set_updated_at();

create table public.web_sessions (
  id                       bigint generated by default as identity,
  organization_id          bigint not null references public.organizations(id) on delete cascade,
  site_id                  bigint not null references public.tracking_sites(id) on delete cascade,
  visitor_id               text not null,               -- cookie anónima de primera parte
  ref_code                 text not null,               -- código corto que viaja en el texto de wa.me
  landing_url              text,
  referrer                 text,
  utm_source               text,
  utm_medium               text,
  utm_campaign             text,
  utm_term                 text,
  utm_content              text,
  gclid                    text,
  gbraid                   text,
  wbraid                   text,
  fbclid                   text,
  fbc                      text,
  fbp                      text,
  ttclid                   text,
  msclkid                  text,
  ga_client_id             text,
  user_agent               text,
  ip_hash                  text,                        -- sha256(ip + sal): nunca la IP en claro
  country                  text,
  wa_click_at              timestamptz,
  matched_conversation_id  bigint,
  matched_at               timestamptz,
  last_seen_at             timestamptz not null default now(),
  created_at               timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);
create table public.web_sessions_default partition of public.web_sessions default;
select public.ensure_monthly_partitions('public.web_sessions', 3);
create unique index web_sessions_ref_idx on public.web_sessions (ref_code, created_at);
create index web_sessions_lookup_idx on public.web_sessions (ref_code);
create index web_sessions_site_idx on public.web_sessions (site_id, created_at);
create index web_sessions_visitor_idx on public.web_sessions (organization_id, visitor_id, created_at desc);

create table public.web_events (
  id               bigint generated by default as identity,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  session_id       bigint not null,
  type             text not null check (type in ('page_view', 'wa_click', 'custom')),
  name             text,
  url              text,
  created_at       timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);
create table public.web_events_default partition of public.web_events default;
select public.ensure_monthly_partitions('public.web_events', 3);
create index web_events_org_idx on public.web_events (organization_id, type, created_at);
create index web_events_session_idx on public.web_events (session_id);

-- Una atribución por conversación (último toque)
create table public.attributions (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  conversation_id  bigint not null unique references public.conversations(id) on delete cascade,
  contact_id       bigint not null references public.contacts(id) on delete cascade,
  channel          text not null check (channel in
                     ('meta_ctwa', 'google_ads', 'meta_ads_web', 'paid_other', 'organic_web', 'campaign', 'direct')),
  matched_by       text not null check (matched_by in ('ctwa_referral', 'ref_code', 'campaign', 'none')),
  web_session_id   bigint,
  web_session_at   timestamptz,
  utm_source       text,
  utm_medium       text,
  utm_campaign     text,
  utm_content      text,
  utm_term         text,
  gclid            text,
  gbraid           text,
  wbraid           text,
  fbc              text,
  fbp              text,
  ctwa_clid        text,
  ad_id            text,
  landing_url      text,
  created_at       timestamptz not null default now()
);
create index attributions_org_channel_idx on public.attributions (organization_id, channel, created_at);
create index attributions_campaign_idx on public.attributions (organization_id, utm_campaign) where utm_campaign is not null;

-- ---------------------------------------------------------------------------
-- Conversiones hacia Google Ads (offline / enhanced) y Meta CAPI (business messaging)
-- ---------------------------------------------------------------------------
create table public.conversion_actions (
  id                   bigint generated by default as identity primary key,
  organization_id      bigint not null references public.organizations(id) on delete cascade,
  name                 text not null,
  trigger              text not null check (trigger in ('typification', 'stage_client', 'appointment_booked', 'deal_won')),
  typification_id      bigint references public.typifications(id) on delete cascade,
  value                numeric(14, 2),           -- valor fijo; null = valor del negocio (deal) si existe
  currency             char(3) not null default 'COP',
  google_ads           jsonb,                    -- {"customer_id","conversion_action_id"}
  meta                 jsonb,                    -- {"dataset_id","event_name":"Purchase|Lead|..."}
  is_active            boolean not null default true,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  unique (organization_id, name),
  check (trigger <> 'typification' or typification_id is not null)
);
create trigger trg_conversion_actions_updated before update on public.conversion_actions
  for each row execute function public.set_updated_at();

create table public.conversion_events (
  id                bigint generated by default as identity primary key,
  organization_id   bigint not null references public.organizations(id) on delete cascade,
  action_id         bigint not null references public.conversion_actions(id) on delete cascade,
  conversation_id   bigint references public.conversations(id) on delete set null,
  contact_id        bigint not null references public.contacts(id) on delete cascade,
  value             numeric(14, 2),
  currency          char(3) not null,
  occurred_at       timestamptz not null default now(),
  attribution       jsonb not null default '{}'::jsonb,   -- copia: gclid, ctwa_clid, fbc, utm...
  hashed_phone      text,                                 -- sha256 E.164 sin '+'
  hashed_email      text,
  dedupe_key        text not null,                        -- evita contar dos veces la misma conversión
  created_at        timestamptz not null default now(),
  unique (organization_id, dedupe_key)
);
create index conversion_events_org_idx on public.conversion_events (organization_id, occurred_at);

create table public.conversion_uploads (
  id               bigint generated by default as identity primary key,
  event_id         bigint not null references public.conversion_events(id) on delete cascade,
  destination      text not null check (destination in ('google_ads', 'meta_capi')),
  status           text not null default 'pending' check (status in ('pending', 'sent', 'failed', 'skipped')),
  attempts         int not null default 0,
  next_attempt_at  timestamptz not null default now(),
  response         jsonb,
  error            text,
  sent_at          timestamptz,
  created_at       timestamptz not null default now(),
  unique (event_id, destination)
);
create index conversion_uploads_due_idx on public.conversion_uploads (next_attempt_at) where status = 'pending';

-- Nuevas capas/orígenes en tablas existentes
alter table public.alerts drop constraint if exists alerts_layer_check;
alter table public.alerts add constraint alerts_layer_check check (layer in
  ('contact', 'template', 'account', 'phone', 'campaign', 'webhook', 'ai', 'catalog', 'conversion', 'integration',
   'voice', 'billing'));
