-- =============================================================================
-- 19 · Calidad de IA y coaching (docs/data-model.md §12.3)
--
-- qa_scorecards: rúbricas configurables (criterios con peso). conversation_reviews: evaluación de una
-- conversación cerrada por la IA (o por un supervisor) contra una rúbrica: puntaje por criterio, total,
-- sentimiento, resumen. coaching_items: sugerencias accionables por asesor. agent_test_*: pruebas de un
-- agente de IA (casos con conversación de entrada y expectativas) que corren antes de publicar cambios.
-- =============================================================================

create table public.qa_scorecards (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  name             text not null,
  applies_to       text not null default 'agent' check (applies_to in ('agent', 'bot', 'any')),
  -- [{key, label, description, weight (0-100), critical (bool)}]
  criteria         jsonb not null check (jsonb_typeof(criteria) = 'array'),
  auto_review      boolean not null default true,    -- evaluar automáticamente al cerrar
  sample_pct       int not null default 100 check (sample_pct between 0 and 100),
  min_messages     int not null default 3,
  group_ids        bigint[] not null default '{}',   -- vacío = todos los grupos
  is_active        boolean not null default true,
  created_by       bigint references public.agents(id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (organization_id, name)
);
create trigger trg_qa_scorecards_updated before update on public.qa_scorecards
  for each row execute function public.set_updated_at();

create table public.conversation_reviews (
  id                bigint generated by default as identity primary key,
  organization_id   bigint not null references public.organizations(id) on delete cascade,
  conversation_id   bigint not null references public.conversations(id) on delete cascade,
  scorecard_id      bigint references public.qa_scorecards(id) on delete set null,
  reviewer_type     text not null check (reviewer_type in ('ai', 'human')),
  reviewer_agent_id bigint references public.agents(id) on delete set null,
  subject_type      text not null check (subject_type in ('agent', 'bot')),
  agent_id          bigint references public.agents(id) on delete set null,      -- asesor evaluado
  ai_agent_id       bigint references public.ai_agents(id) on delete set null,   -- bot evaluado
  status            text not null default 'done' check (status in ('pending', 'done', 'failed', 'disputed')),
  scores            jsonb not null default '{}'::jsonb,   -- {criterio: {score 0-100, evidence, comment}}
  total_score       numeric(5, 2),                       -- ponderado 0-100
  critical_failed   boolean not null default false,
  sentiment         text check (sentiment in ('positive', 'neutral', 'negative', 'mixed')),
  sentiment_score   numeric(4, 3),                       -- -1..1
  customer_effort   smallint check (customer_effort between 1 and 5),
  summary           text,
  ai_call_id        bigint,
  error             text,
  dispute_note      text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create unique index conversation_reviews_ai_idx on public.conversation_reviews (conversation_id, scorecard_id)
  where reviewer_type = 'ai';
create index conversation_reviews_org_idx on public.conversation_reviews (organization_id, created_at desc);
create index conversation_reviews_agent_idx on public.conversation_reviews (organization_id, agent_id, created_at desc)
  where agent_id is not null;
create index conversation_reviews_pending_idx on public.conversation_reviews (created_at) where status = 'pending';
create trigger trg_conversation_reviews_updated before update on public.conversation_reviews
  for each row execute function public.set_updated_at();

-- El sentimiento de la conversación ya existe (conversations.ai_sentiment); la revisión lo actualiza.
alter table public.conversations add column qa_score numeric(5, 2);

create table public.coaching_items (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  agent_id         bigint not null references public.agents(id) on delete cascade,
  review_id        bigint references public.conversation_reviews(id) on delete set null,
  criterion_key    text,
  title            text not null,
  suggestion       text not null,
  example          text,                         -- frase de ejemplo de cómo hacerlo mejor
  status           text not null default 'open' check (status in ('open', 'acknowledged', 'done', 'dismissed')),
  created_at       timestamptz not null default now(),
  resolved_at      timestamptz
);
create index coaching_items_agent_idx on public.coaching_items (organization_id, agent_id, status, created_at desc);

-- Pruebas de agentes de IA ----------------------------------------------------------------------------
create table public.agent_test_suites (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  ai_agent_id      bigint not null references public.ai_agents(id) on delete cascade,
  name             text not null,
  description      text,
  run_on_change    boolean not null default true,   -- correr al guardar el agente
  min_pass_pct     int not null default 80 check (min_pass_pct between 0 and 100),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (ai_agent_id, name)
);
create trigger trg_agent_test_suites_updated before update on public.agent_test_suites
  for each row execute function public.set_updated_at();

create table public.agent_test_cases (
  id               bigint generated by default as identity primary key,
  suite_id         bigint not null references public.agent_test_suites(id) on delete cascade,
  name             text not null,
  turns            jsonb not null check (jsonb_typeof(turns) = 'array'),  -- [{role: user|assistant, text}]
  -- {must_include: [..], must_not_include: [..], expect_handoff: bool, expect_tool: str, rubric: str}
  expectations     jsonb not null default '{}'::jsonb,
  source_conversation_id bigint,                   -- caso creado desde una conversación real
  position         int not null default 0,
  created_at       timestamptz not null default now()
);
create index agent_test_cases_suite_idx on public.agent_test_cases (suite_id, position);

create table public.agent_test_runs (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  suite_id         bigint not null references public.agent_test_suites(id) on delete cascade,
  ai_agent_id      bigint not null,
  config_revision_id bigint,                       -- config_revisions del agente probado
  trigger          text not null default 'manual' check (trigger in ('manual', 'on_change', 'schedule')),
  status           text not null default 'running' check (status in ('running', 'passed', 'failed', 'error')),
  total            int not null default 0,
  passed           int not null default 0,
  pass_pct         numeric(5, 2),
  cost_usd         numeric(12, 6) not null default 0,
  started_by       bigint references public.agents(id) on delete set null,
  started_at       timestamptz not null default now(),
  finished_at      timestamptz
);
create index agent_test_runs_suite_idx on public.agent_test_runs (suite_id, started_at desc);

create table public.agent_test_results (
  id               bigint generated by default as identity primary key,
  run_id           bigint not null references public.agent_test_runs(id) on delete cascade,
  case_id          bigint references public.agent_test_cases(id) on delete set null,
  passed           boolean not null,
  reply            text,
  checks           jsonb not null default '[]'::jsonb,   -- [{check, passed, detail}]
  judge_score      numeric(5, 2),                       -- rúbrica evaluada por un LLM juez
  latency_ms       int,
  ai_call_ids      bigint[] not null default '{}',
  created_at       timestamptz not null default now()
);
create index agent_test_results_run_idx on public.agent_test_results (run_id);

-- Reporting -----------------------------------------------------------------------------------------
create table reporting.daily_qa (
  organization_id  bigint not null,
  day              date not null,
  subject_type     text not null,
  agent_id         bigint not null,        -- 0 = bot
  reviews          int not null default 0,
  score_sum        numeric(12, 2) not null default 0,
  critical_failed  int not null default 0,
  positive         int not null default 0,
  neutral          int not null default 0,
  negative         int not null default 0,
  refreshed_at     timestamptz not null default now(),
  primary key (organization_id, day, subject_type, agent_id)
);

create or replace function reporting.refresh_qa(p_org bigint, p_from date, p_to date) returns void
language plpgsql set search_path = reporting, public, pg_temp as $$
declare
  tz  text := (select timezone from public.organizations where id = p_org);
  lo  timestamptz := (p_from::timestamp at time zone tz);
  hi  timestamptz := ((p_to + 1)::timestamp at time zone tz);
begin
  delete from reporting.daily_qa where organization_id = p_org and day between p_from and p_to;
  insert into reporting.daily_qa (organization_id, day, subject_type, agent_id, reviews, score_sum, critical_failed,
      positive, neutral, negative)
  select p_org, (r.created_at at time zone tz)::date, r.subject_type, coalesce(r.agent_id, 0), count(*),
         coalesce(sum(r.total_score), 0), count(*) filter (where r.critical_failed),
         count(*) filter (where r.sentiment = 'positive'), count(*) filter (where r.sentiment in ('neutral', 'mixed')),
         count(*) filter (where r.sentiment = 'negative')
  from public.conversation_reviews r
  where r.organization_id = p_org and r.status = 'done' and r.created_at >= lo and r.created_at < hi
  group by 2, 3, 4;
end $$;
revoke all on function reporting.refresh_qa(bigint, date, date) from public;

-- RLS
alter table public.qa_scorecards enable row level security;
alter table public.conversation_reviews enable row level security;
alter table public.coaching_items enable row level security;
alter table public.agent_test_suites enable row level security;
alter table public.agent_test_cases enable row level security;
alter table public.agent_test_runs enable row level security;
alter table public.agent_test_results enable row level security;
do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'auth') then
    execute 'create policy org_read on public.qa_scorecards for select to authenticated
             using (organization_id = private.current_org_id())';
    execute 'create policy org_read on public.conversation_reviews for select to authenticated
             using (organization_id = private.current_org_id())';
    execute 'create policy org_read on public.coaching_items for select to authenticated
             using (organization_id = private.current_org_id())';
  end if;
end $$;

update public.plans set features = features || '{"qa": false}'::jsonb where key = 'team';
update public.plans set features = features || '{"qa": true}'::jsonb where key in ('professional', 'enterprise');
