-- =============================================================================
-- 21 · Asistente de onboarding y configuración automática (docs/data-model.md §13)
--
-- onboarding_runs / onboarding_steps: el asistente por empresa (paso actual, respuestas, estado de cada paso con
--   su resultado y reintentos). Cada paso es idempotente: se puede volver a correr ("auto-arreglar").
-- channel_health_checks: validaciones del número (registro, verificación del nombre, calidad, límite de
--   mensajes, suscripción del webhook, PIN de 2 pasos, perfil, prueba de ida y vuelta) — el último resultado por
--   chequeo; el asistente las usa y luego siguen corriendo para el Centro de Control.
-- channels: estado de Meta del número. wa_templates: origen, paquete, motivo de rechazo.
-- agent_invitations: invitaciones de usuarios por correo (rol, grupos) con token de un solo uso.
-- =============================================================================

create table public.onboarding_runs (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  status           text not null default 'in_progress' check (status in ('in_progress', 'completed', 'abandoned')),
  current_step     text not null default 'company',
  industry         text,                         -- automotriz, salud, educacion, retail, servicios, inmobiliaria, otro
  -- Respuestas del asistente: perfil de la empresa, horarios, tono, objetivos, fuente web importada, etc.
  answers          jsonb not null default '{}'::jsonb,
  channel_id       bigint references public.channels(id) on delete set null,   -- número conectado en el asistente
  started_by       bigint references public.agents(id) on delete set null,
  started_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  completed_at     timestamptz
);
create unique index onboarding_runs_active_idx on public.onboarding_runs (organization_id) where status = 'in_progress';
create trigger trg_onboarding_runs_updated before update on public.onboarding_runs
  for each row execute function public.set_updated_at();

create table public.onboarding_steps (
  id           bigint generated by default as identity primary key,
  run_id       bigint not null references public.onboarding_runs(id) on delete cascade,
  key          text not null,                    -- company, whatsapp, validate, profile, templates, ai, team, test, go_live
  status       text not null default 'pending' check (status in
                 ('pending', 'running', 'done', 'warning', 'failed', 'skipped')),
  attempts     int not null default 0,
  result       jsonb not null default '{}'::jsonb,   -- lo que hizo: ids creados, chequeos, plantillas enviadas
  error        text,
  started_at   timestamptz,
  finished_at  timestamptz,
  unique (run_id, key)
);

-- Estado de Meta del número ---------------------------------------------------------------------------
alter table public.channels
  add column verified_name            text,
  add column name_status              text,     -- APPROVED | PENDING_REVIEW | DECLINED | NONE ...
  add column code_verification_status text,     -- VERIFIED | NOT_VERIFIED | EXPIRED
  add column quality_rating           text,     -- GREEN | YELLOW | RED | UNKNOWN
  add column messaging_limit_tier     text,     -- TIER_250 | TIER_1K | TIER_10K | TIER_100K | TIER_UNLIMITED
  add column throughput_level         text,     -- STANDARD | HIGH
  add column platform_type            text,     -- CLOUD_API | ON_PREMISE | NOT_APPLICABLE
  add column is_coexistence           boolean not null default false,  -- número compartido con la app WhatsApp Business
  add column pin_set_at               timestamptz,
  add column registered_at            timestamptz,
  add column webhook_subscribed_at    timestamptz,
  add column last_inbound_at          timestamptz,
  add column business_profile         jsonb not null default '{}'::jsonb,  -- about, description, address, email, websites, vertical
  add column meta_synced_at           timestamptz;

create table public.channel_health_checks (
  channel_id       bigint not null references public.channels(id) on delete cascade,
  check_key        text not null,                 -- registered, name_approved, quality, limit_tier, webhook, pin, profile,
                                                  -- templates_ready, inbound_roundtrip, outbound_test, token_valid
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  status           text not null check (status in ('pass', 'warn', 'fail', 'pending', 'skipped')),
  detail           text,
  data             jsonb not null default '{}'::jsonb,
  fixable          boolean not null default false,   -- el sistema puede corregirlo con "Arreglar"
  checked_at       timestamptz not null default now(),
  primary key (channel_id, check_key)
);
create index channel_health_checks_org_idx on public.channel_health_checks (organization_id, status);

-- Plantillas: origen y paquete ---------------------------------------------------------------------------
alter table public.wa_templates
  add column source           text not null default 'meta_sync' check (source in ('meta_sync', 'panel', 'onboarding', 'ai')),
  add column pack_key         text,              -- paquete del asistente (ej. "automotriz.basico")
  add column template_key     text,              -- clave estable dentro del paquete (welcome, followup, ...)
  add column meta_template_id text,
  add column rejected_reason  text,
  add column submitted_by     bigint references public.agents(id) on delete set null,
  add column submitted_at     timestamptz;
create index wa_templates_pack_idx on public.wa_templates (organization_id, pack_key) where pack_key is not null;

-- Invitaciones de usuarios -------------------------------------------------------------------------------
create table public.agent_invitations (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  email            extensions.citext not null,
  name             text,
  role             text not null default 'agent' check (role in ('admin', 'supervisor', 'agent')),
  group_ids        bigint[] not null default '{}',
  token_hash       text not null unique,          -- sha256 del token del enlace
  expires_at       timestamptz not null,
  accepted_at      timestamptz,
  accepted_agent_id bigint references public.agents(id) on delete set null,
  revoked_at       timestamptz,
  invited_by       bigint references public.agents(id) on delete set null,
  email_sent_at    timestamptz,
  created_at       timestamptz not null default now()
);
create unique index agent_invitations_pending_idx on public.agent_invitations (organization_id, email)
  where accepted_at is null and revoked_at is null;

alter table public.organizations
  add column industry                 text,
  add column onboarding_completed_at  timestamptz;
-- Empresas existentes ya operan: no se les muestra el asistente
update public.organizations set onboarding_completed_at = now() where onboarding_completed_at is null;

-- RLS
alter table public.onboarding_runs enable row level security;
alter table public.onboarding_steps enable row level security;
alter table public.channel_health_checks enable row level security;
alter table public.agent_invitations enable row level security;
do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'auth') then
    execute 'create policy org_read on public.onboarding_runs for select to authenticated
             using (organization_id = private.current_org_id())';
    execute 'create policy org_read on public.channel_health_checks for select to authenticated
             using (organization_id = private.current_org_id())';
  end if;
end $$;
