-- =============================================================================
-- 01 · Núcleo: extensiones, utilidades, organizaciones, agentes, grupos, ajustes
-- Ver docs/data-model.md
-- =============================================================================

create extension if not exists pgcrypto;
create extension if not exists pg_trgm;
create extension if not exists citext;

create schema if not exists reporting;

-- ---------------------------------------------------------------------------
-- Utilidades
-- ---------------------------------------------------------------------------

-- Mantiene updated_at en cada UPDATE.
create or replace function public.set_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end $$;

-- Crea particiones mensuales [mes, mes+1) para una tabla particionada por rango de fecha,
-- desde el mes de p_from hasta p_months_ahead meses adelante. Idempotente.
create or replace function public.ensure_monthly_partitions(
  p_parent regclass, p_months_ahead int default 3, p_from date default (date_trunc('month', now()) - interval '1 month')::date
) returns void
language plpgsql as $$
declare
  m date := date_trunc('month', p_from)::date;
  last date := (date_trunc('month', now()) + make_interval(months => p_months_ahead))::date;
  part text;
  parent_name text := (select relname from pg_class where oid = p_parent);
  parent_schema text := (select nspname from pg_class c join pg_namespace n on n.oid = c.relnamespace where c.oid = p_parent);
begin
  while m <= last loop
    part := format('%s_%s', parent_name, to_char(m, 'YYYYMM'));
    if to_regclass(format('%I.%I', parent_schema, part)) is null then
      execute format('create table %I.%I partition of %s for values from (%L) to (%L)',
                     parent_schema, part, p_parent, m, (m + interval '1 month')::date);
    end if;
    m := (m + interval '1 month')::date;
  end loop;
end $$;

-- Elimina particiones mensuales anteriores a p_keep_months (retención de logs).
create or replace function public.drop_old_partitions(p_parent regclass, p_keep_months int) returns int
language plpgsql as $$
declare
  r record;
  cutoff text := to_char(date_trunc('month', now()) - make_interval(months => p_keep_months), 'YYYYMM');
  dropped int := 0;
begin
  for r in
    select c.oid::regclass as part, c.relname
    from pg_inherits i join pg_class c on c.oid = i.inhrelid
    where i.inhparent = p_parent and c.relname ~ '_[0-9]{6}$'
  loop
    if right(r.relname, 6) < cutoff then
      execute format('drop table %s', r.part);
      dropped := dropped + 1;
    end if;
  end loop;
  return dropped;
end $$;

-- ---------------------------------------------------------------------------
-- Organizaciones (tenant) y agentes
-- ---------------------------------------------------------------------------
create table public.organizations (
  id          bigint generated by default as identity primary key,
  name        text not null,
  slug        citext not null unique,
  timezone    text not null default 'America/Bogota',
  plan        text not null default 'internal',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);
create trigger trg_organizations_updated before update on public.organizations
  for each row execute function public.set_updated_at();

create table public.agents (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  auth_user_id     uuid unique,                 -- auth.users(id) en Supabase
  email            citext not null,
  name             text not null,
  password_hash    text,                        -- null cuando se usa Supabase Auth
  role             text not null default 'agent' check (role in ('admin', 'supervisor', 'agent')),
  availability     text not null default 'available' check (availability in ('available', 'away', 'busy')),
  is_active        boolean not null default true,
  last_seen_at     timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (organization_id, email)
);
create index agents_org_active_idx on public.agents (organization_id) where is_active;
create trigger trg_agents_updated before update on public.agents
  for each row execute function public.set_updated_at();

create table public.groups (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  name             text not null,
  description      text,                        -- también es el criterio de enrutamiento de la IA
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (organization_id, name)
);
create trigger trg_groups_updated before update on public.groups
  for each row execute function public.set_updated_at();

create table public.agent_groups (
  agent_id  bigint not null references public.agents(id) on delete cascade,
  group_id  bigint not null references public.groups(id) on delete cascade,
  primary key (agent_id, group_id)
);
create index agent_groups_group_idx on public.agent_groups (group_id);

-- ---------------------------------------------------------------------------
-- Ajustes por módulo y revisiones de documentos JSON (editables por personas o IA)
-- ---------------------------------------------------------------------------
create table public.org_settings (
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  key              text not null,
  value            jsonb not null default '{}'::jsonb,
  updated_by       bigint references public.agents(id) on delete set null,
  updated_at       timestamptz not null default now(),
  primary key (organization_id, key)
);
create trigger trg_org_settings_updated before update on public.org_settings
  for each row execute function public.set_updated_at();

create table public.config_revisions (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  entity_type      text not null check (entity_type in
                     ('setting', 'ai_agent', 'cortex', 'automation', 'flow', 'classifier', 'seller_profile')),
  entity_id        text not null,              -- id numérico o clave del ajuste
  revision         int not null,
  document         jsonb not null,
  source           text not null check (source in ('human', 'ai', 'import', 'system')),
  ai_prompt        text,                       -- instrucción en lenguaje natural cuando la editó la IA
  ai_call_id       bigint,                     -- ai_calls.id (sin FK: tabla particionada)
  created_by       bigint references public.agents(id) on delete set null,
  created_at       timestamptz not null default now(),
  unique (organization_id, entity_type, entity_id, revision)
);
