-- =============================================================================
-- 20 · API pública, conectores y app del asesor (docs/data-model.md §12.4)
--
-- api_keys: llaves por empresa (solo se guarda el sha256; el prefijo visible identifica la llave), con
-- alcances. api_requests (particionada, 30 días): registro de cada llamada para auditoría y límites.
-- outbound_webhooks gana origen (panel | api | zapier | make | n8n) para las suscripciones REST Hooks.
-- push_subscriptions: Web Push (VAPID) de la app instalable del asesor.
-- =============================================================================

create table public.api_keys (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  name             text not null,
  prefix           text not null unique,          -- "wak_live_ab12cd" (visible)
  key_hash         text not null unique,          -- sha256 de la llave completa
  scopes           text[] not null default '{}',  -- contacts:read, contacts:write, messages:send, ...
  rate_limit_per_min int not null default 120,
  last_used_at     timestamptz,
  last_used_ip     text,
  expires_at       timestamptz,
  revoked_at       timestamptz,
  created_by       bigint references public.agents(id) on delete set null,
  created_at       timestamptz not null default now()
);
create index api_keys_org_idx on public.api_keys (organization_id) where revoked_at is null;

create table public.api_requests (
  id               bigint generated by default as identity,
  organization_id  bigint not null,
  api_key_id       bigint,
  method           text not null,
  path             text not null,                 -- ruta plantilla (/v1/contacts/{id}), sin ids
  status           smallint not null,
  latency_ms       int,
  ip               text,
  error_code       text,
  created_at       timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);
create table public.api_requests_default partition of public.api_requests default;
select public.ensure_monthly_partitions('public.api_requests', 3);
create index api_requests_org_idx on public.api_requests (organization_id, created_at);
create index api_requests_key_idx on public.api_requests (api_key_id, created_at);

-- Suscripciones de conectores (REST Hooks de Zapier/Make/n8n) sobre los webhooks salientes existentes
alter table public.outbound_webhooks
  add column source      text not null default 'panel' check (source in ('panel', 'api', 'zapier', 'make', 'n8n')),
  add column api_key_id  bigint references public.api_keys(id) on delete cascade;

-- Idempotencia de la API (Idempotency-Key en POST): 24 h
create table public.api_idempotency (
  organization_id  bigint not null,
  key              text not null,
  request_hash     text not null,
  status           smallint,
  response         jsonb,
  created_at       timestamptz not null default now(),
  primary key (organization_id, key)
);
create index api_idempotency_created_idx on public.api_idempotency (created_at);

-- App del asesor (PWA): suscripciones Web Push
create table public.push_subscriptions (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  agent_id         bigint not null references public.agents(id) on delete cascade,
  endpoint         text not null unique,
  p256dh           text not null,
  auth             text not null,
  user_agent       text,
  -- qué avisar: {new_conversation, assigned, message_assigned, mention, call}
  preferences      jsonb not null default '{"assigned": true, "message_assigned": true, "call": true}'::jsonb,
  failures         int not null default 0,
  last_success_at  timestamptz,
  created_at       timestamptz not null default now()
);
create index push_subscriptions_agent_idx on public.push_subscriptions (agent_id);

-- Reporting
create table reporting.daily_api (
  organization_id  bigint not null,
  day              date not null,
  api_key_id       bigint not null,
  requests         int not null default 0,
  errors           int not null default 0,     -- status >= 400
  throttled        int not null default 0,     -- 429
  latency_p95_ms   int,
  refreshed_at     timestamptz not null default now(),
  primary key (organization_id, day, api_key_id)
);

create or replace function reporting.refresh_api(p_org bigint, p_from date, p_to date) returns void
language plpgsql set search_path = reporting, public, pg_temp as $$
declare
  tz  text := (select timezone from public.organizations where id = p_org);
  lo  timestamptz := (p_from::timestamp at time zone tz);
  hi  timestamptz := ((p_to + 1)::timestamp at time zone tz);
begin
  delete from reporting.daily_api where organization_id = p_org and day between p_from and p_to;
  insert into reporting.daily_api (organization_id, day, api_key_id, requests, errors, throttled, latency_p95_ms)
  select p_org, (r.created_at at time zone tz)::date, coalesce(r.api_key_id, 0), count(*),
         count(*) filter (where r.status >= 400), count(*) filter (where r.status = 429),
         percentile_cont(0.95) within group (order by r.latency_ms)::int
  from public.api_requests r
  where r.organization_id = p_org and r.created_at >= lo and r.created_at < hi
  group by 2, 3;
end $$;
revoke all on function reporting.refresh_api(bigint, date, date) from public;

-- refresh_range incluye todos los rollups de la fase
create or replace function reporting.refresh_range(p_org bigint, p_from date, p_to date) returns void
language plpgsql set search_path = reporting, public, pg_temp as $$
begin
  perform reporting.refresh_core(p_org, p_from, p_to);
  perform reporting.refresh_flows(p_org, p_from, p_to);
  perform reporting.refresh_links(p_org, p_from, p_to);
  perform reporting.refresh_channels(p_org, p_from, p_to);
  perform reporting.refresh_qa(p_org, p_from, p_to);
  perform reporting.refresh_api(p_org, p_from, p_to);
end $$;

-- RLS: llaves y suscripciones solo por el backend
alter table public.api_keys enable row level security;
alter table public.api_requests enable row level security;
alter table public.api_idempotency enable row level security;
alter table public.push_subscriptions enable row level security;

do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('api-housekeeping', '20 3 * * *', $c$
      select public.ensure_monthly_partitions('public.api_requests', 3);
      select public.drop_old_partitions('public.api_requests', 1);
      delete from public.api_idempotency where created_at < now() - interval '24 hours';
    $c$);
  end if;
end $$;
