-- =============================================================================
-- 16 · Mensajes disparadores (enlaces de WhatsApp con tracking) y atribución multi-toque
-- docs/data-model.md §10.5
--
-- wa_links: un "mensaje disparador" = texto prellenado de WhatsApp + UTMs + plataforma + anuncios que lo usan +
--   acciones al llegar (etiquetas, grupo, flujo). Se publica como enlace corto /t/l/{slug} (captura gclid/fbclid/
--   UTMs, crea la visita y agrega el código de referencia) o como wa.me directo (anuncios Click to WhatsApp).
-- attribution_touches (particionada): cada toque (primero y siguientes) → primer toque vs último toque.
-- ad_entities: caché de nombres de campañas/conjuntos/anuncios de Meta y Google Ads.
-- =============================================================================

create table public.wa_links (
  id                  bigint generated by default as identity primary key,
  organization_id     bigint not null references public.organizations(id) on delete cascade,
  channel_id          bigint references public.channels(id) on delete set null,   -- número de destino (null = principal)
  name                text not null,
  slug                text not null unique,                 -- /t/l/{slug} (global: la URL no lleva la empresa)
  platform            text not null default 'web' check (platform in
                        ('meta_ads', 'google_ads', 'web', 'social', 'email', 'qr', 'sms', 'other')),
  trigger_text        text not null,                        -- texto prellenado que envía el cliente
  trigger_key         text not null,                        -- trigger_text normalizado (minúsculas, sin tildes ni signos)
  append_ref          boolean not null default true,        -- agrega "(ref: CODE)" al texto en el enlace corto
  utm_source          text,
  utm_medium          text,
  utm_campaign        text,
  utm_content         text,
  utm_term            text,
  meta_ad_ids         text[] not null default '{}',         -- anuncios CTWA cuyo mensaje es este disparador
  google_campaign_ids text[] not null default '{}',
  tags                text[] not null default '{}',         -- etiquetas a aplicar al llegar
  group_id            bigint references public.groups(id) on delete set null,
  flow_id             bigint references public.flows(id) on delete set null, -- flujo con disparador "wa_link"
  is_active           boolean not null default true,
  created_by          bigint references public.agents(id) on delete set null,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  check (trigger_key <> '')
);
-- Un texto activo identifica un solo enlace (si no, la atribución por texto sería ambigua)
create unique index wa_links_trigger_idx on public.wa_links (organization_id, trigger_key) where is_active;
create index wa_links_org_idx on public.wa_links (organization_id, is_active);
create index wa_links_meta_ads_idx on public.wa_links using gin (meta_ad_ids);
create trigger trg_wa_links_updated before update on public.wa_links
  for each row execute function public.set_updated_at();

-- Visitas creadas por un enlace corto (sin script en un sitio)
alter table public.web_sessions alter column site_id drop not null;
alter table public.web_sessions add column link_id bigint;
create index web_sessions_link_idx on public.web_sessions (link_id, created_at) where link_id is not null;

-- Atribución: enlace, nombres de campaña enriquecidos y conteo de toques ---------------------------
alter table public.attributions drop constraint attributions_channel_check;
alter table public.attributions add constraint attributions_channel_check check (channel in
  ('meta_ctwa', 'google_ads', 'meta_ads_web', 'paid_other', 'organic_web', 'offline', 'campaign', 'direct'));
alter table public.attributions drop constraint attributions_matched_by_check;
alter table public.attributions add constraint attributions_matched_by_check check (matched_by in
  ('ctwa_referral', 'ref_code', 'trigger_text', 'campaign', 'none'));
alter table public.attributions
  add column link_id           bigint references public.wa_links(id) on delete set null,
  add column platform_campaign_id   text,
  add column platform_campaign_name text,
  add column ad_group_id       text,        -- conjunto de anuncios (Meta) / grupo de anuncios (Google)
  add column ad_group_name     text,
  add column ad_name           text,
  add column keyword           text,
  add column enrichment_status text not null default 'skipped'
    check (enrichment_status in ('pending', 'done', 'failed', 'skipped')),
  add column enriched_at       timestamptz,
  add column touches           int not null default 1,
  add column first_touch_id    bigint,      -- attribution_touches.id del primer toque
  add column last_touch_at     timestamptz;
create index attributions_link_idx on public.attributions (organization_id, link_id, created_at) where link_id is not null;
create index attributions_enrich_idx on public.attributions (created_at) where enrichment_status = 'pending';

create table public.attribution_touches (
  id               bigint generated by default as identity,
  organization_id  bigint not null,
  conversation_id  bigint not null,
  contact_id       bigint not null,
  message_id       bigint,
  channel          text not null,
  matched_by       text not null,
  link_id          bigint,
  web_session_id   bigint,
  utm_source       text,
  utm_medium       text,
  utm_campaign     text,
  gclid            text,
  ctwa_clid        text,
  ad_id            text,
  is_first         boolean not null default false,
  occurred_at      timestamptz not null default now(),
  primary key (id, occurred_at)
) partition by range (occurred_at);
create table public.attribution_touches_default partition of public.attribution_touches default;
select public.ensure_monthly_partitions('public.attribution_touches', 3);
create index attribution_touches_conv_idx on public.attribution_touches (conversation_id, occurred_at);
create index attribution_touches_org_idx on public.attribution_touches (organization_id, occurred_at);
create index attribution_touches_contact_idx on public.attribution_touches (organization_id, contact_id, occurred_at);

-- Caché de entidades publicitarias ---------------------------------------------------------------
create table public.ad_entities (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  platform         text not null check (platform in ('meta', 'google_ads')),
  entity_type      text not null check (entity_type in ('ad', 'ad_group', 'campaign', 'click')),
  external_id      text not null,             -- ad_id (Meta), gclid (Google, entity_type = click)
  name             text,
  campaign_id      text,
  campaign_name    text,
  ad_group_id      text,
  ad_group_name    text,
  keyword          text,
  data             jsonb not null default '{}'::jsonb,
  fetched_at       timestamptz not null default now(),
  unique (organization_id, platform, entity_type, external_id)
);

-- Rollup diario por enlace -----------------------------------------------------------------------
create table reporting.daily_links (
  organization_id  bigint not null,
  day              date not null,
  link_id          bigint not null,
  clicks           int not null default 0,     -- visitas creadas por el enlace corto
  conversations    int not null default 0,     -- conversaciones atribuidas (último toque)
  first_touches    int not null default 0,     -- conversaciones cuyo primer toque fue el enlace
  retouches        int not null default 0,     -- toques posteriores (cliente que vuelve por el enlace)
  conversions      int not null default 0,
  conversion_value numeric(16, 2) not null default 0,
  refreshed_at     timestamptz not null default now(),
  primary key (organization_id, day, link_id)
);

create or replace function reporting.refresh_links(p_org bigint, p_from date, p_to date) returns void
language plpgsql set search_path = reporting, public, pg_temp as $$
declare
  tz  text := (select timezone from public.organizations where id = p_org);
  lo  timestamptz := (p_from::timestamp at time zone tz);
  hi  timestamptz := ((p_to + 1)::timestamp at time zone tz);
begin
  delete from reporting.daily_links where organization_id = p_org and day between p_from and p_to;
  insert into reporting.daily_links as d (organization_id, day, link_id, clicks, conversations, first_touches,
      retouches, conversions, conversion_value)
  select p_org, x.day, x.link_id, sum(x.clicks), sum(x.conversations), sum(x.first_touches), sum(x.retouches),
         sum(x.conversions), sum(x.conversion_value)
  from (
    select (w.created_at at time zone tz)::date as day, w.link_id, count(*) as clicks, 0 as conversations,
           0 as first_touches, 0 as retouches, 0 as conversions, 0::numeric as conversion_value
    from public.web_sessions w
    where w.organization_id = p_org and w.link_id is not null and w.created_at >= lo and w.created_at < hi
    group by 1, 2
    union all
    select (a.created_at at time zone tz)::date, a.link_id, 0, count(*), 0, 0, 0, 0
    from public.attributions a
    where a.organization_id = p_org and a.link_id is not null and a.created_at >= lo and a.created_at < hi
    group by 1, 2
    union all
    select (t.occurred_at at time zone tz)::date, t.link_id, 0, 0,
           count(*) filter (where t.is_first), count(*) filter (where not t.is_first), 0, 0
    from public.attribution_touches t
    where t.organization_id = p_org and t.link_id is not null and t.occurred_at >= lo and t.occurred_at < hi
    group by 1, 2
    union all
    select (e.occurred_at at time zone tz)::date, (e.attribution->>'link_id')::bigint, 0, 0, 0, 0, count(*),
           coalesce(sum(e.value), 0)
    from public.conversion_events e
    where e.organization_id = p_org and e.attribution ? 'link_id' and e.attribution->>'link_id' is not null
      and e.occurred_at >= lo and e.occurred_at < hi
    group by 1, 2
  ) x
  group by 2, 3;
end $$;
revoke all on function reporting.refresh_links(bigint, date, date) from public;

create or replace function reporting.refresh_range(p_org bigint, p_from date, p_to date) returns void
language plpgsql set search_path = reporting, public, pg_temp as $$
begin
  perform reporting.refresh_core(p_org, p_from, p_to);
  perform reporting.refresh_flows(p_org, p_from, p_to);
  perform reporting.refresh_links(p_org, p_from, p_to);
end $$;

-- Retención: toques como el resto de hechos particionados (24 meses) ---------------------------
do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('attribution-touches-partitions', '15 3 * * *',
      $c$select public.ensure_monthly_partitions('public.attribution_touches', 3);
         select public.drop_old_partitions('public.attribution_touches', 24)$c$);
  end if;
end $$;

-- RLS ------------------------------------------------------------------------------------------
alter table public.wa_links enable row level security;
alter table public.attribution_touches enable row level security;
alter table public.ad_entities enable row level security;
do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'auth') then
    execute 'create policy org_read on public.wa_links for select to authenticated
             using (organization_id = private.current_org_id())';
    execute 'create policy org_read on public.attribution_touches for select to authenticated
             using (organization_id = private.current_org_id())';
    execute 'create policy org_read on public.ad_entities for select to authenticated
             using (organization_id = private.current_org_id())';
  end if;
end $$;
