-- =============================================================================
-- 13 · Voz: WhatsApp Business Calling API + agentes de voz con IA
-- Ver docs/data-model.md §10.3
-- =============================================================================

alter table public.channels
  add column calling_enabled boolean not null default false,
  add column calling_hours jsonb;           -- {"days":[0..6],"start":"08:00","end":"18:00"}; null = siempre

create table public.voice_agents (
  id                  bigint generated by default as identity primary key,
  organization_id     bigint not null references public.organizations(id) on delete cascade,
  name                text not null,
  enabled             boolean not null default true,
  ai_agent_id         bigint references public.ai_agents(id) on delete set null,  -- prompt, conocimiento, memoria
  provider            text not null default 'openai_realtime' check (provider in ('openai_realtime', 'pipeline')),
  model               text not null default 'gpt-realtime',
  voice               text not null default 'alloy',
  language            text not null default 'es',
  greeting            text not null default 'Hola, gracias por llamar. ¿En qué te puedo ayudar?',
  max_duration_s      int not null default 600 check (max_duration_s between 30 and 3600),
  transfer_group_id   bigint references public.groups(id) on delete set null,
  record_calls        boolean not null default true,
  settings            jsonb not null default '{}'::jsonb,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  unique (organization_id, name)
);
create trigger trg_voice_agents_updated before update on public.voice_agents
  for each row execute function public.set_updated_at();

alter table public.channels add column voice_agent_id bigint references public.voice_agents(id) on delete set null;

create table public.calls (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  channel_id       bigint not null references public.channels(id),
  contact_id       bigint not null references public.contacts(id) on delete cascade,
  conversation_id  bigint references public.conversations(id) on delete set null,
  wa_call_id       text not null unique,
  direction        text not null check (direction in ('inbound', 'outbound')),
  status           text not null default 'ringing' check (status in
                     ('ringing', 'pre_accepted', 'connected', 'transferring', 'ended', 'missed', 'rejected', 'failed')),
  handled_by       text check (handled_by in ('voice_agent', 'agent')),
  voice_agent_id   bigint references public.voice_agents(id) on delete set null,
  agent_id         bigint references public.agents(id) on delete set null,
  started_at       timestamptz not null default now(),
  answered_at      timestamptz,
  ended_at         timestamptz,
  duration_s       int generated always as (
                     case when ended_at is not null and answered_at is not null
                          then greatest(0, extract(epoch from (ended_at - answered_at))::int) end) stored,
  end_reason       text,
  recording_path   text,
  transcript       text,
  summary          text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index calls_org_started_idx on public.calls (organization_id, started_at desc);
create index calls_contact_idx on public.calls (contact_id, started_at desc);
create index calls_active_idx on public.calls (organization_id, status) where status in ('ringing', 'pre_accepted', 'connected', 'transferring');
create trigger trg_calls_updated before update on public.calls
  for each row execute function public.set_updated_at();

create table public.call_events (
  id          bigint generated by default as identity,
  call_id     bigint not null,
  type        text not null,                -- connect | pre_accept | accept | terminate | transfer | status | error
  payload     jsonb,
  created_at  timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);
create table public.call_events_default partition of public.call_events default;
select public.ensure_monthly_partitions('public.call_events', 3);
create index call_events_call_idx on public.call_events (call_id, created_at);

create table public.call_turns (
  id          bigint generated by default as identity primary key,
  call_id     bigint not null references public.calls(id) on delete cascade,
  speaker     text not null check (speaker in ('contact', 'voice_agent', 'agent')),
  text        text not null,
  start_ms    int,
  end_ms      int,
  created_at  timestamptz not null default now()
);
create index call_turns_call_idx on public.call_turns (call_id, id);

-- Mensaje de tipo "call" (tarjeta en el chat) y eventos de llamada en los hechos
alter table public.messages drop constraint if exists messages_type_check;
alter table public.messages add constraint messages_type_check check (type in
  ('text', 'image', 'audio', 'video', 'document', 'sticker', 'location', 'interactive', 'contacts', 'template',
   'product', 'unsupported', 'call'));

create or replace function public.trg_call_events() returns trigger
language plpgsql set search_path = public, pg_temp as $$
declare conv public.conversations;
begin
  if new.conversation_id is null then return null; end if;
  select * into conv from public.conversations where id = new.conversation_id;
  if tg_op = 'INSERT' then
    perform public.log_conversation_event(conv, 'call_started', jsonb_build_object('call_id', new.id, 'direction', new.direction));
  elsif new.ended_at is not null and old.ended_at is null then
    perform public.log_conversation_event(conv, 'call_ended',
      jsonb_build_object('call_id', new.id, 'status', new.status, 'duration_s', new.duration_s, 'handled_by', new.handled_by));
  end if;
  return null;
end $$;
create trigger trg_calls_events after insert or update of ended_at on public.calls
  for each row execute function public.trg_call_events();
revoke execute on function public.trg_call_events() from public;
