-- =============================================================================
-- 36 · Hub de integraciones (docs/data-model.md §21.3)
--
-- Conectores listos (Shopify, WooCommerce, VTEX, Google Calendar, Outlook, Zoho CRM, Odoo, BigQuery) y un
-- constructor de conectores genéricos (REST + mapeo) para DMS/ERP. Pedidos externos para atribución y journeys,
-- sincronización de citas con calendarios, y exportación de datos a un almacén (BigQuery / S3 / GCS).
-- =============================================================================

alter table public.integration_connections drop constraint integration_connections_provider_check;
alter table public.integration_connections add constraint integration_connections_provider_check check (provider in
  ('hubspot', 'salesforce', 'google_ads', 'meta',
   'shopify', 'woocommerce', 'vtex', 'google_calendar', 'microsoft_calendar', 'zoho', 'odoo', 'bigquery', 'custom'));
alter table public.integration_connections
  add column connector_id  bigint,               -- custom: definición del conector
  add column label         text;                 -- varias conexiones del mismo proveedor (p. ej. dos tiendas)
-- Una cuenta por proveedor para las integraciones de cuenta única (el código las busca por proveedor); varias
-- conexiones con etiqueta distinta solo para tiendas y conectores propios (p. ej. dos tiendas Shopify).
alter table public.integration_connections drop constraint integration_connections_organization_id_provider_key;
create unique index integration_connections_single_idx on public.integration_connections (organization_id, provider)
  where provider not in ('shopify', 'woocommerce', 'vtex', 'custom');
create unique index integration_connections_multi_idx on public.integration_connections
  (organization_id, provider, coalesce(label, '')) where provider in ('shopify', 'woocommerce', 'vtex', 'custom');

-- Constructor de conectores genéricos -------------------------------------------------------------------------
create table public.connector_definitions (
  id               bigint generated by default as identity primary key,
  organization_id  bigint references public.organizations(id) on delete cascade,   -- null = plantilla de la plataforma
  key              text not null check (key ~ '^[a-z][a-z0-9_]{0,49}$'),
  name             text not null,
  description      text,
  base_url         text not null check (base_url ~ '^https://'),
  -- {type: api_key|bearer|basic|oauth2_client_credentials|oauth2_code, header?, query_param?, token_url?, scopes?}
  auth             jsonb not null default '{}'::jsonb,
  -- [{key, method, path, query, body_template, pagination: {type: page|offset|cursor|link, ...}, items_path,
  --   rate_limit_per_min}]
  endpoints        jsonb not null default '[]'::jsonb,
  -- {contact|product|order|appointment|deal: {pull?: {endpoint, fields: {local: "$.remote.path"}, transforms},
  --   push?: {endpoint, body: {...}}}, id_field, updated_field}
  mappings         jsonb not null default '{}'::jsonb,
  webhooks         jsonb not null default '{}'::jsonb,   -- {secret_header, signature: hmac_sha256, events: {...}}
  version          int not null default 1,
  is_published     boolean not null default false,
  created_by       bigint references public.agents(id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create unique index connector_definitions_key_idx on public.connector_definitions (coalesce(organization_id, 0), key);
create trigger trg_connector_definitions_updated before update on public.connector_definitions
  for each row execute function public.set_updated_at();
alter table public.integration_connections add constraint integration_connections_connector_fk
  foreign key (connector_id) references public.connector_definitions(id) on delete set null;

create table public.connector_runs (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  connection_id    bigint not null references public.integration_connections(id) on delete cascade,
  entity           text not null,               -- contact | product | order | appointment | deal | export
  direction        text not null check (direction in ('pull', 'push', 'webhook', 'export')),
  status           text not null default 'running' check (status in ('running', 'succeeded', 'partial', 'failed')),
  fetched          int not null default 0,
  created          int not null default 0,
  updated          int not null default 0,
  skipped          int not null default 0,
  failed           int not null default 0,
  cursor_before    text,
  cursor_after     text,
  error            text,
  sample_errors    jsonb not null default '[]'::jsonb,
  started_at       timestamptz not null default now(),
  finished_at      timestamptz
);
create index connector_runs_conn_idx on public.connector_runs (connection_id, started_at desc);

-- Pedidos de tiendas / ERP -----------------------------------------------------------------------------------
create table public.external_orders (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  connection_id    bigint not null references public.integration_connections(id) on delete cascade,
  external_id      text not null,
  order_number     text,
  contact_id       bigint references public.contacts(id) on delete set null,
  status           text not null,                -- normalizado: pending|paid|fulfilled|cancelled|refunded
  status_raw       text,
  total            numeric(16, 2),
  currency         char(3),
  items            jsonb not null default '[]'::jsonb,   -- [{sku, name, quantity, price, product_id?}]
  customer         jsonb not null default '{}'::jsonb,   -- email/teléfono/nombre tal como llegan (para enlazar)
  attribution_id   bigint references public.attributions(id) on delete set null,   -- conversación que lo originó
  placed_at        timestamptz,
  updated_at       timestamptz not null default now(),
  raw              jsonb,
  unique (connection_id, external_id)
);
create index external_orders_contact_idx on public.external_orders (organization_id, contact_id, placed_at desc);
create index external_orders_placed_idx on public.external_orders (organization_id, placed_at);

-- Citas sincronizadas con calendarios
alter table public.appointments
  add column calendar_connection_id bigint references public.integration_connections(id) on delete set null,
  add column external_event_id      text,
  add column calendar_synced_at     timestamptz;
create unique index appointments_external_event_idx on public.appointments (calendar_connection_id, external_event_id)
  where external_event_id is not null;

-- Exportación a almacén de datos ------------------------------------------------------------------------------
create table public.data_exports (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  name             text not null,
  destination      text not null check (destination in ('bigquery', 's3', 'gcs', 'sftp', 'download')),
  -- {project, dataset, location} | {bucket, prefix, region} …  (credenciales en Vault: config.secret_id)
  config           jsonb not null default '{}'::jsonb,
  -- tablas/vistas: reporting.daily_*, v_contact_bi, v_conversation_bi, conversations, contacts (sin datos sensibles
  -- salvo que se marque include_sensitive), journeys, ads…
  datasets         text[] not null default '{}',
  format           text not null default 'parquet' check (format in ('parquet', 'csv', 'jsonl')),
  schedule         text not null default 'daily' check (schedule in ('hourly', 'daily', 'weekly', 'manual')),
  incremental      boolean not null default true,
  include_sensitive boolean not null default false,
  last_export_at   timestamptz,
  last_status      text,
  last_error       text,
  is_active        boolean not null default true,
  created_by       bigint references public.agents(id) on delete set null,
  created_at       timestamptz not null default now()
);

create table public.data_export_runs (
  id               bigint generated by default as identity primary key,
  export_id        bigint not null references public.data_exports(id) on delete cascade,
  status           text not null default 'running' check (status in ('running', 'succeeded', 'failed')),
  rows_exported    bigint not null default 0,
  bytes            bigint not null default 0,
  files            jsonb not null default '[]'::jsonb,
  watermark        timestamptz,                  -- incremental: hasta dónde se exportó
  error            text,
  started_at       timestamptz not null default now(),
  finished_at      timestamptz
);
create index data_export_runs_idx on public.data_export_runs (export_id, started_at desc);

alter table public.connector_definitions enable row level security;
alter table public.connector_runs enable row level security;
alter table public.external_orders enable row level security;
alter table public.data_exports enable row level security;
alter table public.data_export_runs enable row level security;
do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'auth') then
    execute 'create policy org_read on public.external_orders for select to authenticated
             using (organization_id = (select private.current_org_id()))';
  end if;
end $$;
