-- =============================================================================
-- 31 · Arquitectura de escala (docs/data-model.md §19.2)
--
-- Servicio de voz separado (rol "voice": las sesiones de medios viven en un nodo de voz; la API enruta la
-- señalización al nodo dueño), cola de trabajos en Postgres (SKIP LOCKED) para el trabajo en segundo plano, y
-- metadatos para que el panel use Supabase Realtime (canales privados por empresa, ya publicados por triggers).
-- =============================================================================

alter table public.worker_heartbeats drop constraint worker_heartbeats_role_check;
alter table public.worker_heartbeats add constraint worker_heartbeats_role_check
  check (role in ('api', 'worker', 'all', 'voice'));
alter table public.worker_heartbeats
  add column capacity      int,               -- voz: sesiones simultáneas máximas
  add column active_load   int not null default 0,
  add column endpoint      text;              -- URL interna del nodo (señalización API → voz)

alter table public.calls
  add column media_node_id  text,             -- worker_heartbeats.worker_id dueño de la sesión de medios
  add column media_node_at  timestamptz;
create index calls_media_node_idx on public.calls (media_node_id) where status in ('ringing', 'in_progress');

-- Cola de trabajos ------------------------------------------------------------------------------------------
create table public.jobs (
  id               bigint generated by default as identity primary key,
  organization_id  bigint references public.organizations(id) on delete cascade,
  queue            text not null default 'default',   -- default | ai | outbound | crm | conversions | reports | media
  kind             text not null,                     -- "golden.extract_document", "crm.push_contact"...
  payload          jsonb not null default '{}'::jsonb,
  dedupe_key       text,                              -- evita encolar dos veces el mismo trabajo pendiente
  priority         smallint not null default 100,     -- menor = antes
  status           text not null default 'queued' check (status in ('queued', 'running', 'succeeded', 'failed', 'dead', 'cancelled')),
  run_at           timestamptz not null default now(),
  attempts         int not null default 0,
  max_attempts     int not null default 5,
  locked_by        text,
  locked_until     timestamptz,
  last_error       text,
  result           jsonb,
  created_at       timestamptz not null default now(),
  started_at       timestamptz,
  finished_at      timestamptz
);
create index jobs_ready_idx on public.jobs (queue, priority, run_at) where status = 'queued';
create index jobs_stuck_idx on public.jobs (locked_until) where status = 'running';
create unique index jobs_dedupe_idx on public.jobs (queue, dedupe_key) where dedupe_key is not null and status in ('queued', 'running');
create index jobs_org_idx on public.jobs (organization_id, created_at desc);
create index jobs_finished_idx on public.jobs (finished_at) where status in ('succeeded', 'cancelled');

-- Toma atómica de hasta N trabajos listos (SKIP LOCKED: varios workers sin bloquearse)
create or replace function public.jobs_claim(p_queue text, p_worker text, p_limit int, p_lease_s int)
returns setof public.jobs
language plpgsql set search_path = public, pg_temp as $$
begin
  return query
  update public.jobs j set status = 'running', locked_by = p_worker, attempts = j.attempts + 1,
         locked_until = now() + make_interval(secs => p_lease_s), started_at = coalesce(j.started_at, now())
  where j.id in (
    select id from public.jobs
    where queue = p_queue and status = 'queued' and run_at <= now()
    order by priority, run_at
    limit p_limit
    for update skip locked)
  returning j.*;
end $$;
revoke all on function public.jobs_claim(text, text, int, int) from public;

-- Trabajos con el lease vencido (worker caído) vuelven a la cola o pasan a "dead"
create or replace function public.jobs_requeue_stuck() returns int
language sql set search_path = public, pg_temp as $$
  with s as (
    update public.jobs set status = case when attempts >= max_attempts then 'dead' else 'queued' end,
                           locked_by = null, locked_until = null,
                           last_error = coalesce(last_error, 'lease expired')
    where status = 'running' and locked_until < now()
    returning 1)
  select count(*)::int from s
$$;
revoke all on function public.jobs_requeue_stuck() from public;

do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('jobs-housekeeping', '*/5 * * * *', $c$
      select public.jobs_requeue_stuck();
      delete from public.jobs where status in ('succeeded', 'cancelled') and finished_at < now() - interval '7 days';
      delete from public.jobs where status in ('failed', 'dead') and finished_at < now() - interval '30 days';
    $c$);
  end if;
end $$;

-- Supabase Realtime en el panel: el token de Realtime del asesor se emite con su empresa y su id (app_metadata);
-- las políticas de realtime.messages (migración 09) ya restringen los temas privados org:{id}. Registro de qué
-- usuario de Supabase Auth corresponde a cada asesor cuando no se usa Supabase Auth para iniciar sesión:
alter table public.agents add column realtime_subject uuid;   -- sub del JWT de Realtime (estable por asesor)

alter table public.jobs enable row level security;
