-- =============================================================================
-- 18 · Omnicanal: Instagram DM, Facebook Messenger y chat web (docs/data-model.md §12.2)
--
-- Un contacto puede tener varias identidades (número de WhatsApp, PSID de Messenger, IGSID de Instagram,
-- visitante del chat web). contacts.wa_id deja de ser obligatorio; contact_identities es la llave de entrada
-- de cada canal. messages.wa_message_id / message_wa_ids guardan el id del mensaje del proveedor de cualquier
-- canal (mid de Meta, uuid del chat web).
-- =============================================================================

-- Canales ---------------------------------------------------------------------------------------
alter table public.channels drop constraint channels_provider_check;
alter table public.channels add constraint channels_provider_check
  check (provider in ('whatsapp_cloud', 'messenger', 'instagram', 'webchat'));
alter table public.channels alter column phone_number_id drop not null;
alter table public.channels
  add column external_id      text,           -- page id (Messenger), IG professional account id, widget key (chat web)
  add column page_id          text,           -- página de Facebook (Messenger e Instagram usan su token de página)
  add column settings         jsonb not null default '{}'::jsonb, -- chat web: colores, saludo, dominios permitidos
  add column status           text not null default 'active' check (status in ('active', 'disconnected', 'error')),
  add column last_error       text;
alter table public.channels add constraint channels_whatsapp_phone_check
  check (provider <> 'whatsapp_cloud' or phone_number_id is not null);
alter table public.channels add constraint channels_external_id_check
  check (provider = 'whatsapp_cloud' or external_id is not null);
create unique index channels_provider_external_idx on public.channels (provider, external_id) where external_id is not null;

-- Contactos e identidades --------------------------------------------------------------------------
alter table public.contacts alter column wa_id drop not null;
alter table public.contacts add column avatar_url text;

create table public.contact_identities (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  contact_id       bigint not null references public.contacts(id) on delete cascade,
  provider         text not null check (provider in ('whatsapp_cloud', 'messenger', 'instagram', 'webchat')),
  channel_id       bigint references public.channels(id) on delete cascade,  -- PSID/IGSID dependen de la página
  external_id      text not null,                -- wa_id, PSID, IGSID, visitor id del chat web
  username         text,                         -- @usuario de Instagram
  profile          jsonb not null default '{}'::jsonb,
  last_inbound_at  timestamptz,                  -- ventana de 24 h por canal
  created_at       timestamptz not null default now()
);
-- WhatsApp: el wa_id es global por empresa; Messenger/IG/chat web: el id es propio de la página/widget
create unique index contact_identities_wa_idx on public.contact_identities (organization_id, external_id)
  where provider = 'whatsapp_cloud';
create unique index contact_identities_channel_idx on public.contact_identities (channel_id, external_id)
  where provider <> 'whatsapp_cloud';
create index contact_identities_contact_idx on public.contact_identities (contact_id);

-- Identidades WhatsApp de los contactos existentes
insert into public.contact_identities (organization_id, contact_id, provider, external_id, last_inbound_at, created_at)
select c.organization_id, c.id, 'whatsapp_cloud', c.wa_id, c.last_seen_at, c.created_at
from public.contacts c where c.wa_id is not null
on conflict do nothing;

-- Chat web ------------------------------------------------------------------------------------------
create table public.webchat_sessions (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  channel_id       bigint not null references public.channels(id) on delete cascade,
  visitor_id       text not null,                -- cookie del widget (misma que el script de tracking)
  token_hash       text not null,                -- sha256 del token del visitante (el widget lo envía)
  contact_id       bigint references public.contacts(id) on delete set null,
  conversation_id  bigint references public.conversations(id) on delete set null,
  web_session_ref  text,                         -- ref_code de la visita (atribución)
  page_url         text,
  user_agent       text,
  ip_hash          text,
  created_at       timestamptz not null default now(),
  last_seen_at     timestamptz not null default now(),
  unique (channel_id, visitor_id)
);
create index webchat_sessions_conv_idx on public.webchat_sessions (conversation_id) where conversation_id is not null;

-- Atribución: canal de llegada
alter table public.attributions drop constraint attributions_channel_check;
alter table public.attributions add constraint attributions_channel_check check (channel in
  ('meta_ctwa', 'google_ads', 'meta_ads_web', 'paid_other', 'organic_web', 'offline', 'campaign', 'direct',
   'instagram', 'messenger', 'webchat'));

-- Reporting por canal ---------------------------------------------------------------------------------
create table reporting.daily_channels (
  organization_id  bigint not null,
  day              date not null,
  channel_id       bigint not null,
  provider         text not null,
  conversations    int not null default 0,   -- conversaciones creadas
  inbound          int not null default 0,
  outbound         int not null default 0,
  contacts_new     int not null default 0,
  refreshed_at     timestamptz not null default now(),
  primary key (organization_id, day, channel_id)
);

create or replace function reporting.refresh_channels(p_org bigint, p_from date, p_to date) returns void
language plpgsql set search_path = reporting, public, pg_temp as $$
declare
  tz  text := (select timezone from public.organizations where id = p_org);
  lo  timestamptz := (p_from::timestamp at time zone tz);
  hi  timestamptz := ((p_to + 1)::timestamp at time zone tz);
begin
  delete from reporting.daily_channels where organization_id = p_org and day between p_from and p_to;
  insert into reporting.daily_channels (organization_id, day, channel_id, provider, conversations, inbound, outbound,
      contacts_new)
  select p_org, x.day, x.channel_id, ch.provider, sum(x.conversations), sum(x.inbound), sum(x.outbound),
         sum(x.contacts_new)
  from (
    select (c.created_at at time zone tz)::date as day, c.channel_id, count(*) as conversations, 0 as inbound,
           0 as outbound, 0 as contacts_new
    from public.conversations c
    where c.organization_id = p_org and c.created_at >= lo and c.created_at < hi
    group by 1, 2
    union all
    select (m.created_at at time zone tz)::date, c.channel_id, 0, count(*) filter (where m.direction = 'in'),
           count(*) filter (where m.direction = 'out'), 0
    from public.messages m join public.conversations c on c.id = m.conversation_id
    where m.organization_id = p_org and m.created_at >= lo and m.created_at < hi
    group by 1, 2
    union all
    -- contacto nuevo: se cuenta en el canal de su primera conversación
    select (k.created_at at time zone tz)::date, f.channel_id, 0, 0, 0, count(*)
    from public.contacts k
    cross join lateral (select c.channel_id from public.conversations c where c.contact_id = k.id
                        order by c.created_at limit 1) f
    where k.organization_id = p_org and k.created_at >= lo and k.created_at < hi
    group by 1, 2
  ) x
  join public.channels ch on ch.id = x.channel_id
  group by 2, 3, 4;
end $$;
revoke all on function reporting.refresh_channels(bigint, date, date) from public;

-- RLS
alter table public.contact_identities enable row level security;
alter table public.webchat_sessions enable row level security;
do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'auth') then
    execute 'create policy org_read on public.contact_identities for select to authenticated
             using (organization_id = private.current_org_id())';
  end if;
end $$;

-- Planes: el omnicanal es una función del plan
update public.plans set features = features || '{"omnichannel": false}'::jsonb where key = 'team';
update public.plans set features = features || '{"omnichannel": true}'::jsonb where key in ('professional', 'enterprise');
