-- =============================================================================
-- 26 · Operación de contact center (docs/data-model.md §18.1)
--
-- Estados de asesor personalizables con bitácora de tiempo (reporte "Login"), sesiones de ingreso, horarios por
-- grupo (varios rangos por día, festivos, mensaje fuera de horario, asignar igual / pausar bot), automatizaciones
-- de SLA con temporizador, dueño del cliente con enrutamiento fijo, y reglas de transferencia / canales por grupo.
-- =============================================================================

-- Estados de asesor ---------------------------------------------------------------------------------------
create table public.agent_statuses (
  id                      bigint generated by default as identity primary key,
  organization_id         bigint not null references public.organizations(id) on delete cascade,
  key                     text not null check (key ~ '^[a-z][a-z0-9_]{0,39}$'),
  name                    text not null,             -- Disponible, Almuerzo, Capacitación, Baño, Reunión…
  icon                    text,
  color                   text,
  receives_conversations  boolean not null default false,
  counts_as_working       boolean not null default true,  -- suma a tiempo laborado en el reporte Login
  is_default              boolean not null default false, -- estado al ingresar
  is_offline              boolean not null default false, -- estado al salir / desconectado
  position                int not null default 100,
  is_active               boolean not null default true,
  created_at              timestamptz not null default now(),
  unique (organization_id, key)
);
create unique index agent_statuses_default_idx on public.agent_statuses (organization_id) where is_default and is_active;
create unique index agent_statuses_offline_idx on public.agent_statuses (organization_id) where is_offline and is_active;

-- Estados del sistema por empresa (equivalentes a availability)
insert into public.agent_statuses (organization_id, key, name, icon, color, receives_conversations, counts_as_working,
                                   is_default, is_offline, position)
select o.id, s.key, s.name, s.icon, s.color, s.recv, s.work, s.def, s.off, s.pos
from public.organizations o cross join (values
  ('available', 'Disponible',     '🟢', '#16a34a', true,  true,  true,  false, 10),
  ('busy',      'Ocupado',        '🔴', '#dc2626', false, true,  false, false, 20),
  ('away',      'Ausente',        '🟡', '#ca8a04', false, false, false, false, 30),
  ('offline',   'Desconectado',   '⚪', '#9ca3af', false, false, false, true,  90)) s(key, name, icon, color, recv, work, def, off, pos)
on conflict do nothing;

-- Empresas nuevas reciben los mismos estados
create or replace function private.trg_org_default_statuses() returns trigger
language plpgsql set search_path = public, pg_temp as $$
begin
  insert into public.agent_statuses (organization_id, key, name, icon, color, receives_conversations, counts_as_working,
                                     is_default, is_offline, position)
  values (new.id, 'available', 'Disponible', '🟢', '#16a34a', true, true, true, false, 10),
         (new.id, 'busy', 'Ocupado', '🔴', '#dc2626', false, true, false, false, 20),
         (new.id, 'away', 'Ausente', '🟡', '#ca8a04', false, false, false, false, 30),
         (new.id, 'offline', 'Desconectado', '⚪', '#9ca3af', false, false, false, true, 90)
  on conflict do nothing;
  return null;
end $$;
revoke all on function private.trg_org_default_statuses() from public;
create trigger trg_org_default_statuses after insert on public.organizations
  for each row execute function private.trg_org_default_statuses();

alter table public.agents
  add column status_id          bigint references public.agent_statuses(id) on delete set null,
  add column status_changed_at  timestamptz,
  add column employee_code      text;                -- código / cédula de empleado (Atom: código de usuario)
update public.agents a set status_id = s.id, status_changed_at = now()
from public.agent_statuses s where s.organization_id = a.organization_id and s.key = a.availability;

create table public.agent_status_events (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  agent_id         bigint not null references public.agents(id) on delete cascade,
  status_id        bigint references public.agent_statuses(id) on delete set null,
  status_key       text not null,                   -- copia (el estado puede borrarse)
  started_at       timestamptz not null default now(),
  ended_at         timestamptz,
  duration_s       int,                             -- se llena al cerrar el tramo
  source           text not null default 'manual' check (source in ('manual', 'login', 'logout', 'idle', 'system', 'supervisor'))
);
create index agent_status_events_agent_idx on public.agent_status_events (agent_id, started_at desc);
create index agent_status_events_org_idx on public.agent_status_events (organization_id, started_at);
create unique index agent_status_events_open_idx on public.agent_status_events (agent_id) where ended_at is null;

create table public.agent_sessions (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  agent_id         bigint not null references public.agents(id) on delete cascade,
  started_at       timestamptz not null default now(),
  last_seen_at     timestamptz not null default now(),
  ended_at         timestamptz,
  end_reason       text check (end_reason in ('logout', 'timeout', 'replaced', 'deactivated')),
  ip               text,
  user_agent       text
);
create index agent_sessions_agent_idx on public.agent_sessions (agent_id, started_at desc);
create index agent_sessions_open_idx on public.agent_sessions (organization_id, last_seen_at) where ended_at is null;

-- Horario de atención por grupo (null = horario general) ------------------------------------------------
create table public.business_hours (
  id                     bigint generated by default as identity primary key,
  organization_id        bigint not null references public.organizations(id) on delete cascade,
  group_id               bigint references public.groups(id) on delete cascade,
  timezone               text not null default 'America/Bogota',
  -- {"mon": [{"from": "08:00", "to": "12:00"}, {"from": "14:00", "to": "18:00"}], "tue": [...], ..., "sun": []}
  schedule               jsonb not null default '{}'::jsonb,
  out_of_hours_message   text,
  assign_anyway          boolean not null default false,  -- fuera de horario igual asigna a un asesor
  pause_bot              boolean not null default false,  -- fuera de horario el bot no responde
  inherit_general        boolean not null default false,  -- usa el horario general (copiado al guardar)
  updated_at             timestamptz not null default now()
);
create unique index business_hours_group_idx on public.business_hours (organization_id, coalesce(group_id, 0));

create table public.business_holidays (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  day              date not null,
  name             text not null,
  group_id         bigint references public.groups(id) on delete cascade,   -- null = toda la empresa
  unique (organization_id, day, group_id)
);

-- Reglas por grupo: a qué grupos se puede transferir y qué canales atiende
alter table public.groups
  add column transfer_group_ids  bigint[],          -- null = a cualquiera; {} = a ninguno
  add column channel_ids         bigint[] not null default '{}',   -- vacío = todos
  add column routing             text not null default 'least_loaded'
                                   check (routing in ('least_loaded', 'round_robin', 'sticky_owner', 'manual')),
  add column max_open_per_agent  int check (max_open_per_agent > 0),
  add column last_assigned_agent_id bigint references public.agents(id) on delete set null;   -- round robin

-- Dueño del cliente y enrutamiento fijo ----------------------------------------------------------------------
alter table public.contacts
  add column owner_agent_id     bigint references public.agents(id) on delete set null,
  add column owner_assigned_at  timestamptz;
create index contacts_owner_idx on public.contacts (organization_id, owner_agent_id) where owner_agent_id is not null;

-- Automatizaciones de SLA con temporizador ------------------------------------------------------------------
alter table public.automations drop constraint automations_type_check;
alter table public.automations add constraint automations_type_check check (type in
  ('welcome', 'keyword_reply', 'keyword_handoff', 'business_hours', 'inactivity_close',
   'sla_agent_no_reply',      -- el asesor no responde en X min → mensaje / reasignar en el grupo / avisar supervisor
   'sla_client_no_reply',     -- el cliente no responde en el bot en X min → transferir / tipificar / cerrar
   'sla_unassigned'));        -- conversación en cola sin asesor X min → reasignar / escalar
create table public.automation_runs (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  automation_id    bigint not null references public.automations(id) on delete cascade,
  conversation_id  bigint not null references public.conversations(id) on delete cascade,
  cycle_key        text not null,                 -- evita repetir: ej. timestamp del último mensaje del cliente
  action           text not null,
  result           jsonb not null default '{}'::jsonb,
  fired_at         timestamptz not null default now(),
  unique (automation_id, conversation_id, cycle_key)
);
create index automation_runs_org_idx on public.automation_runs (organization_id, fired_at);

-- Conversación: asignaciones, recurrencia (para sub-estados y AHT) ---------------------------------------------
alter table public.conversations
  add column first_assigned_at  timestamptz,
  add column assigned_at        timestamptz,       -- última asignación
  add column assignment_count   int not null default 0,
  add column is_returning       boolean not null default false,   -- el cliente ya tenía conversaciones antes
  add column last_agent_message_at timestamptz;

create or replace function private.trg_conversations_assignment() returns trigger
language plpgsql set search_path = public, pg_temp as $$
begin
  if tg_op = 'INSERT' then
    new.is_returning := exists (select 1 from public.conversations c where c.contact_id = new.contact_id);
    if new.assigned_agent_id is not null then
      new.first_assigned_at := now(); new.assigned_at := now(); new.assignment_count := 1;
    end if;
  elsif new.assigned_agent_id is distinct from old.assigned_agent_id and new.assigned_agent_id is not null then
    new.first_assigned_at := coalesce(old.first_assigned_at, now());
    new.assigned_at := now();
    new.assignment_count := old.assignment_count + 1;
  end if;
  return new;
end $$;
revoke all on function private.trg_conversations_assignment() from public;
create trigger trg_conversations_assignment before insert or update of assigned_agent_id on public.conversations
  for each row execute function private.trg_conversations_assignment();

create or replace function private.trg_messages_agent_reply() returns trigger
language plpgsql set search_path = public, pg_temp as $$
begin
  if new.sender_type = 'agent' then
    update public.conversations set last_agent_message_at = greatest(coalesce(last_agent_message_at, new.created_at), new.created_at)
    where id = new.conversation_id;
  end if;
  return null;
end $$;
revoke all on function private.trg_messages_agent_reply() from public;
create trigger trg_messages_agent_reply after insert on public.messages
  for each row execute function private.trg_messages_agent_reply();

-- Backfill
update public.conversations c set is_returning = exists (
  select 1 from public.conversations p where p.contact_id = c.contact_id and p.created_at < c.created_at);
update public.conversations c set first_assigned_at = coalesce(c.handoff_at, c.created_at), assigned_at = coalesce(c.handoff_at, c.created_at),
  assignment_count = 1 where c.assigned_agent_id is not null;

-- RLS
alter table public.agent_statuses enable row level security;
alter table public.agent_status_events enable row level security;
alter table public.agent_sessions enable row level security;
alter table public.business_hours enable row level security;
alter table public.business_holidays enable row level security;
alter table public.automation_runs enable row level security;
do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'auth') then
    execute 'create policy org_read on public.agent_statuses for select to authenticated
             using (organization_id = private.current_org_id())';
    execute 'create policy org_read on public.business_hours for select to authenticated
             using (organization_id = private.current_org_id())';
  end if;
end $$;
