-- =============================================================================
-- 12 · CRM: negocios locales y sincronización con HubSpot / Salesforce (y conexiones OAuth para Ads)
-- Ver docs/data-model.md §10.2
-- =============================================================================

create table public.deals (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  contact_id       bigint not null references public.contacts(id) on delete cascade,
  conversation_id  bigint references public.conversations(id) on delete set null,
  owner_agent_id   bigint references public.agents(id) on delete set null,
  name             text not null,
  amount           numeric(14, 2) check (amount >= 0),
  currency         char(3) not null default 'COP',
  pipeline         text not null default 'default',
  stage            text not null default 'new',
  status           text not null default 'open' check (status in ('open', 'won', 'lost')),
  source           text not null default 'agent' check (source in ('agent', 'ai', 'flow', 'crm', 'import')),
  expected_close   date,
  closed_at        timestamptz,
  lost_reason      text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  check (status = 'open' or closed_at is not null)
);
create index deals_org_status_idx on public.deals (organization_id, status, updated_at desc);
create index deals_contact_idx on public.deals (contact_id);
create index deals_owner_idx on public.deals (organization_id, owner_agent_id, closed_at) where status = 'won';
create trigger trg_deals_updated before update on public.deals
  for each row execute function public.set_updated_at();

-- Cuenta externa conectada (OAuth/tokens en Vault)
create table public.integration_connections (
  id                        bigint generated by default as identity primary key,
  organization_id           bigint not null references public.organizations(id) on delete cascade,
  provider                  text not null check (provider in ('hubspot', 'salesforce', 'google_ads', 'meta')),
  status                    text not null default 'connected' check (status in ('connected', 'error', 'revoked')),
  external_account_id       text,             -- portal id (HubSpot), org id (Salesforce), customer id (Google Ads)
  instance_url              text,             -- Salesforce
  access_token_secret_id    uuid,             -- vault
  refresh_token_secret_id   uuid,             -- vault
  expires_at                timestamptz,
  scopes                    text[] not null default '{}',
  settings                  jsonb not null default '{}'::jsonb,   -- pipeline/stage por defecto, owner, etc.
  sync_enabled              boolean not null default true,
  last_sync_at              timestamptz,
  last_error                text,
  connected_by              bigint references public.agents(id) on delete set null,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now(),
  unique (organization_id, provider)
);
create trigger trg_integration_connections_updated before update on public.integration_connections
  for each row execute function public.set_updated_at();

create table public.integration_mappings (
  id               bigint generated by default as identity primary key,
  connection_id    bigint not null references public.integration_connections(id) on delete cascade,
  object           text not null check (object in ('contact', 'deal')),
  local_field      text not null,         -- name | email | stage | memory | custom:<key> | deal.amount ...
  remote_property  text not null,
  direction        text not null default 'both' check (direction in ('push', 'pull', 'both')),
  transform        jsonb,                 -- {"map": {"client": "customer"}} etc.
  unique (connection_id, object, local_field)
);

create table public.external_links (
  id                 bigint generated by default as identity primary key,
  connection_id      bigint not null references public.integration_connections(id) on delete cascade,
  local_type         text not null check (local_type in ('contact', 'deal', 'conversation')),
  local_id           bigint not null,
  remote_type        text not null,       -- contact | deal | note | Lead | Contact | Opportunity | Task
  remote_id          text not null,
  remote_updated_at  timestamptz,
  sync_hash          text,                 -- hash del último estado enviado/recibido (evita bucles)
  last_synced_at     timestamptz not null default now(),
  unique (connection_id, local_type, local_id),
  unique (connection_id, remote_type, remote_id)
);

-- Cola de salida hacia el CRM (reintentos con backoff)
create table public.integration_outbox (
  id               bigint generated by default as identity,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  connection_id    bigint not null,
  entity_type      text not null check (entity_type in ('contact', 'deal', 'conversation_note')),
  entity_id        bigint not null,
  operation        text not null default 'upsert' check (operation in ('upsert', 'delete', 'note')),
  payload          jsonb,
  status           text not null default 'pending' check (status in ('pending', 'sent', 'failed', 'skipped')),
  attempts         int not null default 0,
  next_attempt_at  timestamptz not null default now(),
  error            text,
  created_at       timestamptz not null default now(),
  sent_at          timestamptz,
  primary key (id, created_at)
) partition by range (created_at);
create table public.integration_outbox_default partition of public.integration_outbox default;
select public.ensure_monthly_partitions('public.integration_outbox', 3);
create index integration_outbox_due_idx on public.integration_outbox (next_attempt_at) where status = 'pending';
create index integration_outbox_entity_idx on public.integration_outbox (connection_id, entity_type, entity_id);

-- Evento de negocio ganado para conversiones/reportes
alter table public.conversation_events drop constraint if exists conversation_events_event_type_check;
alter table public.conversation_events add constraint conversation_events_event_type_check check (event_type in
  ('created', 'reopened', 'handoff', 'released', 'assigned', 'unassigned', 'routed', 'first_agent_response',
   'tagged', 'untagged', 'typified', 'classified', 'closed', 'flow_started', 'flow_finished', 'campaign_sent',
   'deal_won', 'deal_lost', 'call_started', 'call_ended'));

-- Orígenes nuevos
alter table public.inbound_events drop constraint if exists inbound_events_source_check;
alter table public.inbound_events add constraint inbound_events_source_check check (source in
  ('whatsapp', 'flow_webhook', 'catalog_feed', 'hubspot', 'salesforce', 'stripe'));
alter table public.contact_changes drop constraint if exists contact_changes_source_check;
alter table public.contact_changes add constraint contact_changes_source_check check (source in
  ('agent', 'ai', 'import', 'api', 'flow', 'crm'));
alter table public.contact_field_values drop constraint if exists contact_field_values_source_check;
alter table public.contact_field_values add constraint contact_field_values_source_check check (source in
  ('agent', 'ai', 'import', 'api', 'flow', 'crm'));
