-- =============================================================================
-- 33 · Diagnóstico de integraciones para salir a producción (docs/data-model.md §20)
--
-- system_checks: último resultado de cada verificación de solo lectura contra los servicios reales (Meta, Google
-- Ads, HubSpot, Salesforce, Stripe, SMTP/IMAP, Supabase Storage/Vault/Realtime, pooler LISTEN, SSO, VAPID, voz).
-- organization_id null = verificación de la plataforma (variables del servidor); con empresa = sus conexiones.
-- system_check_runs: historial de corridas (quién, cuándo, resumen) para comparar antes/después de un despliegue.
-- =============================================================================

create table public.system_check_runs (
  id               bigint generated by default as identity primary key,
  organization_id  bigint references public.organizations(id) on delete cascade,
  trigger          text not null default 'manual' check (trigger in ('manual', 'cli', 'deploy', 'schedule')),
  started_by       bigint references public.agents(id) on delete set null,
  app_version      text,
  passed           int not null default 0,
  warned           int not null default 0,
  failed           int not null default 0,
  skipped          int not null default 0,
  started_at       timestamptz not null default now(),
  finished_at      timestamptz
);
create index system_check_runs_org_idx on public.system_check_runs (organization_id, started_at desc);

create table public.system_checks (
  id               bigint generated by default as identity primary key,
  organization_id  bigint references public.organizations(id) on delete cascade,
  area             text not null,      -- meta | google_ads | hubspot | salesforce | stripe | email | supabase | sso |
                                       -- push | voice | infra
  check_key        text not null,      -- "meta.token_scopes", "smtp.login", "supabase.pooler_listen"…
  label            text not null,
  status           text not null check (status in ('pass', 'warn', 'fail', 'skipped')),
  detail           text,               -- explicación en lenguaje claro + cómo arreglarlo
  data             jsonb not null default '{}'::jsonb,   -- sin secretos: ids, scopes, versiones, latencias
  latency_ms       int,
  run_id           bigint references public.system_check_runs(id) on delete set null,
  checked_at       timestamptz not null default now()
);
create unique index system_checks_key_idx on public.system_checks (coalesce(organization_id, 0), check_key);
create index system_checks_status_idx on public.system_checks (organization_id, status);

alter table public.system_check_runs enable row level security;
alter table public.system_checks enable row level security;
