-- =============================================================================
-- 35 · Base de conocimiento con RAG (docs/data-model.md §21.2)
--
-- Fuentes (archivos, sitio web, catálogo, conversaciones resueltas, documentos existentes) → documentos →
-- fragmentos con embedding (pgvector, 1024 dimensiones: Voyage AI voyage-3.x o OpenAI text-embedding-3-* con
-- dimensions=1024) + texto para búsqueda híbrida (vector + palabras en español). Cada consulta queda registrada
-- con sus fuentes para citar y para detectar vacíos (preguntas sin respuesta).
-- =============================================================================

create extension if not exists vector with schema extensions;

create table public.knowledge_sources (
  id                bigint generated by default as identity primary key,
  organization_id   bigint not null references public.organizations(id) on delete cascade,
  type              text not null check (type in ('upload', 'website', 'catalog', 'conversations', 'legacy_docs', 'faq', 'api')),
  name              text not null,
  -- website: {url, max_pages, include[], exclude[], same_domain}; conversations: {typifications[], min_qa_score,
  -- days}; catalog: {}; upload: {}; api: {}
  config            jsonb not null default '{}'::jsonb,
  status            text not null default 'idle' check (status in ('idle', 'syncing', 'ready', 'error')),
  refresh_hours     int,                          -- null = manual
  documents_count   int not null default 0,
  chunks_count      int not null default 0,
  last_synced_at    timestamptz,
  last_error        text,
  ai_agent_ids      bigint[] not null default '{}', -- vacío = disponible para todos los agentes de IA
  is_active         boolean not null default true,
  created_by        bigint references public.agents(id) on delete set null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now()
);
create trigger trg_knowledge_sources_updated before update on public.knowledge_sources
  for each row execute function public.set_updated_at();

create table public.knowledge_documents (
  id                bigint generated by default as identity primary key,
  organization_id   bigint not null references public.organizations(id) on delete cascade,
  source_id         bigint not null references public.knowledge_sources(id) on delete cascade,
  title             text not null,
  uri               text,                         -- URL, ruta en Storage, sku, id de conversación
  mime              text,
  storage_path      text,
  checksum          text,                         -- sha256 del texto: si no cambió, no se re-procesa
  language          text,
  status            text not null default 'pending' check (status in ('pending', 'processing', 'ready', 'failed', 'excluded')),
  chunks_count      int not null default 0,
  tokens            int,
  metadata          jsonb not null default '{}'::jsonb,
  valid_until       timestamptz,                  -- vigencia (promociones, precios): fuera de vigencia no se usa
  error             text,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (source_id, uri)
);
create index knowledge_documents_org_idx on public.knowledge_documents (organization_id, status);
create trigger trg_knowledge_documents_updated before update on public.knowledge_documents
  for each row execute function public.set_updated_at();

create table public.knowledge_chunks (
  id                bigint generated by default as identity primary key,
  organization_id   bigint not null,
  document_id       bigint not null references public.knowledge_documents(id) on delete cascade,
  ordinal           int not null,
  heading           text,                         -- título/sección para citar
  content           text not null,
  tokens            int,
  embedding         extensions.vector(1024),
  embedding_model   text,
  fts               tsvector generated always as (to_tsvector('spanish', coalesce(heading, '') || ' ' || content)) stored,
  created_at        timestamptz not null default now(),
  unique (document_id, ordinal)
);
create index knowledge_chunks_org_idx on public.knowledge_chunks (organization_id);
create index knowledge_chunks_fts_idx on public.knowledge_chunks using gin (fts);
create index knowledge_chunks_embedding_idx on public.knowledge_chunks
  using hnsw (embedding extensions.vector_cosine_ops) with (m = 16, ef_construction = 64);

-- Búsqueda híbrida (Reciprocal Rank Fusion de vector + texto), filtrada por empresa, vigencia y fuentes
create or replace function public.knowledge_search(p_org bigint, p_embedding extensions.vector(1024), p_query text,
                                                   p_limit int default 8, p_source_ids bigint[] default null)
returns table (chunk_id bigint, document_id bigint, score double precision)
language sql stable set search_path = public, extensions, pg_temp as $$
  with eligible as (
    select c.id, c.document_id, c.embedding, c.fts
    from public.knowledge_chunks c
    join public.knowledge_documents d on d.id = c.document_id
    join public.knowledge_sources s on s.id = d.source_id
    where c.organization_id = p_org and d.status = 'ready' and s.is_active
      and (d.valid_until is null or d.valid_until > now())
      and (p_source_ids is null or s.id = any(p_source_ids))
  ),
  vec as (
    select id, document_id, row_number() over (order by embedding <=> p_embedding) as r
    from eligible where p_embedding is not null and embedding is not null
    order by embedding <=> p_embedding limit greatest(p_limit * 4, 20)
  ),
  txt as (
    select id, document_id, row_number() over (order by ts_rank_cd(fts, q) desc) as r
    -- OR entre los términos (sin stopwords): una pregunta natural no repite todas las palabras del documento;
    -- ts_rank_cd premia los fragmentos que cubren más términos
    from eligible, lateral (select nullif(replace(plainto_tsquery('spanish', coalesce(p_query, ''))::text, ' & ', ' | '), '')
                            as qt) x, to_tsquery('spanish', coalesce(x.qt, '')) q
    where p_query is not null and fts @@ q
    order by ts_rank_cd(fts, q) desc limit greatest(p_limit * 4, 20)
  )
  select coalesce(v.id, t.id), coalesce(v.document_id, t.document_id),
         coalesce(1.0 / (60 + v.r), 0) + coalesce(1.0 / (60 + t.r), 0) as score
  from vec v full outer join txt t on t.id = v.id
  order by score desc
  limit p_limit
$$;
revoke all on function public.knowledge_search(bigint, extensions.vector, text, int, bigint[]) from public;

-- Consultas y vacíos de conocimiento --------------------------------------------------------------------------
create table public.knowledge_queries (
  id               bigint generated by default as identity,
  organization_id  bigint not null,
  conversation_id  bigint,
  ai_agent_id      bigint,
  agent_id         bigint,                        -- consulta hecha por un asesor / copiloto
  query            text not null,
  results          jsonb not null default '[]'::jsonb,   -- [{chunk_id, document_id, score}]
  top_score        double precision,
  answered         boolean,                       -- la respuesta citó al menos una fuente
  ai_call_id       bigint,
  latency_ms       int,
  created_at       timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);
create table public.knowledge_queries_default partition of public.knowledge_queries default;
select public.ensure_monthly_partitions('public.knowledge_queries', 3);
create index knowledge_queries_org_idx on public.knowledge_queries (organization_id, created_at desc);
create index knowledge_queries_unanswered_idx on public.knowledge_queries (organization_id, created_at)
  where answered is false;

create table public.knowledge_gaps (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  topic            text not null,                 -- pregunta representativa del grupo
  examples         text[] not null default '{}',
  occurrences      int not null default 1,
  first_seen_at    timestamptz not null default now(),
  last_seen_at     timestamptz not null default now(),
  status           text not null default 'open' check (status in ('open', 'answered', 'ignored')),
  resolved_document_id bigint references public.knowledge_documents(id) on delete set null,
  embedding        extensions.vector(1024)        -- para agrupar preguntas parecidas
);
create index knowledge_gaps_org_idx on public.knowledge_gaps (organization_id, status, occurrences desc);

do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('knowledge-queries-partitions', '55 3 * * *', $c$
      select public.ensure_monthly_partitions('public.knowledge_queries', 3);
      select public.drop_old_partitions('public.knowledge_queries', 6);
    $c$);
  end if;
end $$;

alter table public.knowledge_sources enable row level security;
alter table public.knowledge_documents enable row level security;
alter table public.knowledge_chunks enable row level security;
alter table public.knowledge_queries enable row level security;
alter table public.knowledge_gaps enable row level security;
