-- =============================================================================
-- 03 · Conversaciones, mensajes (particionado), hechos, etiquetas, tipificaciones, sugerencias IA
-- =============================================================================

create table public.typifications (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  name             text not null,
  criteria         text,                        -- cuándo aplicarla (guía a la IA)
  is_success       boolean not null default false,  -- cuenta como venta ganada
  is_active        boolean not null default true,
  position         int not null default 100,
  created_at       timestamptz not null default now(),
  unique (organization_id, name)
);

create table public.conversations (
  id                    bigint generated by default as identity primary key,
  organization_id       bigint not null references public.organizations(id) on delete cascade,
  contact_id            bigint not null references public.contacts(id) on delete cascade,
  channel_id            bigint not null references public.channels(id),
  ai_agent_id           bigint,                -- FK en 04
  status                text not null default 'bot' check (status in ('bot', 'human', 'closed')),
  assigned_agent_id     bigint references public.agents(id) on delete set null,
  group_id              bigint references public.groups(id) on delete set null,
  typification_id       bigint references public.typifications(id) on delete set null,
  -- Momentos clave (desnormalizados para SLA y listas; la historia completa está en conversation_events)
  handoff_reason        text,
  handoff_at            timestamptz,
  first_response_at     timestamptz,            -- primera respuesta de asesor después del handoff
  closed_at             timestamptz,
  reopened_count        int not null default 0,
  -- Contadores mantenidos por trigger desde messages
  message_count         int not null default 0,
  inbound_count         int not null default 0,
  unread_count          int not null default 0,
  last_message_at       timestamptz not null default now(),
  last_inbound_at       timestamptz,
  last_message_preview  text,
  -- Click to WhatsApp (referral de Meta)
  ad_source_type        text,
  ad_source_id          text,
  ad_headline           text,
  ad_source_url         text,
  ad_ctwa_clid          text,
  -- Clasificación por IA
  ai_summary            text,
  ai_sentiment          text check (ai_sentiment in ('positive', 'neutral', 'negative')),
  ai_typification_id    bigint references public.typifications(id) on delete set null,
  ai_classified_at      timestamptz,
  ai_inbound_mark       int not null default 0,  -- inbound_count en el último análisis
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  check (status <> 'closed' or closed_at is not null)
);
-- Bandeja: abiertas por fecha, por asesor, cola sin asignar, por grupo
create index conv_org_status_last_idx on public.conversations (organization_id, status, last_message_at desc);
create index conv_open_agent_idx on public.conversations (organization_id, assigned_agent_id, last_message_at desc)
  where status <> 'closed';
create index conv_queue_idx on public.conversations (organization_id, group_id, handoff_at)
  where status = 'human' and assigned_agent_id is null;
create index conv_contact_idx on public.conversations (contact_id, created_at desc);
create index conv_org_created_idx on public.conversations (organization_id, created_at);
create index conv_org_closed_idx on public.conversations (organization_id, closed_at) where closed_at is not null;
create index conv_org_handoff_idx on public.conversations (organization_id, handoff_at) where handoff_at is not null;
create index conv_ad_idx on public.conversations (organization_id, ad_source_id) where ad_source_id is not null;
create trigger trg_conversations_updated before update on public.conversations
  for each row execute function public.set_updated_at();

alter table public.contact_changes
  add constraint contact_changes_conversation_fk
  foreign key (conversation_id) references public.conversations(id) on delete set null;

create table public.conversation_tags (
  conversation_id  bigint not null references public.conversations(id) on delete cascade,
  tag_id           bigint not null references public.tags(id) on delete cascade,
  source           text not null default 'agent' check (source in ('agent', 'ai', 'rule', 'flow')),
  confidence       real check (confidence between 0 and 1),
  created_by       bigint references public.agents(id) on delete set null,
  created_at       timestamptz not null default now(),
  primary key (conversation_id, tag_id)
);
create index conversation_tags_tag_idx on public.conversation_tags (tag_id, created_at);

-- Cada sugerencia de la IA es una fila: permite medir la tasa de aceptación por tipo
create table public.conversation_suggestions (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  conversation_id  bigint not null references public.conversations(id) on delete cascade,
  kind             text not null check (kind in ('tag', 'typification', 'group', 'field', 'memory')),
  target           text,                        -- nombre de etiqueta, clave de campo, id de grupo...
  value            jsonb not null,
  confidence       real check (confidence between 0 and 1),
  evidence         text,
  status           text not null default 'pending' check (status in ('pending', 'accepted', 'dismissed', 'expired')),
  decided_by       bigint references public.agents(id) on delete set null,
  decided_at       timestamptz,
  ai_call_id       bigint,
  created_at       timestamptz not null default now()
);
create index conv_sugg_pending_idx on public.conversation_suggestions (conversation_id) where status = 'pending';
create index conv_sugg_org_kind_idx on public.conversation_suggestions (organization_id, kind, created_at);

-- ---------------------------------------------------------------------------
-- Mensajes: particionado mensual por created_at
-- ---------------------------------------------------------------------------
create table public.messages (
  id                bigint generated by default as identity,
  organization_id   bigint not null references public.organizations(id) on delete cascade,
  conversation_id   bigint not null references public.conversations(id) on delete cascade,
  direction         text not null check (direction in ('in', 'out')),
  sender_type       text not null check (sender_type in ('contact', 'bot', 'agent', 'campaign', 'flow', 'system')),
  sender_agent_id   bigint,
  ai_agent_id       bigint,
  type              text not null default 'text' check (type in
                      ('text', 'image', 'audio', 'video', 'document', 'sticker', 'location', 'interactive',
                       'contacts', 'template', 'product', 'unsupported')),
  text              text,
  media_path        text,                       -- ruta en Supabase Storage
  media_mime        text,
  media_filename    text,
  media_size        int,
  transcript        text,
  template_name     text,
  campaign_id       bigint,
  wa_message_id     text,
  status            text not null default 'received' check (status in
                      ('received', 'pending', 'sent', 'delivered', 'read', 'failed')),
  error_code        int,
  error             text,
  pricing_category  text,                       -- marketing | utility | authentication | service ...
  billable          boolean,
  metadata          jsonb,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);

create table public.messages_default partition of public.messages default;
select public.ensure_monthly_partitions('public.messages', 3);

create index messages_conv_idx on public.messages (conversation_id, created_at desc);
create index messages_org_created_brin on public.messages using brin (organization_id, created_at);
create index messages_wa_idx on public.messages (wa_message_id) where wa_message_id is not null;
create index messages_campaign_idx on public.messages (campaign_id) where campaign_id is not null;
create trigger trg_messages_updated before update on public.messages
  for each row execute function public.set_updated_at();

-- Idempotencia de webhooks y búsqueda por id de WhatsApp (los estados llegan después)
create table public.message_wa_ids (
  wa_message_id       text primary key,
  organization_id     bigint not null,
  message_id          bigint not null,
  message_created_at  timestamptz not null,
  conversation_id     bigint not null,
  created_at          timestamptz not null default now(),
  foreign key (message_id, message_created_at) references public.messages (id, created_at) on delete cascade
);

-- ---------------------------------------------------------------------------
-- Hechos de conversación (append-only, particionado): fuente del reporting
-- ---------------------------------------------------------------------------
create table public.conversation_events (
  id               bigint generated by default as identity,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  conversation_id  bigint not null references public.conversations(id) on delete cascade,
  event_type       text not null check (event_type in
                     ('created', 'reopened', 'handoff', 'released', 'assigned', 'unassigned', 'routed',
                      'first_agent_response', 'tagged', 'untagged', 'typified', 'classified', 'closed',
                      'flow_started', 'flow_finished', 'campaign_sent')),
  actor_type       text not null default 'system' check (actor_type in
                     ('system', 'bot', 'agent', 'ai', 'contact', 'automation', 'flow')),
  actor_agent_id   bigint,
  assigned_agent_id bigint,                     -- estado al momento del evento (para atribuir en reportes)
  group_id         bigint,
  payload          jsonb,
  occurred_at      timestamptz not null default now(),
  primary key (id, occurred_at)
) partition by range (occurred_at);

create table public.conversation_events_default partition of public.conversation_events default;
select public.ensure_monthly_partitions('public.conversation_events', 3);

create index conv_events_conv_idx on public.conversation_events (conversation_id, occurred_at);
create index conv_events_org_type_idx on public.conversation_events (organization_id, event_type, occurred_at);

-- Quién hizo el cambio: el backend lo indica por transacción con
--   select set_config('app.actor_type', 'agent', true), set_config('app.actor_agent_id', '12', true);
create or replace function public.current_actor_type() returns text
language sql stable as $$ select coalesce(nullif(current_setting('app.actor_type', true), ''), 'system') $$;

create or replace function public.current_actor_agent_id() returns bigint
language sql stable as $$ select nullif(current_setting('app.actor_agent_id', true), '')::bigint $$;

create or replace function public.log_conversation_event(
  p_conv public.conversations, p_type text, p_payload jsonb default null
) returns void
language sql as $$
  insert into public.conversation_events
    (organization_id, conversation_id, event_type, actor_type, actor_agent_id, assigned_agent_id, group_id, payload)
  values (p_conv.organization_id, p_conv.id, p_type, public.current_actor_type(), public.current_actor_agent_id(),
          p_conv.assigned_agent_id, p_conv.group_id, p_payload);
$$;

-- Los eventos de estado se generan en la base: ningún camino de escritura puede saltárselos
create or replace function public.trg_conversation_events() returns trigger
language plpgsql as $$
begin
  if tg_op = 'INSERT' then
    perform public.log_conversation_event(new, 'created');
    return new;
  end if;
  if new.status is distinct from old.status then
    if old.status = 'closed' then
      perform public.log_conversation_event(new, 'reopened', jsonb_build_object('to', new.status));
    elsif new.status = 'closed' then
      perform public.log_conversation_event(new, 'closed', jsonb_build_object(
        'typification_id', new.typification_id, 'had_handoff', new.handoff_at is not null));
    elsif old.status = 'bot' and new.status = 'human' then
      perform public.log_conversation_event(new, 'handoff', jsonb_build_object('reason', new.handoff_reason));
    elsif old.status = 'human' and new.status = 'bot' then
      perform public.log_conversation_event(new, 'released');
    end if;
  end if;
  if new.assigned_agent_id is distinct from old.assigned_agent_id then
    perform public.log_conversation_event(new, case when new.assigned_agent_id is null then 'unassigned' else 'assigned' end,
      jsonb_build_object('from', old.assigned_agent_id, 'to', new.assigned_agent_id));
  end if;
  if new.group_id is distinct from old.group_id then
    perform public.log_conversation_event(new, 'routed', jsonb_build_object('from', old.group_id, 'to', new.group_id));
  end if;
  if new.typification_id is distinct from old.typification_id and new.typification_id is not null then
    perform public.log_conversation_event(new, 'typified', jsonb_build_object('typification_id', new.typification_id));
  end if;
  if new.ai_classified_at is distinct from old.ai_classified_at then
    perform public.log_conversation_event(new, 'classified',
      jsonb_build_object('ai_typification_id', new.ai_typification_id, 'sentiment', new.ai_sentiment));
  end if;
  return new;
end $$;

create trigger trg_conversations_events after insert or update on public.conversations
  for each row execute function public.trg_conversation_events();

-- Reglas de negocio de la conversación al cambiar de estado
create or replace function public.trg_conversation_state() returns trigger
language plpgsql as $$
begin
  if new.status = 'closed' and old.status <> 'closed' then
    new.closed_at := coalesce(new.closed_at, now());
    new.unread_count := 0;
    update public.conversation_suggestions set status = 'expired'
      where conversation_id = new.id and status = 'pending';
  elsif old.status = 'closed' and new.status <> 'closed' then
    new.closed_at := null;
    new.typification_id := null;
    new.reopened_count := old.reopened_count + 1;
    new.handoff_at := null;
    new.first_response_at := null;
  end if;
  return new;
end $$;

create trigger trg_conversations_state before update of status on public.conversations
  for each row execute function public.trg_conversation_state();

-- Contadores y primera respuesta: se mantienen desde messages
create or replace function public.trg_messages_after_insert() returns trigger
language plpgsql as $$
declare
  conv public.conversations;
begin
  update public.conversations c set
    message_count = c.message_count + 1,
    inbound_count = c.inbound_count + (new.direction = 'in')::int,
    unread_count = c.unread_count + (new.direction = 'in')::int,
    last_message_at = greatest(c.last_message_at, new.created_at),
    last_inbound_at = case when new.direction = 'in' then new.created_at else c.last_inbound_at end,
    last_message_preview = case when new.sender_type = 'system' then c.last_message_preview else
      left(coalesce(new.text, new.transcript, '[' || new.type || ']'), 255) end,
    first_response_at = case
      when new.sender_type = 'agent' and c.handoff_at is not null and c.first_response_at is null
           and new.created_at >= c.handoff_at then new.created_at
      else c.first_response_at end
  where c.id = new.conversation_id
  returning c.* into conv;

  if new.sender_type = 'agent' and conv.first_response_at = new.created_at then
    perform public.log_conversation_event(conv, 'first_agent_response',
      jsonb_build_object('seconds', extract(epoch from new.created_at - conv.handoff_at)::int));
  end if;
  if new.wa_message_id is not null then
    insert into public.message_wa_ids (wa_message_id, organization_id, message_id, message_created_at, conversation_id)
    values (new.wa_message_id, new.organization_id, new.id, new.created_at, new.conversation_id)
    on conflict (wa_message_id) do nothing;
  end if;
  return null;
end $$;

create trigger trg_messages_after_insert after insert on public.messages
  for each row execute function public.trg_messages_after_insert();

-- wa_message_id puede llegar después del insert (envío asíncrono): registrar también en UPDATE
create or replace function public.trg_messages_wa_id() returns trigger
language plpgsql as $$
begin
  insert into public.message_wa_ids (wa_message_id, organization_id, message_id, message_created_at, conversation_id)
  values (new.wa_message_id, new.organization_id, new.id, new.created_at, new.conversation_id)
  on conflict (wa_message_id) do nothing;
  return null;
end $$;

create trigger trg_messages_wa_id after update of wa_message_id on public.messages
  for each row when (new.wa_message_id is not null and old.wa_message_id is distinct from new.wa_message_id)
  execute function public.trg_messages_wa_id();

-- Eventos de etiquetas
create or replace function public.trg_conversation_tags_events() returns trigger
language plpgsql as $$
declare
  conv public.conversations;
  rec record := coalesce(new, old);
begin
  select * into conv from public.conversations where id = rec.conversation_id;
  if conv.id is not null then
    perform public.log_conversation_event(conv, case when tg_op = 'INSERT' then 'tagged' else 'untagged' end,
      jsonb_build_object('tag_id', rec.tag_id, 'source', rec.source));
  end if;
  return null;
end $$;

create trigger trg_conversation_tags_events after insert or delete on public.conversation_tags
  for each row execute function public.trg_conversation_tags_events();
