-- =============================================================================
-- 17 · Escala y producción (docs/data-model.md §12.1)
--
-- Varias réplicas del backend: los eventos en vivo viajan por Postgres LISTEN/NOTIFY (canal "wa_events");
-- cada réplica los reenvía a sus WebSockets. NOTIFY admite ~8 KB: los eventos más grandes se guardan en
-- realtime_spill (UNLOGGED, vida de minutos) y el aviso lleva solo su id.
-- Trabajos en segundo plano: proceso "worker" aparte; cada bucle toma un advisory lock (uno activo por
-- clúster) y deja su latido en worker_heartbeats (monitoreo y /health).
-- Límites de uso por clave/IP compartidos entre réplicas: rate_limit_counters (UNLOGGED) + rate_limit_hit().
-- =============================================================================

create unlogged table public.realtime_spill (
  id          bigint generated by default as identity primary key,
  payload     jsonb not null,
  created_at  timestamptz not null default now()
);
create index realtime_spill_created_idx on public.realtime_spill (created_at);

create table public.worker_heartbeats (
  worker_id     text primary key,                 -- hostname:pid
  role          text not null check (role in ('api', 'worker', 'all')),
  hostname      text not null,
  version       text,
  started_at    timestamptz not null default now(),
  last_beat_at  timestamptz not null default now(),
  loops         jsonb not null default '{}'::jsonb  -- {loop: {leader, last_ok_at, last_error, last_error_at}}
);
create index worker_heartbeats_beat_idx on public.worker_heartbeats (last_beat_at);

create unlogged table public.rate_limit_counters (
  bucket        text not null,                    -- "api_key:12", "ip:1.2.3.4:/t/collect", "org:3:send"
  window_start  timestamptz not null,
  hits          int not null default 0,
  primary key (bucket, window_start)
);
create index rate_limit_counters_window_idx on public.rate_limit_counters (window_start);

-- Suma un golpe en la ventana fija actual; devuelve el total (el llamador compara con su límite).
create or replace function public.rate_limit_hit(p_bucket text, p_window_s int) returns int
language sql set search_path = public, pg_temp as $$
  insert into public.rate_limit_counters as c (bucket, window_start, hits)
  values (p_bucket, to_timestamp(floor(extract(epoch from now()) / p_window_s) * p_window_s), 1)
  on conflict (bucket, window_start) do update set hits = c.hits + 1
  returning hits
$$;
revoke all on function public.rate_limit_hit(text, int) from public;

-- Limpieza: spill > 10 min, contadores > 2 h, latidos de réplicas muertas > 1 día
create or replace function public.ops_cleanup() returns void
language sql set search_path = public, pg_temp as $$
  delete from public.realtime_spill where created_at < now() - interval '10 minutes';
  delete from public.rate_limit_counters where window_start < now() - interval '2 hours';
  delete from public.worker_heartbeats where last_beat_at < now() - interval '1 day';
$$;
revoke all on function public.ops_cleanup() from public;

alter table public.realtime_spill enable row level security;
alter table public.worker_heartbeats enable row level security;
alter table public.rate_limit_counters enable row level security;
-- Sin políticas: solo el backend (service role / owner) las usa.

do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('ops-cleanup', '*/10 * * * *', 'select public.ops_cleanup()');
  end if;
end $$;
