-- =============================================================================
-- 29 · Seguridad: roles y permisos, SSO, 2FA, política de contraseñas, IP, recuperación (docs/data-model.md §18.4)
-- =============================================================================

-- Roles con permisos granulares --------------------------------------------------------------------------------
create table public.roles (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  key              text not null check (key ~ '^[a-z][a-z0-9_]{0,39}$'),
  name             text not null,
  description      text,
  base_role        text not null default 'agent' check (base_role in ('admin', 'supervisor', 'agent')),  -- compatibilidad
  permissions      text[] not null default '{}',  -- catálogo en la app (app/permissions.py): "conversations.view_all"…
  data_scope       text not null default 'own' check (data_scope in ('own', 'groups', 'all')),
  is_system        boolean not null default false,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (organization_id, key)
);
create trigger trg_roles_updated before update on public.roles
  for each row execute function public.set_updated_at();

-- Roles del sistema por empresa (los permisos se completan desde la app al iniciar)
insert into public.roles (organization_id, key, name, base_role, data_scope, is_system)
select o.id, r.key, r.name, r.key, r.scope, true
from public.organizations o cross join (values ('admin', 'Administrador', 'all'), ('supervisor', 'Supervisor', 'groups'),
                                              ('agent', 'Asesor', 'own')) r(key, name, scope)
on conflict do nothing;

create or replace function private.trg_org_default_roles() returns trigger
language plpgsql set search_path = public, pg_temp as $$
begin
  insert into public.roles (organization_id, key, name, base_role, data_scope, is_system)
  values (new.id, 'admin', 'Administrador', 'admin', 'all', true),
         (new.id, 'supervisor', 'Supervisor', 'supervisor', 'groups', true),
         (new.id, 'agent', 'Asesor', 'agent', 'own', true)
  on conflict do nothing;
  return null;
end $$;
revoke all on function private.trg_org_default_roles() from public;
create trigger trg_org_default_roles after insert on public.organizations
  for each row execute function private.trg_org_default_roles();

alter table public.agents add column role_id bigint references public.roles(id) on delete set null;
update public.agents a set role_id = r.id from public.roles r where r.organization_id = a.organization_id and r.key = a.role;

-- Cualquier alta/edición que solo indique agents.role (demo, bootstrap, rutas antiguas) queda con su rol del sistema
create or replace function private.trg_agents_role_id() returns trigger
language plpgsql set search_path = public, pg_temp as $$
begin
  if new.role_id is null or (tg_op = 'UPDATE' and new.role is distinct from old.role
                             and new.role_id is not distinct from old.role_id) then
    select r.id into new.role_id from public.roles r
    where r.organization_id = new.organization_id and r.key = new.role and r.is_system;
  end if;
  return new;
end $$;
revoke all on function private.trg_agents_role_id() from public;
create trigger trg_agents_role_id before insert or update of role, role_id on public.agents
  for each row execute function private.trg_agents_role_id();

-- SSO (SAML 2.0 / OIDC: OneLogin, Okta, Azure AD, Google Workspace) ----------------------------------------------
create table public.sso_connections (
  id                    bigint generated by default as identity primary key,
  organization_id       bigint not null references public.organizations(id) on delete cascade,
  protocol              text not null check (protocol in ('saml', 'oidc')),
  name                  text not null,                 -- "OneLogin"
  slug                  text not null unique,          -- /auth/sso/{slug}
  -- SAML
  idp_entity_id         text,
  idp_sso_url           text,
  idp_certificate       text,                          -- público (PEM)
  idp_metadata_url      text,
  -- OIDC
  issuer                text,
  client_id             text,
  client_secret_secret_id uuid,                        -- Vault
  scopes                text[] not null default '{openid,email,profile}',
  -- comportamiento
  domains               text[] not null default '{}',  -- correos que deben usar SSO
  jit_provisioning      boolean not null default true, -- crea el usuario al primer ingreso
  default_role_id       bigint references public.roles(id) on delete set null,
  group_claim           text,                          -- atributo/claim con grupos → mapeo
  group_mapping         jsonb not null default '{}'::jsonb,   -- {"idp_group": {"role_key": "...", "group_ids": [..]}}
  enforce               boolean not null default false,       -- prohíbe contraseña local para esos dominios
  is_active             boolean not null default false,
  last_login_at         timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now(),
  check (protocol <> 'saml' or (idp_sso_url is not null or idp_metadata_url is not null)),
  check (protocol <> 'oidc' or (issuer is not null and client_id is not null))
);
create trigger trg_sso_connections_updated before update on public.sso_connections
  for each row execute function public.set_updated_at();

create table public.agent_identities (                    -- vínculo usuario ↔ identidad del IdP
  id               bigint generated by default as identity primary key,
  agent_id         bigint not null references public.agents(id) on delete cascade,
  sso_connection_id bigint not null references public.sso_connections(id) on delete cascade,
  subject          text not null,                         -- NameID / sub
  last_login_at    timestamptz,
  unique (sso_connection_id, subject)
);

-- 2FA, contraseñas y bloqueo ------------------------------------------------------------------------------------
alter table public.agents
  add column mfa_method          text check (mfa_method in ('totp', 'email')),
  add column mfa_secret_id       uuid,                    -- Vault (semilla TOTP)
  add column mfa_enabled_at      timestamptz,
  add column mfa_recovery_hashes text[] not null default '{}',
  add column password_changed_at timestamptz,
  add column must_change_password boolean not null default false,
  add column failed_logins       int not null default 0,
  add column locked_until        timestamptz;

create table public.mfa_challenges (
  id               bigint generated by default as identity primary key,
  agent_id         bigint not null references public.agents(id) on delete cascade,
  method           text not null check (method in ('totp', 'email')),
  code_hash        text,                                  -- email: sha256 del código
  token_hash       text not null unique,                  -- token de la sesión intermedia
  ip               text,
  attempts         int not null default 0,
  expires_at       timestamptz not null,
  verified_at      timestamptz,
  created_at       timestamptz not null default now()
);

create table public.trusted_devices (                     -- navegador/IP conocido: no vuelve a pedir 2FA por N días
  id               bigint generated by default as identity primary key,
  agent_id         bigint not null references public.agents(id) on delete cascade,
  device_hash      text not null,                         -- sha256 del token de dispositivo (cookie)
  ip               text,
  user_agent       text,
  last_used_at     timestamptz not null default now(),
  expires_at       timestamptz not null,
  created_at       timestamptz not null default now(),
  unique (agent_id, device_hash)
);

create table public.password_history (
  agent_id         bigint not null references public.agents(id) on delete cascade,
  password_hash    text not null,
  created_at       timestamptz not null default now()
);
create index password_history_agent_idx on public.password_history (agent_id, created_at desc);

create table public.password_resets (
  id               bigint generated by default as identity primary key,
  agent_id         bigint not null references public.agents(id) on delete cascade,
  token_hash       text not null unique,
  ip               text,
  expires_at       timestamptz not null,
  used_at          timestamptz,
  created_at       timestamptz not null default now()
);

-- Auditoría de autenticación (particionada, 12 meses) ------------------------------------------------------------
create table public.auth_events (
  id               bigint generated by default as identity,
  organization_id  bigint,
  agent_id         bigint,
  email            text,
  event            text not null check (event in ('login_ok', 'login_failed', 'logout', 'locked', 'unlocked',
                     'mfa_challenge', 'mfa_ok', 'mfa_failed', 'mfa_enabled', 'mfa_disabled', 'password_changed',
                     'password_reset_requested', 'password_reset', 'sso_login', 'sso_failed', 'ip_blocked',
                     'role_changed', 'session_revoked')),
  ip               text,
  user_agent       text,
  detail           jsonb not null default '{}'::jsonb,
  created_at       timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);
create table public.auth_events_default partition of public.auth_events default;
select public.ensure_monthly_partitions('public.auth_events', 3);
create index auth_events_org_idx on public.auth_events (organization_id, created_at desc);
create index auth_events_agent_idx on public.auth_events (agent_id, created_at desc);
-- La política (longitud, complejidad, vencimiento, historial, bloqueo, IPs permitidas, 2FA obligatorio, sesión)
-- vive en org_settings key = 'security' (app/settings_store.py DEFAULTS).

do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('auth-housekeeping', '40 3 * * *', $c$
      select public.ensure_monthly_partitions('public.auth_events', 3);
      select public.drop_old_partitions('public.auth_events', 12);
      delete from public.mfa_challenges where expires_at < now() - interval '1 day';
      delete from public.password_resets where expires_at < now() - interval '7 days';
      delete from public.trusted_devices where expires_at < now();
    $c$);
  end if;
end $$;

alter table public.roles enable row level security;
alter table public.sso_connections enable row level security;
alter table public.agent_identities enable row level security;
alter table public.mfa_challenges enable row level security;
alter table public.trusted_devices enable row level security;
alter table public.password_history enable row level security;
alter table public.password_resets enable row level security;
alter table public.auth_events enable row level security;
do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'auth') then
    execute 'create policy org_read on public.roles for select to authenticated
             using (organization_id = private.current_org_id())';
  end if;
end $$;
