-- =============================================================================
-- 04 · IA: conexiones a LLMs, Cortex (enrutamiento con failover), llamadas, agentes,
--      conocimiento, memoria del negocio, aprendizaje y "mejor vendedor"
-- =============================================================================

create table public.ai_connections (
  id                     bigint generated by default as identity primary key,
  organization_id        bigint not null references public.organizations(id) on delete cascade,
  name                   text not null,
  provider               text not null check (provider in ('anthropic', 'openai', 'openai_compatible', 'azure_openai')),
  model                  text not null,
  base_url               text,
  api_key_secret_id      uuid,                  -- vault.secrets(id); null = clave del servidor
  default_params         jsonb not null default '{}'::jsonb,   -- effort, max_tokens, temperature...
  timeout_ms             int not null default 60000 check (timeout_ms between 1000 and 600000),
  input_cost_per_mtok    numeric(10, 4),        -- USD por millón de tokens (para reportar costo)
  output_cost_per_mtok   numeric(10, 4),
  is_active              boolean not null default true,
  created_at             timestamptz not null default now(),
  updated_at             timestamptz not null default now(),
  unique (organization_id, name),
  check (provider not in ('openai_compatible', 'azure_openai') or base_url is not null)
);
create trigger trg_ai_connections_updated before update on public.ai_connections
  for each row execute function public.set_updated_at();

-- Cortex: política de enrutamiento sobre varias conexiones (failover por error, latencia o respuesta fuera de rango)
create table public.cortexes (
  id                         bigint generated by default as identity primary key,
  organization_id            bigint not null references public.organizations(id) on delete cascade,
  name                       text not null,
  description                text,
  purpose                    text not null default 'any'
                               check (purpose in ('chat', 'classification', 'learning', 'flow', 'json_edit', 'any')),
  strategy                   text not null default 'failover' check (strategy in ('failover', 'lowest_latency', 'weighted')),
  max_latency_ms             int check (max_latency_ms > 0),   -- presupuesto: si se excede se prueba la siguiente
  max_attempts               int not null default 3 check (max_attempts between 1 and 10),
  circuit_breaker_failures   int not null default 5 check (circuit_breaker_failures > 0),
  circuit_breaker_cooldown_s int not null default 120 check (circuit_breaker_cooldown_s > 0),
  validation                 jsonb not null default '{}'::jsonb,  -- reglas de "fuera de rango": min/max longitud, frases prohibidas, esquema
  is_active                  boolean not null default true,
  created_at                 timestamptz not null default now(),
  updated_at                 timestamptz not null default now(),
  unique (organization_id, name)
);
create trigger trg_cortexes_updated before update on public.cortexes
  for each row execute function public.set_updated_at();

create table public.cortex_members (
  cortex_id      bigint not null references public.cortexes(id) on delete cascade,
  connection_id  bigint not null references public.ai_connections(id) on delete cascade,
  position       int not null default 1,        -- orden en failover
  weight         int not null default 1 check (weight > 0),
  timeout_ms     int,                           -- override del timeout de la conexión
  primary key (cortex_id, connection_id)
);
create index cortex_members_order_idx on public.cortex_members (cortex_id, position);

create table public.ai_connection_health (
  connection_id         bigint primary key references public.ai_connections(id) on delete cascade,
  state                 text not null default 'closed' check (state in ('closed', 'open', 'half_open')),
  consecutive_failures  int not null default 0,
  opened_at             timestamptz,
  last_success_at       timestamptz,
  last_failure_at       timestamptz,
  last_error            text,
  latency_p50_ms        int,
  latency_p95_ms        int,
  updated_at            timestamptz not null default now()
);

-- Cada llamada a un LLM (particionado): salud, latencia, tokens, costo y cadena de failover
create table public.ai_calls (
  id                     bigint generated by default as identity,
  organization_id        bigint not null references public.organizations(id) on delete cascade,
  cortex_id              bigint,
  connection_id          bigint,
  purpose                text not null check (purpose in ('chat', 'classification', 'learning', 'flow', 'json_edit', 'test')),
  conversation_id        bigint,
  ai_agent_id            bigint,
  attempt                smallint not null default 1,
  status                 text not null check (status in ('ok', 'error', 'timeout', 'slow', 'invalid', 'refused')),
  latency_ms             int,
  input_tokens           int,
  output_tokens          int,
  cache_read_tokens      int,
  cost_usd               numeric(12, 6),
  error                  text,
  fallback_from_call_id  bigint,
  created_at             timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);
create table public.ai_calls_default partition of public.ai_calls default;
select public.ensure_monthly_partitions('public.ai_calls', 3);
create index ai_calls_org_idx on public.ai_calls (organization_id, created_at);
create index ai_calls_conn_idx on public.ai_calls (connection_id, created_at);
create index ai_calls_conv_idx on public.ai_calls (conversation_id) where conversation_id is not null;

-- ---------------------------------------------------------------------------
-- Agentes de IA (chat) y recursos conectados
-- ---------------------------------------------------------------------------
create table public.ai_agents (
  id                   bigint generated by default as identity primary key,
  organization_id      bigint not null references public.organizations(id) on delete cascade,
  name                 text not null,
  description          text,
  enabled              boolean not null default true,
  cortex_id            bigint references public.cortexes(id) on delete set null,
  system_prompt        text not null,
  handoff_message      text not null default 'Te comunico con un asesor, en un momento te atiende.',
  use_knowledge        boolean not null default true,
  use_memory           boolean not null default true,
  use_customer_memory  boolean not null default true,
  use_catalog          boolean not null default true,
  use_appointments     boolean not null default true,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),
  unique (organization_id, name)
);
create trigger trg_ai_agents_updated before update on public.ai_agents
  for each row execute function public.set_updated_at();

alter table public.channels add constraint channels_ai_agent_fk
  foreign key (default_ai_agent_id) references public.ai_agents(id) on delete set null;
alter table public.conversations add constraint conversations_ai_agent_fk
  foreign key (ai_agent_id) references public.ai_agents(id) on delete set null;

create table public.knowledge_docs (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  title            text not null,
  content          text not null,
  source_filename  text,
  enabled          boolean not null default true,
  chars            int generated always as (char_length(content)) stored,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create trigger trg_knowledge_docs_updated before update on public.knowledge_docs
  for each row execute function public.set_updated_at();

-- Conocimiento compartido entre agentes
create table public.ai_agent_knowledge (
  ai_agent_id  bigint not null references public.ai_agents(id) on delete cascade,
  doc_id       bigint not null references public.knowledge_docs(id) on delete cascade,
  primary key (ai_agent_id, doc_id)
);
create index ai_agent_knowledge_doc_idx on public.ai_agent_knowledge (doc_id);

-- ---------------------------------------------------------------------------
-- Aprendizaje: memoria del negocio y mejor vendedor
-- ---------------------------------------------------------------------------
create table public.learning_runs (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  type             text not null check (type in ('memory', 'seller')),
  status           text not null default 'running' check (status in ('running', 'done', 'failed')),
  cortex_id        bigint references public.cortexes(id) on delete set null,
  params           jsonb not null default '{}'::jsonb,
  stats            jsonb,
  error            text,
  created_by       bigint references public.agents(id) on delete set null,
  started_at       timestamptz not null default now(),
  finished_at      timestamptz
);
create index learning_runs_org_idx on public.learning_runs (organization_id, type, started_at desc);

create table public.memory_items (
  id                         bigint generated by default as identity primary key,
  organization_id            bigint not null references public.organizations(id) on delete cascade,
  kind                       text not null check (kind in ('faq', 'objection', 'winning_response', 'fact', 'policy', 'insight')),
  title                      text not null,
  content                    text not null,
  status                     text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  source                     text not null default 'learned' check (source in ('learned', 'manual')),
  confidence                 real check (confidence between 0 and 1),
  evidence_conversation_ids  bigint[] not null default '{}',
  run_id                     bigint references public.learning_runs(id) on delete set null,
  reviewed_by                bigint references public.agents(id) on delete set null,
  reviewed_at                timestamptz,
  created_at                 timestamptz not null default now(),
  updated_at                 timestamptz not null default now()
);
create index memory_items_org_status_idx on public.memory_items (organization_id, status, kind);
create unique index memory_items_title_uq on public.memory_items (organization_id, lower(title)) where status <> 'rejected';
create trigger trg_memory_items_updated before update on public.memory_items
  for each row execute function public.set_updated_at();

create table public.seller_profiles (
  id                bigint generated by default as identity primary key,
  organization_id   bigint not null references public.organizations(id) on delete cascade,
  name              text not null,
  status            text not null default 'draft' check (status in ('draft', 'applied', 'archived')),
  source_agent_ids  bigint[] not null default '{}',
  stats             jsonb,
  playbook          jsonb not null,
  system_prompt     text not null,
  ai_agent_id       bigint references public.ai_agents(id) on delete set null,
  run_id            bigint references public.learning_runs(id) on delete set null,
  created_at        timestamptz not null default now()
);
create index seller_profiles_org_idx on public.seller_profiles (organization_id, created_at desc);
