-- =============================================================================
-- 30 · Brechas restantes vs. Atom (docs/data-model.md §19.1)
--
-- Canal de correo (bandeja reenviada / recepción por proveedor, hilos por Message-ID), permisos de llamada para
-- llamadas iniciadas por el asesor (WhatsApp Business Calling exige que el cliente acepte), botón flotante de
-- WhatsApp embebible (uno o varios asesores) y cola de difusión de opciones de enrutamiento de la API.
-- =============================================================================

-- Correo ---------------------------------------------------------------------------------------------------
alter table public.channels drop constraint channels_provider_check;
alter table public.channels add constraint channels_provider_check
  check (provider in ('whatsapp_cloud', 'messenger', 'instagram', 'webchat', 'email'));
-- channels.external_id = dirección de la bandeja (ventas@empresa.com); settings: {inbound: "forward"|"imap"|
-- "provider", inbound_address (alias único de reenvío), smtp/imap host/port/user (secretos en Vault vía
-- settings.*_secret_id), signature_html, assign_to_group_id, auto_reply}

alter table public.contact_identities drop constraint contact_identities_provider_check;
alter table public.contact_identities add constraint contact_identities_provider_check
  check (provider in ('whatsapp_cloud', 'messenger', 'instagram', 'webchat', 'email'));

-- Hilos: Message-ID / In-Reply-To / References → conversación
create table public.email_threads (
  id                 bigint generated by default as identity primary key,
  organization_id    bigint not null references public.organizations(id) on delete cascade,
  channel_id         bigint not null references public.channels(id) on delete cascade,
  conversation_id    bigint not null references public.conversations(id) on delete cascade,
  message_id_header  text not null,             -- <...@...> normalizado sin <>
  subject            text,
  created_at         timestamptz not null default now(),
  unique (channel_id, message_id_header)
);
create index email_threads_conv_idx on public.email_threads (conversation_id);

-- Encabezados y cuerpo HTML del correo van en messages.metadata ({subject, from, to, cc, message_id, in_reply_to,
-- references, html_path}) y el HTML en Storage; el texto plano en messages.text. Recepción cruda en inbound_events.
alter table public.inbound_events drop constraint if exists inbound_events_source_check;
alter table public.inbound_events add constraint inbound_events_source_check check (source in
  ('whatsapp', 'messenger', 'instagram', 'flow_webhook', 'catalog_feed', 'hubspot', 'salesforce', 'stripe', 'email'));

alter table public.messages drop constraint messages_type_check;
alter table public.messages add constraint messages_type_check check (type in
  ('text', 'image', 'audio', 'video', 'document', 'sticker', 'location', 'interactive', 'contacts', 'template',
   'product', 'unsupported', 'call', 'order', 'email'));

-- Llamadas iniciadas por el asesor: permiso del cliente -----------------------------------------------------
create table public.call_permissions (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  channel_id       bigint not null references public.channels(id) on delete cascade,
  contact_id       bigint not null references public.contacts(id) on delete cascade,
  status           text not null default 'requested' check (status in ('requested', 'granted', 'denied', 'expired', 'revoked')),
  permanent        boolean not null default false,   -- el cliente aceptó "siempre"
  requested_by     bigint references public.agents(id) on delete set null,
  request_message_id text,                         -- wamid de la solicitud
  requested_at     timestamptz not null default now(),
  responded_at     timestamptz,
  expires_at       timestamptz,                     -- permiso temporal (Meta: días)
  created_at       timestamptz not null default now()
);
create index call_permissions_contact_idx on public.call_permissions (channel_id, contact_id, requested_at desc);

alter table public.calls add column initiated_by_agent_id bigint references public.agents(id) on delete set null;

-- Botón flotante de WhatsApp embebible -----------------------------------------------------------------------
create table public.wa_widgets (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  name             text not null,
  key              text not null unique,             -- /b/{key}.js
  -- {mode: "single"|"multi", agents: [{name, role, photo_url, channel_id?, link_id?, prefill?, hours?}],
  --  button: {text, color, position, icon}, greeting, show_on: {paths_include[], paths_exclude[], delay_s, mobile,
  --  desktop}, allowed_domains[]}
  config           jsonb not null default '{}'::jsonb,
  link_id          bigint references public.wa_links(id) on delete set null,   -- atribución por defecto
  is_active        boolean not null default true,
  impressions      bigint not null default 0,
  clicks           bigint not null default 0,
  created_by       bigint references public.agents(id) on delete set null,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create trigger trg_wa_widgets_updated before update on public.wa_widgets
  for each row execute function public.set_updated_at();

-- RLS
alter table public.email_threads enable row level security;
alter table public.call_permissions enable row level security;
alter table public.wa_widgets enable row level security;
do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'auth') then
    execute 'create policy org_read on public.wa_widgets for select to authenticated
             using (organization_id = (select private.current_org_id()))';
  end if;
end $$;
