-- =============================================================================
-- 23 · Registro maestro del cliente ("golden record") y llaves de identificación (docs/data-model.md §15)
--
-- golden_key_types: catálogo de llaves (sistema + propias de la empresa): teléfono, correo, usuario de red,
--   documento de identidad, nombres, apellidos, fecha de nacimiento, dirección, placa, VIN... con su normalizador,
--   si identifica a la persona (sirve para encontrar duplicados), si es dato sensible y si la IA debe extraerla.
-- contact_keys: cada valor capturado, con evidencia (mensaje, conversación, documento), fuente, confianza, rango
--   (principal / secundario) y vigencia. Se va llenando a medida que el chat recibe conversaciones y documentos.
-- contact_golden: el registro agregado por cliente (valores principales + listas), mantenido por trigger; no se
--   muestra en la ficha resumen, se consulta en "Datos maestros", en BI y para generar oportunidades.
-- contact_vehicles: vehículos del cliente (placa + VIN + marca/modelo/año) — base de oportunidades de taller,
--   retoma, seguros. key_extractions: auditoría de cada extracción de IA (conversación o documento).
-- contact_merge_candidates: clientes distintos que comparten una llave identificadora (posible duplicado).
-- =============================================================================

create table public.golden_key_types (
  id               bigint generated by default as identity primary key,
  organization_id  bigint references public.organizations(id) on delete cascade,   -- null = tipo del sistema
  key              text not null check (key ~ '^[a-z][a-z0-9_]{0,49}$'),
  label            text not null,
  normalizer       text not null check (normalizer in
                     ('phone', 'email', 'username', 'document', 'plate', 'vin', 'name', 'date', 'address', 'text')),
  is_identifier    boolean not null default false,   -- identifica a una sola persona (para encontrar duplicados)
  is_sensitive     boolean not null default false,   -- dato personal sensible: se enmascara a asesores
  multi            boolean not null default true,    -- admite varios valores (teléfonos, placas...)
  ai_extract       boolean not null default true,
  ai_hint          text,                             -- guía para la IA (formato, dónde suele aparecer)
  position         int not null default 100,
  archived_at      timestamptz,
  created_at       timestamptz not null default now()
);
create unique index golden_key_types_key_idx on public.golden_key_types (coalesce(organization_id, 0), key);

insert into public.golden_key_types (organization_id, key, label, normalizer, is_identifier, is_sensitive, multi, ai_hint, position) values
  (null, 'phone',       'Teléfono',                 'phone',    true,  false, true,  'Números de teléfono o celular, con indicativo si aparece', 10),
  (null, 'email',       'Correo electrónico',       'email',    true,  false, true,  null, 20),
  (null, 'username',    'Usuario de red social',    'username', true,  false, true,  'Usuario de WhatsApp, Instagram, Facebook, TikTok, X; indicar la red', 30),
  (null, 'document',    'Documento de identidad',   'document', true,  true,  true,  'Tipo (CC, CE, NIT, PAS, TI, RUT, DNI, RFC, CPF...) y número', 40),
  (null, 'first_name',  'Nombres',                  'name',     false, false, false, null, 50),
  (null, 'last_name',   'Apellidos',                'name',     false, false, false, null, 60),
  (null, 'birthdate',   'Fecha de nacimiento',      'date',     false, true,  false, 'Formato AAAA-MM-DD', 70),
  (null, 'address',     'Dirección',                'address',  false, true,  true,  'Dirección con ciudad; tipo: casa, trabajo, envío, facturación', 80),
  (null, 'plate',       'Placa de vehículo',        'plate',    true,  false, true,  'Placa del vehículo (ej. ABC123)', 90),
  (null, 'vin',         'VIN / número de chasis',   'vin',      true,  false, true,  '17 caracteres, sin I, O ni Q', 100),
  (null, 'company',     'Empresa',                  'text',     false, false, true,  'Empresa donde trabaja o razón social', 110),
  (null, 'occupation',  'Ocupación',                'text',     false, false, false, null, 120);

create table public.contact_keys (
  id                bigint generated by default as identity primary key,
  organization_id   bigint not null references public.organizations(id) on delete cascade,
  contact_id        bigint not null references public.contacts(id) on delete cascade,
  key_type          text not null,                  -- golden_key_types.key
  subtype           text,                           -- documento: CC/NIT/PAS…; usuario: instagram/facebook…;
                                                    -- dirección: casa/trabajo/envío; teléfono: móvil/fijo
  value             text not null,                  -- como se capturó
  value_normalized  text not null,                  -- para buscar y cruzar (E.164, minúsculas, placa sin guiones…)
  data              jsonb not null default '{}'::jsonb,   -- dirección estructurada (ciudad, país, geo), etc.
  rank              text not null default 'secondary' check (rank in ('primary', 'secondary')),
  status            text not null default 'active' check (status in ('active', 'superseded', 'rejected')),
  verified          boolean not null default false, -- confirmado por un asesor o por el canal (ej. teléfono de WhatsApp)
  confidence        real check (confidence between 0 and 1),
  source            text not null check (source in
                      ('whatsapp', 'channel', 'ai_conversation', 'ai_document', 'agent', 'import', 'api', 'crm', 'flow', 'form')),
  conversation_id   bigint references public.conversations(id) on delete set null,
  message_id        bigint,                         -- messages es particionada: sin FK
  extraction_id     bigint,                         -- key_extractions.id
  evidence          text,                           -- fragmento del texto o del documento
  seen_count        int not null default 1,
  first_seen_at     timestamptz not null default now(),
  last_seen_at      timestamptz not null default now(),
  created_by        bigint references public.agents(id) on delete set null,
  updated_at        timestamptz not null default now()
);
create unique index contact_keys_value_idx on public.contact_keys
  (contact_id, key_type, coalesce(subtype, ''), value_normalized);
-- Cruce entre clientes: ¿quién más tiene esta placa / documento / correo?
create index contact_keys_lookup_idx on public.contact_keys (organization_id, key_type, value_normalized)
  where status = 'active';
create index contact_keys_contact_idx on public.contact_keys (contact_id, key_type, rank);
-- A lo sumo un valor principal activo por cliente, tipo y subtipo
create unique index contact_keys_primary_idx on public.contact_keys (contact_id, key_type, coalesce(subtype, ''))
  where rank = 'primary' and status = 'active';
create trigger trg_contact_keys_updated before update on public.contact_keys
  for each row execute function public.set_updated_at();

create table public.contact_vehicles (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  contact_id       bigint not null references public.contacts(id) on delete cascade,
  plate            text,                            -- normalizada
  vin              text,
  make             text,
  model            text,
  version          text,
  year             smallint check (year between 1950 and 2100),
  color            text,
  fuel             text,
  mileage_km       int,
  relation         text not null default 'owner' check (relation in ('owner', 'driver', 'interested', 'previous_owner')),
  status           text not null default 'active' check (status in ('active', 'sold', 'inactive')),
  -- vencimientos que generan oportunidades (SOAT, revisión técnico-mecánica, garantía, mantenimiento)
  insurance_due    date,
  inspection_due   date,
  warranty_until   date,
  next_service_at  date,
  source           text not null check (source in ('ai_conversation', 'ai_document', 'agent', 'import', 'api', 'crm', 'flow')),
  confidence       real,
  conversation_id  bigint references public.conversations(id) on delete set null,
  extraction_id    bigint,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  check (plate is not null or vin is not null)
);
create unique index contact_vehicles_plate_idx on public.contact_vehicles (contact_id, plate) where plate is not null;
create unique index contact_vehicles_vin_idx on public.contact_vehicles (contact_id, vin) where vin is not null;
create index contact_vehicles_lookup_plate on public.contact_vehicles (organization_id, plate) where plate is not null;
create index contact_vehicles_lookup_vin on public.contact_vehicles (organization_id, vin) where vin is not null;
create index contact_vehicles_due_idx on public.contact_vehicles (organization_id, insurance_due, inspection_due, next_service_at)
  where status = 'active';
create trigger trg_contact_vehicles_updated before update on public.contact_vehicles
  for each row execute function public.set_updated_at();

-- Oportunidades sobre un vehículo (taller, retoma, seguro)
alter table public.deals add column vehicle_id bigint references public.contact_vehicles(id) on delete set null;
alter table public.deals add column origin text;   -- golden: "soat_due", "inspection_due", "trade_in", ... o null

create table public.key_extractions (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  contact_id       bigint not null references public.contacts(id) on delete cascade,
  conversation_id  bigint references public.conversations(id) on delete set null,
  message_id       bigint,
  source_kind      text not null check (source_kind in ('conversation', 'document', 'image', 'audio')),
  document_type    text,          -- cedula, pasaporte, licencia, tarjeta_propiedad, soat, rtm, factura, rut, otro
  status           text not null default 'pending' check (status in ('pending', 'done', 'failed', 'skipped')),
  extracted        jsonb not null default '{}'::jsonb,   -- salida estructurada de la IA
  keys_added       int not null default 0,
  keys_updated     int not null default 0,
  ai_call_id       bigint,
  error            text,
  created_at       timestamptz not null default now(),
  finished_at      timestamptz
);
create index key_extractions_contact_idx on public.key_extractions (contact_id, created_at desc);
create index key_extractions_pending_idx on public.key_extractions (created_at) where status = 'pending';
-- Un mensaje (documento) se procesa una sola vez
create unique index key_extractions_message_idx on public.key_extractions (message_id, source_kind) where message_id is not null;

create table public.contact_merge_candidates (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  contact_a_id     bigint not null references public.contacts(id) on delete cascade,
  contact_b_id     bigint not null references public.contacts(id) on delete cascade,
  matched          jsonb not null,                 -- [{key_type, value_normalized}]
  score            real not null,                  -- 0..1 (documento/correo pesan más que placa/VIN)
  status           text not null default 'pending' check (status in ('pending', 'merged', 'dismissed')),
  decided_by       bigint references public.agents(id) on delete set null,
  decided_at       timestamptz,
  created_at       timestamptz not null default now(),
  check (contact_a_id < contact_b_id)
);
create unique index contact_merge_candidates_pair_idx on public.contact_merge_candidates (contact_a_id, contact_b_id);
create index contact_merge_candidates_pending_idx on public.contact_merge_candidates (organization_id, score desc)
  where status = 'pending';

-- Registro agregado por cliente ---------------------------------------------------------------------------
create table public.contact_golden (
  contact_id        bigint primary key references public.contacts(id) on delete cascade,
  organization_id   bigint not null references public.organizations(id) on delete cascade,
  first_name        text,
  last_name         text,
  full_name         text,
  primary_phone     text,
  phones            text[] not null default '{}',
  primary_email     text,
  emails            text[] not null default '{}',
  usernames         jsonb not null default '[]'::jsonb,   -- [{network, username}]
  document_type     text,
  document_number   text,
  birthdate         date,
  addresses         jsonb not null default '[]'::jsonb,   -- [{type, value, city, country}]
  plates            text[] not null default '{}',
  vins              text[] not null default '{}',
  extra             jsonb not null default '{}'::jsonb,   -- llaves propias de la empresa {key: [values]}
  completeness_pct  smallint not null default 0,          -- llaves principales presentes / esperadas
  keys_count        int not null default 0,
  updated_at        timestamptz not null default now()
);
create index contact_golden_org_idx on public.contact_golden (organization_id, completeness_pct);
create index contact_golden_doc_idx on public.contact_golden (organization_id, document_number) where document_number is not null;
create index contact_golden_plates_idx on public.contact_golden using gin (plates);
create index contact_golden_vins_idx on public.contact_golden using gin (vins);
create index contact_golden_emails_idx on public.contact_golden using gin (emails);
create index contact_golden_phones_idx on public.contact_golden using gin (phones);

create or replace function private.refresh_contact_golden(p_contact bigint) returns void
language plpgsql set search_path = public, pg_temp as $$
declare
  v_org bigint;
begin
  select organization_id into v_org from public.contacts where id = p_contact;
  if v_org is null then
    return;
  end if;
  insert into public.contact_golden as g (contact_id, organization_id, first_name, last_name, full_name, primary_phone,
      phones, primary_email, emails, usernames, document_type, document_number, birthdate, addresses, plates, vins,
      extra, completeness_pct, keys_count, updated_at)
  select p_contact, v_org,
    (array_agg(k.value order by (k.rank = 'primary') desc, k.confidence desc nulls last, k.last_seen_at desc)
       filter (where k.key_type = 'first_name'))[1],
    (array_agg(k.value order by (k.rank = 'primary') desc, k.confidence desc nulls last, k.last_seen_at desc)
       filter (where k.key_type = 'last_name'))[1],
    nullif(trim(concat_ws(' ',
      (array_agg(k.value order by (k.rank = 'primary') desc, k.last_seen_at desc) filter (where k.key_type = 'first_name'))[1],
      (array_agg(k.value order by (k.rank = 'primary') desc, k.last_seen_at desc) filter (where k.key_type = 'last_name'))[1])), ''),
    (array_agg(k.value_normalized order by (k.rank = 'primary') desc, k.verified desc, k.last_seen_at desc)
       filter (where k.key_type = 'phone'))[1],
    coalesce(array_agg(distinct k.value_normalized) filter (where k.key_type = 'phone'), '{}'),
    (array_agg(k.value_normalized order by (k.rank = 'primary') desc, k.verified desc, k.last_seen_at desc)
       filter (where k.key_type = 'email'))[1],
    coalesce(array_agg(distinct k.value_normalized) filter (where k.key_type = 'email'), '{}'),
    coalesce(jsonb_agg(distinct jsonb_build_object('network', k.subtype, 'username', k.value_normalized))
       filter (where k.key_type = 'username'), '[]'),
    (array_agg(k.subtype order by (k.rank = 'primary') desc, k.verified desc, k.last_seen_at desc)
       filter (where k.key_type = 'document'))[1],
    (array_agg(k.value_normalized order by (k.rank = 'primary') desc, k.verified desc, k.last_seen_at desc)
       filter (where k.key_type = 'document'))[1],
    (array_agg(k.value_normalized order by (k.rank = 'primary') desc, k.confidence desc nulls last)
       filter (where k.key_type = 'birthdate' and k.value_normalized ~ '^\d{4}-\d{2}-\d{2}$'))[1]::date,
    coalesce(jsonb_agg(distinct jsonb_build_object('type', k.subtype, 'value', k.value) || k.data)
       filter (where k.key_type = 'address'), '[]'),
    coalesce(array_agg(distinct k.value_normalized) filter (where k.key_type = 'plate'), '{}'),
    coalesce(array_agg(distinct k.value_normalized) filter (where k.key_type = 'vin'), '{}'),
    coalesce((select jsonb_object_agg(x.key_type, x.vals) from (
        select k2.key_type, jsonb_agg(distinct k2.value) as vals from public.contact_keys k2
        where k2.contact_id = p_contact and k2.status = 'active' and k2.key_type not in
          ('phone', 'email', 'username', 'document', 'first_name', 'last_name', 'birthdate', 'address', 'plate', 'vin')
        group by k2.key_type) x), '{}'),
    -- completitud: nombres, apellidos, teléfono, correo, documento, fecha de nacimiento, dirección (7 llaves base)
    (100 * (
      (count(*) filter (where k.key_type = 'first_name') > 0)::int +
      (count(*) filter (where k.key_type = 'last_name') > 0)::int +
      (count(*) filter (where k.key_type = 'phone') > 0)::int +
      (count(*) filter (where k.key_type = 'email') > 0)::int +
      (count(*) filter (where k.key_type = 'document') > 0)::int +
      (count(*) filter (where k.key_type = 'birthdate') > 0)::int +
      (count(*) filter (where k.key_type = 'address') > 0)::int) / 7)::smallint,
    count(*), now()
  from public.contact_keys k
  where k.contact_id = p_contact and k.status = 'active'
  on conflict (contact_id) do update set
    first_name = excluded.first_name, last_name = excluded.last_name, full_name = excluded.full_name,
    primary_phone = excluded.primary_phone, phones = excluded.phones, primary_email = excluded.primary_email,
    emails = excluded.emails, usernames = excluded.usernames, document_type = excluded.document_type,
    document_number = excluded.document_number, birthdate = excluded.birthdate, addresses = excluded.addresses,
    plates = excluded.plates, vins = excluded.vins, extra = excluded.extra, completeness_pct = excluded.completeness_pct,
    keys_count = excluded.keys_count, updated_at = now();
end $$;
revoke all on function private.refresh_contact_golden(bigint) from public;

create or replace function private.trg_contact_keys_golden() returns trigger
language plpgsql set search_path = public, pg_temp as $$
begin
  perform private.refresh_contact_golden(coalesce(new.contact_id, old.contact_id));
  if tg_op = 'UPDATE' and new.contact_id is distinct from old.contact_id then
    perform private.refresh_contact_golden(old.contact_id);
  end if;
  return null;
end $$;
revoke all on function private.trg_contact_keys_golden() from public;
create trigger trg_contact_keys_golden after insert or update or delete on public.contact_keys
  for each row execute function private.trg_contact_keys_golden();

-- Datos del canal → llaves (teléfono y @usuario de WhatsApp verificados por el canal; correo escrito en la ficha)
create or replace function private.trg_contacts_golden_keys() returns trigger
language plpgsql set search_path = public, pg_temp as $$
begin
  if new.wa_id is not null and (tg_op = 'INSERT' or new.wa_id is distinct from old.wa_id) then
    insert into public.contact_keys (organization_id, contact_id, key_type, subtype, value, value_normalized, rank,
                                     verified, confidence, source)
    values (new.organization_id, new.id, 'phone', 'whatsapp', new.wa_id, new.wa_id,
            case when exists (select 1 from public.contact_keys where contact_id = new.id and key_type = 'phone'
                              and coalesce(subtype, '') = 'whatsapp' and rank = 'primary' and status = 'active')
                 then 'secondary' else 'primary' end, true, 1, 'whatsapp')
    on conflict (contact_id, key_type, coalesce(subtype, ''), value_normalized)
      do update set verified = true, last_seen_at = now(), seen_count = public.contact_keys.seen_count + 1;
  end if;
  if new.wa_username is not null and (tg_op = 'INSERT' or new.wa_username is distinct from old.wa_username) then
    insert into public.contact_keys (organization_id, contact_id, key_type, subtype, value, value_normalized, rank,
                                     verified, confidence, source)
    values (new.organization_id, new.id, 'username', 'whatsapp', new.wa_username, lower(new.wa_username), 'secondary',
            true, 1, 'whatsapp')
    on conflict (contact_id, key_type, coalesce(subtype, ''), value_normalized) do update set last_seen_at = now();
  end if;
  if new.email is not null and (tg_op = 'INSERT' or new.email is distinct from old.email) then
    insert into public.contact_keys (organization_id, contact_id, key_type, value, value_normalized, rank, confidence,
                                     source)
    values (new.organization_id, new.id, 'email', new.email, lower(new.email), 'secondary', 0.9, 'agent')
    on conflict (contact_id, key_type, coalesce(subtype, ''), value_normalized) do update set last_seen_at = now();
  end if;
  return null;
end $$;
revoke all on function private.trg_contacts_golden_keys() from public;
create trigger trg_contacts_golden_keys after insert or update of wa_id, wa_username, email on public.contacts
  for each row execute function private.trg_contacts_golden_keys();

-- Las llaves que ya conocemos: teléfono de WhatsApp (verificado por el canal), correo, @usuario, nombre
insert into public.contact_keys (organization_id, contact_id, key_type, subtype, value, value_normalized, rank, verified,
                                 confidence, source)
select organization_id, id, 'phone', 'whatsapp', wa_id, wa_id, 'primary', true, 1, 'whatsapp'
from public.contacts where wa_id is not null
on conflict do nothing;
insert into public.contact_keys (organization_id, contact_id, key_type, value, value_normalized, rank, confidence, source)
select organization_id, id, 'email', email, lower(email), 'primary', 0.9, 'agent'
from public.contacts where email is not null
on conflict do nothing;
insert into public.contact_keys (organization_id, contact_id, key_type, subtype, value, value_normalized, rank, verified,
                                 confidence, source)
select organization_id, id, 'username', 'whatsapp', wa_username, lower(wa_username), 'primary', true, 1, 'whatsapp'
from public.contacts where wa_username is not null
on conflict do nothing;
insert into public.contact_keys (organization_id, contact_id, key_type, subtype, value, value_normalized, rank, verified,
                                 confidence, source)
select i.organization_id, i.contact_id, 'username', i.provider, i.username, lower(i.username), 'secondary', true, 1, 'channel'
from public.contact_identities i where i.username is not null and i.provider <> 'whatsapp_cloud'
on conflict do nothing;

-- BI: completitud del registro maestro y cobertura por llave
create or replace view reporting.v_golden_coverage as
select g.organization_id, count(*) as contacts,
       round(avg(g.completeness_pct), 1) as avg_completeness,
       count(*) filter (where g.document_number is not null) as with_document,
       count(*) filter (where g.primary_email is not null) as with_email,
       count(*) filter (where g.birthdate is not null) as with_birthdate,
       count(*) filter (where jsonb_array_length(g.addresses) > 0) as with_address,
       count(*) filter (where cardinality(g.plates) > 0 or cardinality(g.vins) > 0) as with_vehicle,
       count(*) filter (where cardinality(g.phones) > 1) as with_secondary_phone
from public.contact_golden g group by g.organization_id;

-- RLS: el registro maestro tiene datos sensibles → solo el backend (que enmascara según el rol)
alter table public.golden_key_types enable row level security;
alter table public.contact_keys enable row level security;
alter table public.contact_vehicles enable row level security;
alter table public.key_extractions enable row level security;
alter table public.contact_merge_candidates enable row level security;
alter table public.contact_golden enable row level security;
do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'auth') then
    execute 'create policy read_types on public.golden_key_types for select to authenticated
             using (organization_id is null or organization_id = private.current_org_id())';
  end if;
end $$;

-- =============================================================================
-- Organización de campos: secciones, alcance, destino en el registro maestro y alias
-- (consolida fichas con decenas de campos sueltos y duplicados: Placa / Numero_placa / C_taller_placa…)
-- =============================================================================
alter table public.contact_fields drop constraint contact_fields_type_check;
alter table public.contact_fields add constraint contact_fields_type_check check (type in
  ('text', 'long_text', 'number', 'currency', 'date', 'datetime', 'select', 'boolean', 'email', 'phone'));
alter table public.contact_fields
  add column section       text not null default 'General',  -- Identidad, Vehículo, Nuevos, Usados, Taller, PQR…
  -- dónde vive el valor: el cliente, una oportunidad de una línea de negocio, un vehículo, una cita o el flujo
  add column scope         text not null default 'contact'
                             check (scope in ('contact', 'deal', 'vehicle', 'appointment', 'flow')),
  add column pipeline      text,                             -- scope = deal: línea (nuevos, usados, taller…)
  -- destino canónico: tipo de llave del registro maestro ("document", "plate"…) o atributo ("vehicle.mileage_km",
  -- "consent.habeas_data", "deal.amount"); los alias apuntan al mismo destino
  add column maps_to       text,
  add column aliases       text[] not null default '{}',    -- nombres anteriores (Atom, bots, CRM, importaciones)
  add column show_in_card  boolean not null default false,  -- aparece en la ficha resumen
  add column currency      char(3),                          -- type = currency
  add check (scope <> 'deal' or pipeline is not null);
create index contact_fields_aliases_idx on public.contact_fields using gin (aliases);
-- Los campos existentes siguen visibles en la ficha hasta que se reorganicen
update public.contact_fields set show_in_card = true;

-- Atributos de calificación de una oportunidad por línea de negocio (modelo de interés, transmisión, forma de pago,
-- tiempo de compra, presupuesto, test drive…) y temperatura del lead
alter table public.deals
  add column attributes      jsonb not null default '{}'::jsonb,
  add column interest_level  text check (interest_level in ('hot', 'warm', 'cold'));
create index deals_pipeline_idx on public.deals (organization_id, pipeline, status, updated_at desc);

-- Atributos adicionales del vehículo (línea, transmisión, tipo, almacén/sede…)
alter table public.contact_vehicles add column attributes jsonb not null default '{}'::jsonb;

-- Consentimientos (habeas data, términos y condiciones, marketing): con evidencia, por canal ------------------
create table public.contact_consents (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  contact_id       bigint not null references public.contacts(id) on delete cascade,
  consent_type     text not null,               -- habeas_data, terms, marketing, data_sharing, call_recording…
  granted          boolean not null,
  policy_version   text,                        -- versión del texto aceptado
  channel_id       bigint references public.channels(id) on delete set null,
  conversation_id  bigint references public.conversations(id) on delete set null,
  message_id       bigint,                      -- respuesta del cliente (evidencia)
  evidence         text,                        -- texto mostrado / respuesta
  source           text not null check (source in ('whatsapp', 'flow', 'agent', 'form', 'import', 'api', 'ai')),
  recorded_by      bigint references public.agents(id) on delete set null,
  recorded_at      timestamptz not null default now(),
  revoked_at       timestamptz
);
create index contact_consents_contact_idx on public.contact_consents (contact_id, consent_type, recorded_at desc);
create index contact_consents_org_idx on public.contact_consents (organization_id, consent_type, granted);
-- Estado vigente por tipo (el último registro sin revocar)
create or replace view reporting.v_contact_consents as
select distinct on (c.contact_id, c.consent_type) c.organization_id, c.contact_id, c.consent_type, c.granted,
       c.policy_version, c.recorded_at, c.source
from public.contact_consents c
where c.revoked_at is null
order by c.contact_id, c.consent_type, c.recorded_at desc;

alter table public.contact_consents enable row level security;
