-- =============================================================================
-- 07 · Operación: seguimiento, citas, respuestas rápidas, recursos, integraciones,
--      webhooks salientes, eventos crudos de entrada y alertas
-- =============================================================================

create table public.followups (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  contact_id       bigint not null references public.contacts(id) on delete cascade,
  conversation_id  bigint references public.conversations(id) on delete set null,
  agent_id         bigint not null references public.agents(id) on delete cascade,
  due_at           timestamptz not null,
  note             text not null,
  done_at          timestamptz,
  created_at       timestamptz not null default now()
);
create index followups_agent_pending_idx on public.followups (organization_id, agent_id, due_at) where done_at is null;
create index followups_contact_idx on public.followups (contact_id);

create table public.appointments (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  contact_id       bigint not null references public.contacts(id) on delete cascade,
  conversation_id  bigint references public.conversations(id) on delete set null,
  agent_id         bigint references public.agents(id) on delete set null,
  starts_at        timestamptz not null,
  duration_min     int not null default 30 check (duration_min between 5 and 1440),
  title            text not null,
  notes            text,
  status           text not null default 'scheduled' check (status in ('scheduled', 'done', 'cancelled', 'no_show')),
  created_by_type  text not null default 'agent' check (created_by_type in ('bot', 'agent', 'flow')),
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now()
);
create index appointments_org_start_idx on public.appointments (organization_id, starts_at) where status = 'scheduled';
create index appointments_contact_idx on public.appointments (contact_id, starts_at desc);
create trigger trg_appointments_updated before update on public.appointments
  for each row execute function public.set_updated_at();

create table public.quick_replies (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  shortcut         text not null check (shortcut ~ '^[a-z0-9_-]{1,50}$'),
  text             text not null,
  unique (organization_id, shortcut)
);

create table public.resources (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  name             text not null,
  storage_path     text not null,               -- bucket/ruta en Supabase Storage
  mime             text not null,
  size_bytes       int not null check (size_bytes <= 16 * 1024 * 1024),
  created_by       bigint references public.agents(id) on delete set null,
  created_at       timestamptz not null default now()
);

create table public.integrations (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  key              text not null check (key in ('hubspot', 'salesforce', 'google_ads', 'meta_ads', 'zapier')),
  connected        boolean not null default false,
  config           jsonb not null default '{}'::jsonb,
  secret_id        uuid,                        -- vault
  last_sync_at     timestamptz,
  last_error       text,
  unique (organization_id, key)
);

create table public.outbound_webhooks (
  id                    bigint generated by default as identity primary key,
  organization_id       bigint not null references public.organizations(id) on delete cascade,
  name                  text not null,
  url                   text not null check (url ~ '^https://'),
  signing_secret_id     uuid,                   -- vault; el secreto firma X-Signature-256
  events                text[] not null default '{}',   -- vacío = todos
  active                boolean not null default true,
  consecutive_failures  int not null default 0,
  last_status           int,
  last_error            text,
  last_delivery_at      timestamptz,
  created_at            timestamptz not null default now()
);

create table public.webhook_deliveries (
  id            bigint generated by default as identity,
  webhook_id    bigint not null,
  event         text not null,
  status_code   int,
  latency_ms    int,
  error         text,
  attempt       smallint not null default 1,
  created_at    timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);
create table public.webhook_deliveries_default partition of public.webhook_deliveries default;
select public.ensure_monthly_partitions('public.webhook_deliveries', 3);
create index webhook_deliveries_hook_idx on public.webhook_deliveries (webhook_id, created_at desc);

-- Payloads crudos de Meta (retención corta): reprocesar y auditar
create table public.inbound_events (
  id               bigint generated by default as identity,
  organization_id  bigint,
  source           text not null default 'whatsapp' check (source in ('whatsapp', 'flow_webhook', 'catalog_feed')),
  payload          jsonb not null,
  processed_at     timestamptz,
  error            text,
  received_at      timestamptz not null default now(),
  primary key (id, received_at)
) partition by range (received_at);
create table public.inbound_events_default partition of public.inbound_events default;
select public.ensure_monthly_partitions('public.inbound_events', 2);
create index inbound_events_unprocessed_idx on public.inbound_events (received_at) where processed_at is null;

create table public.alerts (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  severity         text not null default 'warning' check (severity in ('info', 'warning', 'critical')),
  layer            text not null check (layer in ('contact', 'template', 'account', 'phone', 'campaign', 'webhook', 'ai', 'catalog')),
  source           text not null default 'meta' check (source in ('meta', 'system')),
  title            text not null,
  description      text,
  ref              text,
  resolved_at      timestamptz,
  resolved_by      bigint references public.agents(id) on delete set null,
  created_at       timestamptz not null default now()
);
create index alerts_open_idx on public.alerts (organization_id, created_at desc) where resolved_at is null;
