-- =============================================================================
-- 05 · Catálogo de productos, plantillas de WhatsApp y campañas
-- =============================================================================

create table public.products (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  sku              text not null,               -- = retailer_id en el catálogo de Meta
  name             text not null,
  description      text,
  category         text,
  brand            text,
  price            numeric(14, 2) check (price >= 0),
  sale_price       numeric(14, 2) check (sale_price >= 0),
  currency         char(3) not null default 'COP',
  stock            int,
  available        boolean not null default true,
  url              text,
  image_url        text,
  attributes       jsonb,                       -- año, color, km, versión...
  source           text not null default 'manual' check (source in ('manual', 'import', 'meta', 'feed', 'api')),
  in_meta_catalog  boolean not null default false,
  search           tsvector generated always as (
                     setweight(to_tsvector('spanish', coalesce(name, '')), 'A') ||
                     setweight(to_tsvector('spanish', coalesce(brand, '') || ' ' || coalesce(category, '') || ' ' || sku), 'B') ||
                     setweight(to_tsvector('spanish', coalesce(description, '')), 'C')
                   ) stored,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (organization_id, sku)
);
create index products_search_idx on public.products using gin (search);
create index products_name_trgm on public.products using gin (name gin_trgm_ops);
create index products_attrs_idx on public.products using gin (attributes jsonb_path_ops);
create index products_org_cat_idx on public.products (organization_id, category, price) where available;
create trigger trg_products_updated before update on public.products
  for each row execute function public.set_updated_at();

create table public.catalog_sync_runs (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  source           text not null check (source in ('import', 'meta', 'feed', 'api')),
  status           text not null default 'running' check (status in ('running', 'done', 'failed')),
  stats            jsonb,                       -- created, updated, invalid, disabled
  error            text,
  created_by       bigint references public.agents(id) on delete set null,
  started_at       timestamptz not null default now(),
  finished_at      timestamptz
);
create index catalog_sync_runs_org_idx on public.catalog_sync_runs (organization_id, started_at desc);

-- Copia sincronizada de las plantillas aprobadas en Meta
create table public.wa_templates (
  id                bigint generated by default as identity primary key,
  organization_id   bigint not null references public.organizations(id) on delete cascade,
  waba_id           text not null,
  name              text not null,
  language          text not null,
  category          text,                       -- MARKETING | UTILITY | AUTHENTICATION
  status            text,                       -- APPROVED | PAUSED | REJECTED ...
  quality           text,
  parameter_format  text,
  components        jsonb not null,
  synced_at         timestamptz not null default now(),
  unique (organization_id, waba_id, name, language)
);

create table public.campaigns (
  id                 bigint generated by default as identity primary key,
  organization_id    bigint not null references public.organizations(id) on delete cascade,
  channel_id         bigint not null references public.channels(id),
  name               text not null,
  template_name      text not null,
  template_language  text not null,
  params             jsonb not null default '[]'::jsonb,   -- admite {{nombre}}
  audience           jsonb not null,             -- {"tag_ids": [...]} | {"phones": [...]} | {"filter": {...}}
  status             text not null default 'draft'
                       check (status in ('draft', 'scheduled', 'running', 'done', 'failed', 'cancelled')),
  scheduled_at       timestamptz,
  created_by         bigint references public.agents(id) on delete set null,
  created_at         timestamptz not null default now(),
  started_at         timestamptz,
  finished_at        timestamptz,
  check (status <> 'scheduled' or scheduled_at is not null)
);
create index campaigns_org_created_idx on public.campaigns (organization_id, created_at desc);
create index campaigns_scheduled_idx on public.campaigns (scheduled_at) where status = 'scheduled';

create table public.campaign_recipients (
  id             bigint generated by default as identity primary key,
  campaign_id    bigint not null references public.campaigns(id) on delete cascade,
  contact_id     bigint not null references public.contacts(id) on delete cascade,
  status         text not null default 'pending' check (status in ('pending', 'skipped', 'sent', 'delivered', 'read', 'failed')),
  wa_message_id  text,
  error_code     int,
  error          text,
  sent_at        timestamptz,
  delivered_at   timestamptz,
  read_at        timestamptz,
  failed_at      timestamptz,
  unique (campaign_id, contact_id)
);
create index campaign_recipients_status_idx on public.campaign_recipients (campaign_id, status);
create index campaign_recipients_wa_idx on public.campaign_recipients (wa_message_id) where wa_message_id is not null;

alter table public.messages add constraint messages_campaign_fk
  foreign key (campaign_id) references public.campaigns(id) on delete set null;
