-- =============================================================================
-- 34 · Segmentos dinámicos y journeys de marketing (docs/data-model.md §21.1)
--
-- segments: reglas sobre cliente 360 + llaves maestras + vehículos + consentimientos + fuente (dinámicos) o lista
-- fija (estáticos). journeys: recorridos de varios pasos por WhatsApp / correo / chat web con esperas, ramas,
-- A/B, límites de frecuencia y horas de silencio; cada cliente inscrito avanza con su propio estado.
-- =============================================================================

create table public.segments (
  id                bigint generated by default as identity primary key,
  organization_id   bigint not null references public.organizations(id) on delete cascade,
  name              text not null,
  description       text,
  kind              text not null default 'dynamic' check (kind in ('dynamic', 'static')),
  -- Árbol de reglas validado (JSON Schema en la app): {"all": [{"field": "golden.vehicle.insurance_due",
  -- "op": "within_days", "value": 30}, {"field": "consent.marketing", "op": "eq", "value": true}]}
  definition        jsonb not null default '{}'::jsonb,
  member_count      int not null default 0,
  last_computed_at  timestamptz,
  refresh_minutes   int not null default 60 check (refresh_minutes between 5 and 10080),
  created_by        bigint references public.agents(id) on delete set null,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (organization_id, name)
);
create trigger trg_segments_updated before update on public.segments
  for each row execute function public.set_updated_at();

-- Miembros materializados (estáticos y la última evaluación de los dinámicos: permite "entró al segmento")
create table public.segment_members (
  segment_id   bigint not null references public.segments(id) on delete cascade,
  contact_id   bigint not null references public.contacts(id) on delete cascade,
  added_at     timestamptz not null default now(),
  primary key (segment_id, contact_id)
);
create index segment_members_contact_idx on public.segment_members (contact_id);

create table public.journeys (
  id                bigint generated by default as identity primary key,
  organization_id   bigint not null references public.organizations(id) on delete cascade,
  name              text not null,
  description       text,
  status            text not null default 'draft' check (status in ('draft', 'active', 'paused', 'archived')),
  -- Entrada: {type: segment_enter|segment_member|event|date_field|manual|api, segment_id?, event?, field?,
  --           offset_days?, at_time?}
  entry             jsonb not null default '{}'::jsonb,
  current_version_id bigint,
  -- Reglas: {reentry: never|after_days|always, reentry_days?, frequency_cap: {per_day, per_week},
  --          quiet_hours: {from, to, timezone}, channels_priority: [whatsapp_cloud, email, webchat],
  --          require_consent: marketing, goal: {event: replied|deal_won|appointment_booked|purchase|stage, window_days}}
  settings          jsonb not null default '{}'::jsonb,
  created_by        bigint references public.agents(id) on delete set null,
  published_at      timestamptz,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (organization_id, name)
);
create trigger trg_journeys_updated before update on public.journeys
  for each row execute function public.set_updated_at();

create table public.journey_versions (
  id           bigint generated by default as identity primary key,
  journey_id   bigint not null references public.journeys(id) on delete cascade,
  version      int not null,
  -- Grafo: {steps: [{id, type: send_template|send_email|send_text|wait|wait_until|branch|split|update_contact|
  --          add_tag|create_deal|move_stage|notify_agent|start_flow|exit, config, next | branches{...}}]}
  definition   jsonb not null,
  change_note  text,
  created_by   bigint references public.agents(id) on delete set null,
  created_at   timestamptz not null default now(),
  unique (journey_id, version)
);
alter table public.journeys add constraint journeys_current_version_fk
  foreign key (current_version_id) references public.journey_versions(id) on delete set null;

create table public.journey_enrollments (
  id               bigint generated by default as identity,
  organization_id  bigint not null,
  journey_id       bigint not null,
  version_id       bigint not null,
  contact_id       bigint not null,
  status           text not null default 'active' check (status in ('active', 'waiting', 'completed', 'goal_met', 'exited', 'failed')),
  current_step     text,
  next_run_at      timestamptz,
  variant          text,                         -- rama A/B asignada (estable por inscripción)
  context          jsonb not null default '{}'::jsonb,
  exit_reason      text,
  enrolled_at      timestamptz not null default now(),
  finished_at      timestamptz,
  primary key (id, enrolled_at)
) partition by range (enrolled_at);
create table public.journey_enrollments_default partition of public.journey_enrollments default;
select public.ensure_monthly_partitions('public.journey_enrollments', 3);
create index journey_enrollments_due_idx on public.journey_enrollments (next_run_at) where status in ('active', 'waiting');
create index journey_enrollments_contact_idx on public.journey_enrollments (contact_id, journey_id);
create index journey_enrollments_journey_idx on public.journey_enrollments (journey_id, status);

create table public.journey_events (
  id               bigint generated by default as identity,
  organization_id  bigint not null,
  journey_id       bigint not null,
  enrollment_id    bigint not null,
  contact_id       bigint not null,
  step_id          text not null,
  variant          text,
  kind             text not null check (kind in ('entered', 'sent', 'delivered', 'read', 'replied', 'clicked', 'failed',
                                                 'skipped', 'branched', 'waited', 'goal_met', 'exited', 'completed')),
  message_id       bigint,
  data             jsonb not null default '{}'::jsonb,
  created_at       timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);
create table public.journey_events_default partition of public.journey_events default;
select public.ensure_monthly_partitions('public.journey_events', 3);
create index journey_events_enrollment_idx on public.journey_events (enrollment_id, created_at);
create index journey_events_journey_idx on public.journey_events (journey_id, created_at);
create index journey_events_message_idx on public.journey_events (message_id) where message_id is not null;

-- Mensajes enviados por un journey (para estados entregado/leído/respondido y límites de frecuencia)
alter table public.messages drop constraint messages_sender_type_check;
alter table public.messages add constraint messages_sender_type_check
  check (sender_type in ('contact', 'bot', 'agent', 'campaign', 'flow', 'system', 'journey'));
alter table public.messages add column journey_id bigint;

-- Reporting
create table reporting.daily_journeys (
  organization_id  bigint not null,
  day              date not null,
  journey_id       bigint not null,
  step_id          text not null,
  variant          text not null default '',
  entered          int not null default 0,
  sent             int not null default 0,
  delivered        int not null default 0,
  read             int not null default 0,
  replied          int not null default 0,
  clicked          int not null default 0,
  failed           int not null default 0,
  goal_met         int not null default 0,
  exited           int not null default 0,
  refreshed_at     timestamptz not null default now(),
  primary key (organization_id, day, journey_id, step_id, variant)
);

create or replace function reporting.refresh_journeys(p_org bigint, p_from date, p_to date) returns void
language plpgsql set search_path = reporting, public, pg_temp as $$
declare
  tz  text := (select timezone from public.organizations where id = p_org);
  lo  timestamptz := (p_from::timestamp at time zone tz);
  hi  timestamptz := ((p_to + 1)::timestamp at time zone tz);
begin
  delete from reporting.daily_journeys where organization_id = p_org and day between p_from and p_to;
  insert into reporting.daily_journeys (organization_id, day, journey_id, step_id, variant, entered, sent, delivered,
      read, replied, clicked, failed, goal_met, exited)
  select p_org, (e.created_at at time zone tz)::date, e.journey_id, e.step_id, coalesce(e.variant, ''),
         count(*) filter (where e.kind = 'entered'), count(*) filter (where e.kind = 'sent'),
         count(*) filter (where e.kind = 'delivered'), count(*) filter (where e.kind = 'read'),
         count(*) filter (where e.kind = 'replied'), count(*) filter (where e.kind = 'clicked'),
         count(*) filter (where e.kind = 'failed'), count(*) filter (where e.kind = 'goal_met'),
         count(*) filter (where e.kind = 'exited')
  from public.journey_events e
  where e.organization_id = p_org and e.created_at >= lo and e.created_at < hi
  group by 2, 3, 4, 5;
end $$;
revoke all on function reporting.refresh_journeys(bigint, date, date) from public;

create or replace function reporting.refresh_range(p_org bigint, p_from date, p_to date) returns void
language plpgsql set search_path = reporting, public, pg_temp as $$
begin
  perform reporting.refresh_core(p_org, p_from, p_to);
  perform reporting.refresh_flows(p_org, p_from, p_to);
  perform reporting.refresh_links(p_org, p_from, p_to);
  perform reporting.refresh_channels(p_org, p_from, p_to);
  perform reporting.refresh_qa(p_org, p_from, p_to);
  perform reporting.refresh_api(p_org, p_from, p_to);
  perform reporting.refresh_products(p_org, p_from, p_to);
  perform reporting.refresh_ads(p_org, p_from, p_to);
  perform reporting.refresh_service(p_org, p_from, p_to);
  perform reporting.refresh_copilot(p_org, p_from, p_to);
  perform reporting.refresh_journeys(p_org, p_from, p_to);
end $$;

do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('journeys-partitions', '50 3 * * *', $c$
      select public.ensure_monthly_partitions('public.journey_enrollments', 3);
      select public.ensure_monthly_partitions('public.journey_events', 3);
      select public.drop_old_partitions('public.journey_events', 13);
    $c$);
  end if;
end $$;

alter table public.segments enable row level security;
alter table public.segment_members enable row level security;
alter table public.journeys enable row level security;
alter table public.journey_versions enable row level security;
alter table public.journey_enrollments enable row level security;
alter table public.journey_events enable row level security;
do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'auth') then
    execute 'create policy org_read on public.segments for select to authenticated
             using (organization_id = (select private.current_org_id()))';
    execute 'create policy org_read on public.journeys for select to authenticated
             using (organization_id = (select private.current_org_id()))';
  end if;
end $$;
