-- =============================================================================
-- 14 · SaaS multiempresa: planes, suscripciones, consumo, límites y back-office
-- Ver docs/data-model.md §10.4
-- =============================================================================

create table public.plans (
  id                  bigint generated by default as identity primary key,
  key                 text not null unique check (key ~ '^[a-z][a-z0-9_]{1,30}$'),
  name                text not null,
  description         text,
  price_month_usd     numeric(10, 2) not null default 0,
  -- null = ilimitado
  limits              jsonb not null default '{}'::jsonb,
    -- {"channels","users","ai_agents","flows","conversations_month","voice_minutes_month","campaign_recipients_month"}
  features            jsonb not null default '{}'::jsonb,
    -- {"flows","voice","crm","attribution","api","seller","memory"} → true/false
  provider_price_id   text,          -- Stripe price id
  is_public           boolean not null default true,
  position            int not null default 100,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);
create trigger trg_plans_updated before update on public.plans
  for each row execute function public.set_updated_at();

insert into public.plans (key, name, description, price_month_usd, limits, features, position) values
  ('team', 'Team', 'Equipos pequeños o medianos', 550,
   '{"channels": 2, "users": null, "ai_agents": 2, "flows": 20, "conversations_month": 2500, "voice_minutes_month": 0, "campaign_recipients_month": 10000}',
   '{"flows": true, "voice": false, "crm": true, "attribution": true, "api": false, "seller": false, "memory": true}', 1),
  ('professional', 'Profesional', 'Empresas medianas y grandes', 1100,
   '{"channels": 3, "users": null, "ai_agents": 5, "flows": 100, "conversations_month": 5500, "voice_minutes_month": 1000, "campaign_recipients_month": 50000}',
   '{"flows": true, "voice": true, "crm": true, "attribution": true, "api": true, "seller": true, "memory": true}', 2),
  ('enterprise', 'Enterprise', 'Corporaciones y multinacionales', 5400,
   '{"channels": 5, "users": null, "ai_agents": null, "flows": null, "conversations_month": 20000, "voice_minutes_month": 10000, "campaign_recipients_month": null}',
   '{"flows": true, "voice": true, "crm": true, "attribution": true, "api": true, "seller": true, "memory": true}', 3)
on conflict (key) do nothing;

alter table public.organizations
  add column status         text not null default 'active' check (status in ('trial', 'active', 'past_due', 'suspended', 'cancelled')),
  add column plan_id        bigint references public.plans(id),
  add column trial_ends_at  timestamptz,
  add column country        char(2),
  add column billing_email  extensions.citext;

update public.organizations set plan_id = (select id from public.plans where key = 'enterprise') where plan_id is null;

-- Un usuario de Supabase Auth puede pertenecer a varias empresas: único por organización
alter table public.agents drop constraint if exists agents_auth_user_id_key;
create unique index agents_org_auth_user_uq on public.agents (organization_id, auth_user_id) where auth_user_id is not null;
create index agents_email_idx on public.agents (email);

create table public.subscriptions (
  id                        bigint generated by default as identity primary key,
  organization_id           bigint not null unique references public.organizations(id) on delete cascade,
  plan_id                   bigint not null references public.plans(id),
  provider                  text not null default 'stripe' check (provider in ('stripe', 'manual')),
  provider_customer_id      text,
  provider_subscription_id  text unique,
  status                    text not null check (status in ('trialing', 'active', 'past_due', 'canceled', 'incomplete', 'unpaid')),
  current_period_start      timestamptz,
  current_period_end        timestamptz,
  cancel_at_period_end      boolean not null default false,
  created_at                timestamptz not null default now(),
  updated_at                timestamptz not null default now()
);
create trigger trg_subscriptions_updated before update on public.subscriptions
  for each row execute function public.set_updated_at();

create table public.billing_events (
  id                 bigint generated by default as identity primary key,
  provider           text not null,
  provider_event_id  text not null,
  type               text not null,
  organization_id    bigint references public.organizations(id) on delete set null,
  payload            jsonb not null,
  processed_at       timestamptz,
  error              text,
  created_at         timestamptz not null default now(),
  unique (provider, provider_event_id)       -- idempotencia de webhooks
);

-- ---------------------------------------------------------------------------
-- Consumo: contadores mensuales por métrica (solo eventos de baja frecuencia que se limitan en tiempo real).
-- Mensajes y costo de IA se leen de reporting.* (sin contención en filas calientes).
-- ---------------------------------------------------------------------------
create table public.usage_counters (
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  period           date not null,                 -- primer día del mes (UTC)
  metric           text not null check (metric in ('conversations', 'voice_minutes', 'campaign_recipients')),
  value            numeric not null default 0,
  updated_at       timestamptz not null default now(),
  primary key (organization_id, period, metric)
);

create or replace function public.bump_usage(p_org bigint, p_metric text, p_delta numeric) returns void
language sql set search_path = public, pg_temp as $$
  insert into public.usage_counters (organization_id, period, metric, value)
  values (p_org, date_trunc('month', now() at time zone 'UTC')::date, p_metric, p_delta)
  on conflict (organization_id, period, metric)
  do update set value = public.usage_counters.value + excluded.value, updated_at = now();
$$;

create or replace function public.trg_usage_conversations() returns trigger
language plpgsql set search_path = public, pg_temp as $$
begin
  perform public.bump_usage(new.organization_id, 'conversations', 1);
  return null;
end $$;
create trigger trg_conversations_usage after insert on public.conversations
  for each row execute function public.trg_usage_conversations();

create or replace function public.trg_usage_calls() returns trigger
language plpgsql set search_path = public, pg_temp as $$
begin
  if new.duration_s is not null and old.duration_s is null and new.duration_s > 0 then
    perform public.bump_usage(new.organization_id, 'voice_minutes', ceil(new.duration_s / 60.0));
  end if;
  return null;
end $$;
create trigger trg_calls_usage after update of ended_at on public.calls
  for each row execute function public.trg_usage_calls();

create or replace function public.trg_usage_campaign_recipients() returns trigger
language plpgsql set search_path = public, pg_temp as $$
declare org bigint;
begin
  if new.status = 'sent' and old.status is distinct from 'sent' then
    select organization_id into org from public.campaigns where id = new.campaign_id;
    perform public.bump_usage(org, 'campaign_recipients', 1);
  end if;
  return null;
end $$;
create trigger trg_campaign_recipients_usage after update of status on public.campaign_recipients
  for each row execute function public.trg_usage_campaign_recipients();

-- Límite del plan: devuelve {allowed, limit, used}. Métricas de conteo (channels, users...) se calculan en vivo.
create or replace function public.check_limit(p_org bigint, p_metric text) returns jsonb
language plpgsql stable set search_path = public, pg_temp as $$
declare
  lim numeric;
  used numeric;
  v_period date := date_trunc('month', now() at time zone 'UTC')::date;
begin
  select (p.limits ->> p_metric)::numeric into lim
  from public.organizations o join public.plans p on p.id = o.plan_id where o.id = p_org;
  used := case p_metric
    when 'channels' then (select count(*) from public.channels where organization_id = p_org)
    when 'users' then (select count(*) from public.agents where organization_id = p_org and is_active)
    when 'ai_agents' then (select count(*) from public.ai_agents where organization_id = p_org)
    when 'flows' then (select count(*) from public.flows where organization_id = p_org and status <> 'archived')
    when 'conversations_month' then coalesce((select value from public.usage_counters
                               where organization_id = p_org and period = v_period and metric = 'conversations'), 0)
    when 'voice_minutes_month' then coalesce((select value from public.usage_counters
                               where organization_id = p_org and period = v_period and metric = 'voice_minutes'), 0)
    when 'campaign_recipients_month' then coalesce((select value from public.usage_counters
                               where organization_id = p_org and period = v_period and metric = 'campaign_recipients'), 0)
    else 0 end;
  return jsonb_build_object('metric', p_metric, 'limit', lim, 'used', used, 'allowed', lim is null or used < lim);
end $$;

-- Back-office del dueño de la plataforma
create table public.platform_admins (
  id             bigint generated by default as identity primary key,
  email          extensions.citext not null unique,
  name           text not null,
  password_hash  text,
  auth_user_id   uuid unique,
  created_at     timestamptz not null default now()
);

-- Seguridad: funciones internas fuera de la API pública
revoke execute on function public.bump_usage(bigint, text, numeric), public.trg_usage_conversations(),
  public.trg_usage_calls(), public.trg_usage_campaign_recipients(), public.check_limit(bigint, text) from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then
    revoke execute on function public.bump_usage(bigint, text, numeric), public.trg_usage_conversations(),
      public.trg_usage_calls(), public.trg_usage_campaign_recipients(), public.check_limit(bigint, text)
      from anon, authenticated;
  end if;
end $$;

-- RLS: tablas nuevas de esta fase (lectura por organización; escritura solo backend)
do $$
declare t text;
begin
  foreach t in array array['tracking_sites', 'web_sessions', 'web_events', 'attributions', 'conversion_actions',
    'conversion_events', 'conversion_uploads', 'deals', 'integration_connections', 'integration_mappings',
    'external_links', 'integration_outbox', 'voice_agents', 'calls', 'call_events', 'call_turns', 'plans',
    'subscriptions', 'billing_events', 'usage_counters', 'platform_admins'] loop
    execute format('alter table public.%I enable row level security', t);
  end loop;
end $$;

do $guard$
begin
  if not exists (select 1 from pg_namespace where nspname = 'auth') then
    return;
  end if;
  -- Varias empresas por usuario: la empresa activa viaja en el JWT (app_metadata.org_id)
  execute $f$
    create or replace function private.current_org_id() returns bigint
    language sql stable security definer set search_path = public, pg_temp as $$
      select coalesce(
        (select organization_id from public.agents
          where auth_user_id = auth.uid() and is_active
            and organization_id = nullif(auth.jwt() -> 'app_metadata' ->> 'org_id', '')::bigint),
        (select organization_id from public.agents where auth_user_id = auth.uid() and is_active
          order by organization_id limit 1))
    $$;
  $f$;
  execute $p$
    create policy org_read on public.tracking_sites for select to authenticated using (organization_id = private.current_org_id());
    create policy org_read on public.attributions for select to authenticated using (organization_id = private.current_org_id());
    create policy org_read on public.conversion_actions for select to authenticated using (organization_id = private.current_org_id());
    create policy org_read on public.conversion_events for select to authenticated using (organization_id = private.current_org_id());
    create policy org_read on public.deals for select to authenticated using (organization_id = private.current_org_id());
    create policy org_read on public.voice_agents for select to authenticated using (organization_id = private.current_org_id());
    create policy org_read on public.calls for select to authenticated using (organization_id = private.current_org_id());
    create policy org_read on public.call_turns for select to authenticated
      using (exists (select 1 from public.calls c where c.id = call_id and c.organization_id = private.current_org_id()));
    create policy org_read on public.usage_counters for select to authenticated using (organization_id = private.current_org_id());
    create policy org_read on public.subscriptions for select to authenticated using (organization_id = private.current_org_id());
    create policy public_read on public.plans for select to authenticated using (is_public);
  $p$;
end $guard$;
