-- =============================================================================
-- 02 · Canales, contactos, campos personalizados (EAV tipado), etiquetas, auditoría
-- =============================================================================

create table public.channels (
  id                      bigint generated by default as identity primary key,
  organization_id         bigint not null references public.organizations(id) on delete cascade,
  name                    text not null,
  provider                text not null default 'whatsapp_cloud' check (provider in ('whatsapp_cloud')),
  phone_number_id         text not null unique,
  waba_id                 text,
  display_phone           text,
  access_token_secret_id  uuid,                -- vault.secrets(id); null = token del servidor
  default_ai_agent_id     bigint,              -- FK agregada en 04 (ai_agents)
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);
create index channels_org_idx on public.channels (organization_id);
create trigger trg_channels_updated before update on public.channels
  for each row execute function public.set_updated_at();

create table public.contacts (
  id                 bigint generated by default as identity primary key,
  organization_id    bigint not null references public.organizations(id) on delete cascade,
  wa_id              text not null check (wa_id ~ '^[0-9]{8,15}$'),
  name               text,
  email              citext,
  notes              text,
  stage              text not null default 'lead' check (stage in ('lead', 'prospect', 'client', 'lost')),
  -- Memoria del cliente: perfil vivo compartido por todos los agentes (IA y personas)
  memory             text,
  memory_updated_at  timestamptz,
  marketing_opt_out  boolean not null default false,
  opt_out_at         timestamptz,
  blocked            boolean not null default false,
  blocked_reason     text,
  blocked_at         timestamptz,
  last_seen_at       timestamptz,
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  unique (organization_id, wa_id),
  check (blocked = (blocked_at is not null))
);
create index contacts_org_created_idx on public.contacts (organization_id, created_at desc);
create index contacts_org_stage_idx on public.contacts (organization_id, stage) where not blocked;
create index contacts_blocked_idx on public.contacts (organization_id, blocked_at desc) where blocked;
create index contacts_optout_idx on public.contacts (organization_id, opt_out_at) where marketing_opt_out;
create index contacts_name_trgm on public.contacts using gin (name gin_trgm_ops);
create index contacts_wa_trgm on public.contacts using gin (wa_id gin_trgm_ops);
create trigger trg_contacts_updated before update on public.contacts
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Campos personalizados: definición + valores tipados (filtrables y agregables)
-- ---------------------------------------------------------------------------
create table public.contact_fields (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  key              text not null check (key ~ '^[a-z][a-z0-9_]{0,49}$'),
  label            text not null,
  type             text not null default 'text'
                     check (type in ('text', 'long_text', 'number', 'date', 'select', 'boolean', 'email', 'phone')),
  options          jsonb,                       -- ["Onix", "Tracker"] para select
  description      text,                        -- también guía a la IA
  ai_extract       boolean not null default true,
  agent_editable   boolean not null default true,
  position         int not null default 100,
  archived_at      timestamptz,                 -- borrado lógico: los valores se conservan
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (organization_id, key),
  check (type <> 'select' or jsonb_typeof(options) = 'array')
);
create trigger trg_contact_fields_updated before update on public.contact_fields
  for each row execute function public.set_updated_at();

create table public.contact_field_values (
  contact_id    bigint not null references public.contacts(id) on delete cascade,
  field_id      bigint not null references public.contact_fields(id) on delete cascade,
  value_text    text,
  value_number  numeric,
  value_date    date,
  value_bool    boolean,
  source        text not null check (source in ('agent', 'ai', 'import', 'api')),
  updated_by    bigint references public.agents(id) on delete set null,
  updated_at    timestamptz not null default now(),
  primary key (contact_id, field_id),
  check (num_nonnulls(value_text, value_number, value_date, value_bool) = 1)
);
create index cfv_field_number_idx on public.contact_field_values (field_id, value_number) where value_number is not null;
create index cfv_field_date_idx on public.contact_field_values (field_id, value_date) where value_date is not null;
create index cfv_field_text_idx on public.contact_field_values (field_id, lower(value_text)) where value_text is not null;
create index cfv_field_bool_idx on public.contact_field_values (field_id, value_bool) where value_bool is not null;

-- Historial append-only de la ficha (campos nativos, personalizados y memoria)
create table public.contact_changes (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  contact_id       bigint not null references public.contacts(id) on delete cascade,
  field_key        text not null,
  old_value        text,
  new_value        text,
  source           text not null check (source in ('agent', 'ai', 'import', 'api', 'flow')),
  agent_id         bigint references public.agents(id) on delete set null,
  conversation_id  bigint,                      -- FK agregada en 03
  created_at       timestamptz not null default now()
);
create index contact_changes_contact_idx on public.contact_changes (contact_id, created_at desc);
create index contact_changes_last_idx on public.contact_changes (contact_id, field_key, id desc);

-- ---------------------------------------------------------------------------
-- Etiquetas (catálogo por organización) y etiquetas de contacto
-- ---------------------------------------------------------------------------
create table public.tags (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  name             text not null check (name = lower(btrim(name)) and name <> ''),
  scope            text not null default 'both' check (scope in ('conversation', 'contact', 'both')),
  ai_description   text,                        -- criterio para la IA; null = la IA no la usa
  color            text,
  created_at       timestamptz not null default now(),
  unique (organization_id, name)
);

create table public.contact_tags (
  contact_id  bigint not null references public.contacts(id) on delete cascade,
  tag_id      bigint not null references public.tags(id) on delete cascade,
  source      text not null default 'agent' check (source in ('agent', 'ai', 'import', 'rule', 'flow')),
  created_at  timestamptz not null default now(),
  primary key (contact_id, tag_id)
);
create index contact_tags_tag_idx on public.contact_tags (tag_id);
