-- =============================================================================
-- 25 · Configuración avanzada del agente de IA, etapas por línea de negocio, recuperación por inactividad,
--      reglas de seguridad y webhooks entrantes (docs/data-model.md §17)
-- =============================================================================

-- Agente de IA: contexto de pauta, optimización de costos, seguridad, recuperación, zona horaria ------------------
alter table public.ai_agents
  add column timezone                 text,              -- null = la de la empresa
  add column max_words                int check (max_words between 20 and 2000),
  -- Reconocimiento de pauta: el primer mensaje se personaliza con el anuncio / publicación / enlace de origen
  add column ad_context_enabled       boolean not null default true,
  add column ad_context_prompt        text,
  -- Reglas por fuente: [{match: {channel?, source_type?, ad_id?, campaign_contains?, link_id?, portal?: "mercadolibre"|
  --   "tucarro"|..., text_contains?}, actions: {group_id?, tags?[], stage?: {pipeline, key}, skip_intent_question?,
  --   handoff?: bool, note?}}]  (validado con JSON Schema en la app)
  add column source_rules             jsonb not null default '[]'::jsonb,
  -- Optimización de costos de WhatsApp: agrupa mensajes consecutivos, evita plantillas dentro de la ventana de servicio,
  -- recupera solo dentro de la ventana gratuita y prioriza la ventana de 72 h de Click to WhatsApp
  add column cost_optimization        boolean not null default true,
  -- Seguridad: detecta spam o intención maliciosa y termina la conversación
  add column security_enabled         boolean not null default true,
  add column security_prompt          text,
  add column security_action          text not null default 'close' check (security_action in ('close', 'block', 'handoff', 'flag')),
  -- Recuperación por inactividad: hasta 3 intentos [{after_hours (≤12), message (guía o texto), use_ai: bool}]
  add column recovery_enabled         boolean not null default false,
  add column recovery_attempts        jsonb not null default '[]'::jsonb
                                        check (jsonb_typeof(recovery_attempts) = 'array' and jsonb_array_length(recovery_attempts) <= 3),
  add column inactivity_end_hours     numeric(5, 2),     -- fin por inactividad (después del último intento)
  add column inactivity_end_typification_id bigint references public.typifications(id) on delete set null,
  -- Campos que este agente debe identificar (vacío = todos los contact_fields con ai_extract)
  add column extract_field_ids        bigint[] not null default '{}';

-- Estado de recuperación por conversación
alter table public.conversations
  add column recovery_attempts_sent  smallint not null default 0,
  add column last_recovery_at        timestamptz,
  add column security_flag           text;            -- spam | abuse | phishing | null
create index conv_recovery_idx on public.conversations (organization_id, last_inbound_at)
  where status = 'bot' and closed_at is null;

alter table public.conversation_events drop constraint conversation_events_event_type_check;
alter table public.conversation_events add constraint conversation_events_event_type_check check (event_type in
  ('created', 'reopened', 'handoff', 'released', 'assigned', 'unassigned', 'routed', 'first_agent_response',
   'tagged', 'untagged', 'typified', 'classified', 'closed', 'flow_started', 'flow_finished', 'campaign_sent',
   'deal_won', 'deal_lost', 'call_started', 'call_ended',
   'recovery_sent', 'inactivity_closed', 'security_flagged', 'stage_changed', 'source_rule_applied', 'webhook_triggered'));

-- Etapas por línea de negocio (Lead → MQL → SQL…) con condición para la IA ----------------------------------
create table public.pipeline_stages (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  pipeline         text not null,                -- nuevos | usados | taller | repuestos_accesorios | pqr | default…
  key              text not null check (key ~ '^[a-z][a-z0-9_]{0,49}$'),
  name             text not null,                -- "MQL (Marketing Qualified Lead)"
  external_name    text,                         -- nombre en el CRM / Atom
  ai_condition     text,                         -- cuándo la IA marca esta etapa (null = solo manual)
  position         int not null default 100,
  probability      smallint check (probability between 0 and 100),
  is_won           boolean not null default false,
  is_lost          boolean not null default false,
  is_active        boolean not null default true,
  created_at       timestamptz not null default now(),
  unique (organization_id, pipeline, key),
  check (not (is_won and is_lost))
);

create table public.deal_stage_events (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  deal_id          bigint not null references public.deals(id) on delete cascade,
  from_stage       text,
  to_stage         text not null,
  source           text not null check (source in ('ai', 'agent', 'flow', 'crm', 'api', 'rule', 'webhook')),
  reason           text,                         -- evidencia / condición cumplida
  confidence       real,
  agent_id         bigint references public.agents(id) on delete set null,
  conversation_id  bigint references public.conversations(id) on delete set null,
  created_at       timestamptz not null default now()
);
create index deal_stage_events_deal_idx on public.deal_stage_events (deal_id, created_at);
create index deal_stage_events_org_idx on public.deal_stage_events (organization_id, created_at);
alter table public.deals add column stage_changed_at timestamptz;

-- Tipificaciones más ricas (sección, palabra clave, grupos, reactivar el bot, datos de venta) --------------------
alter table public.typifications
  add column section                 text check (section in ('positive', 'negative', 'followup', 'neutral')),
  add column keyword                 text,
  add column group_ids               bigint[] not null default '{}',   -- vacío = todos los grupos
  add column reactivate_bot_after_h  numeric(6, 2),                    -- vuelve al bot tras N horas
  add column required_fields         text[] not null default '{}';     -- ej. {deal.amount, deal.currency, invoice}
create unique index typifications_keyword_idx on public.typifications (organization_id, lower(keyword))
  where keyword is not null;

-- Webhooks entrantes (sistemas externos: agenda de taller, DMS, ERP…) --------------------------------------------
create table public.inbound_webhooks (
  id               bigint generated by default as identity primary key,
  organization_id  bigint not null references public.organizations(id) on delete cascade,
  name             text not null,                -- "Confirmación Cita V.5"
  slug             text not null unique,         -- /hooks/{slug}
  token_hash       text not null,                -- sha256 del token (cabecera X-Hook-Token o ?token=)
  status           text not null default 'active' check (status in ('draft', 'active', 'paused')),
  action           text not null check (action in
                     ('send_template', 'send_text', 'start_flow', 'upsert_contact', 'create_deal', 'create_appointment')),
  channel_id       bigint references public.channels(id) on delete set null,
  template_name    text,
  template_language text,
  flow_id          bigint references public.flows(id) on delete set null,
  -- [{name, label, type(text|number|date|datetime|phone|email|url|currency), required, example,
  --   maps_to: "recipient.phone" | "recipient.bsuid" | "template.header.1" | "template.body.N" | "template.button.N" |
  --            "contact.name" | "field:<key>" | "key:<golden_type>" | "vehicle.<attr>" | "deal.<attr>" |
  --            "appointment.<attr>" | "flow.var.<name>"}]
  params           jsonb not null default '[]'::jsonb check (jsonb_typeof(params) = 'array'),
  -- {assign_group_id, assign_agent_id, bot: on|off, tags[], typification, pipeline, dedupe_minutes}
  options          jsonb not null default '{}'::jsonb,
  version          int not null default 1,
  executions       bigint not null default 0,
  succeeded        bigint not null default 0,
  failed           bigint not null default 0,
  last_run_at      timestamptz,
  created_by       bigint references public.agents(id) on delete set null,
  published_at     timestamptz,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (organization_id, name)
);
create trigger trg_inbound_webhooks_updated before update on public.inbound_webhooks
  for each row execute function public.set_updated_at();

create table public.inbound_webhook_runs (
  id               bigint generated by default as identity,
  organization_id  bigint not null,
  webhook_id       bigint not null,
  status           text not null check (status in ('succeeded', 'failed', 'rejected', 'duplicate')),
  http_status      smallint not null,
  payload          jsonb,                        -- parámetros recibidos (recortados)
  result           jsonb,                        -- ids creados / message_id
  contact_id       bigint,
  conversation_id  bigint,
  error            text,
  latency_ms       int,
  ip               text,
  idempotency_key  text,
  created_at       timestamptz not null default now(),
  primary key (id, created_at)
) partition by range (created_at);
create table public.inbound_webhook_runs_default partition of public.inbound_webhook_runs default;
select public.ensure_monthly_partitions('public.inbound_webhook_runs', 3);
create index inbound_webhook_runs_hook_idx on public.inbound_webhook_runs (webhook_id, created_at desc);
create index inbound_webhook_runs_idem_idx on public.inbound_webhook_runs (webhook_id, idempotency_key, created_at)
  where idempotency_key is not null;

-- Contadores (ejecuciones / exitosas / erróneas) mantenidos por la base
create or replace function private.trg_inbound_webhook_runs_counters() returns trigger
language plpgsql set search_path = public, pg_temp as $$
begin
  update public.inbound_webhooks set executions = executions + 1,
    succeeded = succeeded + (new.status = 'succeeded')::int,
    failed = failed + (new.status in ('failed', 'rejected'))::int,
    last_run_at = new.created_at
  where id = new.webhook_id;
  return null;
end $$;
revoke all on function private.trg_inbound_webhook_runs_counters() from public;
create trigger trg_inbound_webhook_runs_counters after insert on public.inbound_webhook_runs
  for each row execute function private.trg_inbound_webhook_runs_counters();

do $$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    perform cron.schedule('inbound-webhook-runs-partitions', '25 3 * * *', $c$
      select public.ensure_monthly_partitions('public.inbound_webhook_runs', 3);
      select public.drop_old_partitions('public.inbound_webhook_runs', 6);
    $c$);
  end if;
end $$;

-- RLS
alter table public.pipeline_stages enable row level security;
alter table public.deal_stage_events enable row level security;
alter table public.inbound_webhooks enable row level security;
alter table public.inbound_webhook_runs enable row level security;
do $$
begin
  if exists (select 1 from pg_namespace where nspname = 'auth') then
    execute 'create policy org_read on public.pipeline_stages for select to authenticated
             using (organization_id = private.current_org_id())';
    execute 'create policy org_read on public.deal_stage_events for select to authenticated
             using (organization_id = private.current_org_id())';
  end if;
end $$;
